# Generated by Django 3.2.14 on 2022-07-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_assessment_epi_version'),
        ('assessmentvalues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentvalues',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_list', to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentvalues',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
