# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_auto_20170806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='enable_project_management',
            field=models.BooleanField(default=True, help_text='Enable project management module for data extraction and Study Evaluation. If enabled, each study will have multiple tasks which can be assigned and tracked for completion.'),
        ),
    ]
