# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-07 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20180103_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='enable_bmd',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text="Conduct benchmark dose (BMD) modeling on animal bioassay data available in the HAWC database, using the US EPA's Benchmark Dose Modeling Software (BMDS).", verbose_name='Enable BMD modeling'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enable_data_extraction',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text='Extract animal bioassay, epidemiological, or in-vitro data from key references and create customizable, dynamic visualizations or summary data and associated metadata for display.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enable_literature_review',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text='Search or import references from PubMed and other literature databases, define inclusion, exclusion, or descriptive tags, and apply these tags to retrieved literature for your analysis.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enable_project_management',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text='Enable project management module for data extraction and Study Evaluation. If enabled, each study will have multiple tasks which can be assigned and tracked for completion.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enable_risk_of_bias',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text='Define criteria for a systematic review of literature, and apply these criteria to references in your literature-review. View details on findings and identify areas with a potential risk of bias.'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enable_summary_text',
            field=models.PositiveIntegerField(choices=[(2, 'Publicly Visible'), (1, 'Internal Only'), (0, 'Diabled')], default=1, help_text='Create custom-text to describe methodology and results of the assessment; insert tables, figures, and visualizations to using "smart-tags" which link to other data in HAWC.'),
        ),
    ]
