# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0002_auto_20150723_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmd_model_run',
            name='BMD_session',
        ),
        migrations.RemoveField(
            model_name='bmd_session',
            name='dose_units',
        ),
        migrations.RemoveField(
            model_name='bmd_session',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='bmd_session',
            name='selected_model',
        ),
        migrations.DeleteModel(
            name='BMD_model_run',
        ),
        migrations.DeleteModel(
            name='BMD_session',
        ),
    ]
