# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 20:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0018_auto_20160602_1007'),
        ('assessment', '0007_auto_20160426_1124'),
        ('bmd', '0003_auto_20160620_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveSmallIntegerField()),
                ('bmr_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=25)),
                ('defaults', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('overrides', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_executed', models.DateTimeField(null=True)),
                ('execution_error', models.BooleanField(default=False)),
                ('dfile', models.TextField(blank=True)),
                ('plot', models.ImageField(blank=True, upload_to=b'bmds_plot')),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='BMDSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmds_version', models.CharField(choices=[(b'2.30', b'Version 2.30'), (b'2.31', b'Version 2.31'), (b'2.40', b'Version 2.40')], max_length=10)),
                ('bmrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_executed', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dose_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_sessions', to='assessment.DoseUnits')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_sessions', to='animal.Endpoint')),
            ],
            options={
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='SelectedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_model', to='animal.Endpoint')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmd.BMDModel')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='bmdmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmd.BMDSession'),
        ),
    ]
