# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0003_auto_20160722_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsettings',
            name='version',
            field=models.CharField(choices=[('BMDS230', 'BMDS v2.3.0'), ('BMDS231', 'BMDS v2.3.1'), ('BMDS240', 'BMDS v2.4.0'), ('BMDS260', 'BMDS v2.6.0'), ('BMDS2601', 'BMDS v2.6.0.1')], default='BMDS2601', max_length=10),
        ),
        migrations.AlterField(
            model_name='logicfield',
            name='cancer_dichotomous_on',
            field=models.BooleanField(default=True, verbose_name='Cancer Dichotomous Datasets'),
        ),
        migrations.AlterField(
            model_name='logicfield',
            name='continuous_on',
            field=models.BooleanField(default=True, verbose_name='Continuous Datasets'),
        ),
        migrations.AlterField(
            model_name='logicfield',
            name='dichotomous_on',
            field=models.BooleanField(default=True, verbose_name='Dichotomous Datasets'),
        ),
        migrations.AlterField(
            model_name='logicfield',
            name='failure_bin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Warning (no change)'), (1, 'Questionable'), (2, 'Not Viable')], help_text='If the test fails, select the model-bin should the model be placed into.'),
        ),
        migrations.AlterField(
            model_name='logicfield',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If a threshold is required for the test, threshold can be specified to non-default.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='plot',
            field=models.ImageField(blank=True, upload_to='bmds_plot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='version',
            field=models.CharField(choices=[('BMDS230', 'BMDS v2.3.0'), ('BMDS231', 'BMDS v2.3.1'), ('BMDS240', 'BMDS v2.4.0'), ('BMDS260', 'BMDS v2.6.0'), ('BMDS2601', 'BMDS v2.6.0.1')], max_length=10),
        ),
    ]
