# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0004_auto_20160621_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmdmodel',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='bmdsession',
            options={'get_latest_by': 'last_updated', 'ordering': ('-last_updated',)},
        ),
    ]
