# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0005_auto_20160621_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmd_assessment_settings',
            old_name='BMDS_version',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='bmd_assessment_settings',
            name='version',
            field=models.CharField(choices=[(b'2.30', b'Version 2.30'), (b'2.31', b'Version 2.31'), (b'2.40', b'Version 2.40'), (b'2.60', b'Version 2.60'), (b'2.601', b'Version 2.601')], default=b'2.601', max_length=10),
        ),
        migrations.RenameField(
            model_name='bmdsession',
            old_name='bmds_version',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='bmdsession',
            name='version',
            field=models.CharField(choices=[(b'2.30', b'Version 2.30'), (b'2.31', b'Version 2.31'), (b'2.40', b'Version 2.40'), (b'2.60', b'Version 2.60'), (b'2.601', b'Version 2.601')], max_length=10),
        ),
    ]
