# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0006_auto_20160712_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmdmodel',
            options={'get_latest_by': 'created', 'ordering': ('model_id',)},
        ),
        migrations.RemoveField(
            model_name='bmdmodel',
            name='defaults',
        ),
        migrations.AlterField(
            model_name='bmdmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='bmd.BMDSession'),
        ),
    ]
