# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0007_auto_20160714_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmdmodel',
            old_name='outputs',
            new_name='output',
        ),
        migrations.AddField(
            model_name='bmdmodel',
            name='outfile',
            field=models.TextField(blank=True),
        ),
    ]
