# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0008_auto_20160719_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logicfield',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='logicfield',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='logicfield',
            name='logic_id',
        ),
    ]
