# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 15:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd', '0009_auto_20160721_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmdsession',
            name='bmrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
