# Generated by Django 3.2.12 on 2022-07-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0018_django31"),
        ("eco", "0002_load_fixtures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cause",
            name="units",
        ),
        migrations.RemoveField(
            model_name="design",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="effect",
            name="modifying_factors",
        ),
        migrations.RemoveField(
            model_name="result",
            name="study",
        ),
        migrations.AddField(
            model_name="cause",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="design",
            name="country",
            field=models.ManyToManyField(
                help_text="Select one or more countries", related_name="country", to="epi.Country"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="effect",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="result",
            name="modifying_factors",
            field=models.CharField(
                default="",
                help_text="Type a comma-separated list of any modifying factors, confounding variables, model co-variates, etc. that were analyzed and tested for the potential to influence the relationship between cause and effect",
                max_length=256,
                verbose_name="Modifying factors",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="duration",
            field=models.CharField(
                help_text="Describe the duration or range of durations of the treatment/exposure",
                max_length=128,
                verbose_name="Cause/treatment duration",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="duration_units",
            field=models.CharField(
                blank=True,
                help_text="Type the unit associated with the cause duration term. Autocomplete.",
                max_length=128,
                verbose_name="Cause/treatment duration units",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="level_units",
            field=models.CharField(
                help_text="Type the units associated with the cause value term",
                max_length=128,
                verbose_name="Cause/treatment level units",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="measure",
            field=models.ForeignKey(
                help_text="Add help text - autocomplete field?",
                limit_choices_to={"category": 4},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eco.vocab",
                verbose_name="Cause measure",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="species",
            field=models.CharField(
                blank=True,
                help_text="Type the species name, if applicable; use the format Common name (Latin binomial)",
                max_length=128,
                verbose_name="Cause/treatment species",
            ),
        ),
        migrations.AlterField(
            model_name="cause",
            name="term",
            field=models.ForeignKey(
                help_text="Add help text - autocomplete field?",
                limit_choices_to={"category": 3},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eco.vocab",
                verbose_name="Cause term",
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="measure_detail",
            field=models.CharField(
                blank=True,
                help_text="Add help-text. autocomplete?",
                max_length=128,
                verbose_name="Effect measure detail",
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="species",
            field=models.CharField(
                blank=True,
                help_text="Type the species name, if applicable; use the format Common name (Latin binomial)",
                max_length=128,
                verbose_name="Effect species",
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="units",
            field=models.CharField(
                help_text="Type the unit associated with the effect term. autocomplete?",
                max_length=128,
                verbose_name="Effect units",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="cause",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eco.cause"),
        ),
        migrations.AlterField(
            model_name="result",
            name="effect",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eco.effect"),
        ),
        migrations.AlterField(
            model_name="result",
            name="measure_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Select one response measure type",
                limit_choices_to=models.Q(("category", 8), ("parent__isnull", False)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eco.vocab",
                verbose_name="Response measure type",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="modifying_factors_comment",
            field=models.TextField(
                blank=True,
                help_text="Describe how the important modifying factor(s) affect the relationship in 1-2 sentences. Consider factors associated with the study that have an important influence on the relationship between cause and effect. For example, statistical significance of a co-variate in a model can indicate importance.",
                max_length=256,
                verbose_name="Modifying factors comment",
            ),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="value",
            field=models.CharField(max_length=128),
        ),
    ]
