# Generated by Django 3.2.16 on 2023-02-27 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eco", "0004_updates_0223"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="result",
            options={
                "ordering": ("design", "cause", "effect", "sort_order"),
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
            },
        ),
        migrations.AlterUniqueTogether(
            name="result",
            unique_together=set(),
        ),
    ]
