# Generated by Django 3.2.14 on 2022-08-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco", "0005_load_nestedterms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cause",
            name="measure",
        ),
        migrations.RemoveField(
            model_name="cause",
            name="measure_detail",
        ),
        migrations.RemoveField(
            model_name="effect",
            name="measure",
        ),
        migrations.RemoveField(
            model_name="effect",
            name="measure_detail",
        ),
        migrations.AlterField(
            model_name="cause",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="causes",
                to="eco.nestedterm",
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effects",
                to="eco.nestedterm",
            ),
        ),
    ]
