# Generated by Django 3.2.14 on 2022-08-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0012_study_eco"),
        ("eco", "0006_auto_20220804_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eco_designs",
                to="study.study",
            ),
        ),
    ]
