# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20170806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='published',
            field=models.BooleanField(default=False, help_text='If True, this study, Study Evaluation, and extraction details may be visible to reviewers and/or the general public (if assessment-permissions allow this level of visibility). Team-members and project-management can view both published and unpublished studies.'),
        ),
    ]
