# Generated by Django 1.9.4 on 2016-03-30 22:23


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study", "0002_auto_20151130_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyquality",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
