# Generated by Django 1.9.8 on 2016-07-25 16:28


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0007_migrate_study_type"),
    ]

    operations = [
        # remove field
        migrations.RemoveField(
            model_name="study",
            name="study_type",
        ),
    ]
