# Generated by Django 1.11.15 on 2019-04-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0009_py3_unicode"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="editable",
            field=models.BooleanField(
                default=True,
                help_text="Project-managers and team-members are allowed to edit this study.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="ask_author",
            field=models.TextField(
                blank=True,
                help_text="Details on correspondence between data-extractor and author (if author contacted). Redact confidential or personal information (e.g., email address).",
                verbose_name="Correspondence details",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="coi_details",
            field=models.TextField(
                blank=True,
                help_text="Details related to potential or disclosed conflict(s) of interest. When available, cut and paste the COI declaration with quotations. Provide details when a COI is inferred.",
                verbose_name="COI details",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="coi_reported",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (4, "---"),
                    (0, "Authors report they have no COI"),
                    (1, "Authors disclosed COI"),
                    (2, "Unknown"),
                    (3, "Not reported"),
                ],
                default=4,
                help_text="Was a conflict of interest reported by the study authors?",
                verbose_name="COI reported",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="contact_author",
            field=models.BooleanField(
                default=False,
                help_text="Was the author contacted for clarification of methods, results, or to request additional data?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="funding_source",
            field=models.TextField(
                blank=True,
                help_text='When reported, cut and paste the funding source information with quotations, e.g., "The study was sponsored by Hoechst AG and Dow Europe".',
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="If True, this study, study evaluation, and extraction details may be visible to reviewers and/or the public (if assessment-permissions allow this level of visibility). Team-members and project-management can view both published and unpublished studies.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="This field is often left blank, but used to add comments on data extraction or other general comments. This field is displayed if an assessment is made public.",
                verbose_name="Summary/extraction comments",
            ),
        ),
    ]
