# Generated by Django 3.2.14 on 2022-07-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0011_auto_20190416_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
