# Generated by Django 3.2.14 on 2022-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0011_auto_20190416_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="eco",
            field=models.BooleanField(
                default=False, help_text="Study contains ecology data", verbose_name="Ecology"
            ),
        ),
    ]
