# Generated by Django 5.2.12 on 2026-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0012_study_eco"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="mechanistic",
            field=models.BooleanField(default=False, help_text="Study contains mechanistic data"),
        ),
    ]
