version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "monthly"


updates:
  - package-ecosystem: uv
    directory: /
    multi-ecosystem-group: "infrastructure"
    patterns: ["**/*"]
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "Django"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: frontend
    multi-ecosystem-group: "infrastructure"
    patterns: ["**/*"]
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "mobx-react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: .github
    multi-ecosystem-group: "infrastructure"
    patterns: ["**/*"]
    cooldown:
      default-days: 7
