# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_endpointrobtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointrobtask',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='endpointrobtask',
            name='owner',
        ),
        migrations.DeleteModel(
            name='EndpointRobTask',
        ),
    ]
