# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_auto_20170806_1721'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mgmt', '0003_auto_20171213_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointRobTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'not started'), (20, 'started'), (30, 'completed'), (40, 'abandoned')], default=10)),
                ('open', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='animal.Endpoint')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpointRobTasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('endpoint',),
            },
        ),
    ]
