# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
mkdocs:
  configuration: docs/mkdocs.yml
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
