# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  image: testing  # https://hub.docker.com/r/readthedocs/build/

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - requirements: requirements/dev.txt
