# Generated by Django 3.1.3 on 2021-04-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_load_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
