# Generated by Django 3.1.3 on 2021-04-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0004_term_uid"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
    ]
