# Generated by Django 3.1.3 on 2021-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0005_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term", name="uid", field=models.PositiveIntegerField(unique=True),
        ),
    ]
