# Generated by Django 5.0.6 on 2024-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocab", "0007_load_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="namespace",
            field=models.PositiveSmallIntegerField(choices=[(1, "EHV"), (2, "ToxRef")], default=1),
        ),
    ]
