# Generated by Django 5.1.1 on 2024-10-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animal", "0032_experiment_guideline"),
        ("vocab", "0008_alter_term_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidelineProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guideline_id", models.PositiveIntegerField()),
                (
                    "obs_status",
                    models.CharField(
                        choices=[
                            ("NM", "NM"),
                            ("not required", "not required"),
                            ("recommended", "recommended"),
                            ("required", "required"),
                            ("triggered", "triggered"),
                        ],
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab.term",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("id",),
            },
        )
    ]
