# Generated by Django 5.2.2 on 2025-06-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocab", "0008_alter_term_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guideline",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=64)),
                ("profile_name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="entity",
            name="terms",
            field=models.ManyToManyField(
                related_name="entities",
                through="vocab.EntityTermRelation",
                through_fields=("entity", "term"),
                to="vocab.term",
            ),
        ),
        migrations.CreateModel(
            name="GuidelineProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "obs_status",
                    models.CharField(
                        choices=[
                            ("NM", "NM"),
                            ("not required", "not required"),
                            ("recommended", "recommended"),
                            ("required", "required"),
                            ("triggered", "triggered"),
                        ],
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab.term",
                    ),
                ),
                (
                    "guideline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="vocab.guideline",
                    ),
                ),
            ],
            options={"ordering": ("guideline_id", "id")},
        ),
    ]
