# Generated by Django 1.11.15 on 2019-04-17 01:35

from django.db import migrations

from ...common.models import CustomURLField


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0010_py3_unicode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="full_text_url",
            field=CustomURLField(
                blank=True,
                help_text="Link to full-text URL from journal site (may require increased access privileges to view)",
            ),
        ),
    ]
