# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-09 23:47
from __future__ import unicode_literals

import json
import re

from django.db import migrations, models

from hawc.apps.lit.constants import HERO, PUBMED, RIS


def set_null_content(apps, schema_editor):
    num_updated = (
        apps.get_model("lit", "Identifiers").objects.filter(content="None").update(content="")
    )
    print(f"Updated {num_updated} items renaming content from 'None' to ''")


def set_authors(apps, schema_editor):
    Identifiers = apps.get_model("lit", "Identifiers")
    qs = Identifiers.objects.filter(database__in=[PUBMED, HERO])
    for idx, identifier in enumerate(qs.iterator()):
        if idx % 1000 == 0:
            print(f"Processing Pubmed/HERO {idx:,} ...")
        if len(identifier.content):
            content = json.loads(identifier.content)
            if "authors_list" in content:
                identifier.authors = ", ".join(content["authors"])
                identifier.save()

    # TODO - move this code somewhere else
    # 2 or 3 sequential single capital-letters with single spaces between
    pattern = re.compile(r"([A-Z])\s([A-Z])\s?([A-Z])?")
    qs = Identifiers.objects.filter(database=RIS)
    for idx, identifier in enumerate(qs.iterator()):
        if idx % 1000 == 0:
            print(f"Processing Pubmed/HERO {idx:,} ...")
        if len(identifier.content):
            authors_list = json.loads(json.loads(identifier.content)["json"])["authors"]
            if len(authors_list) == 0:
                raise ValueError(f'No authors in authors list: "{authors_list}"')
            elif len(authors_list) == 1:
                authors = authors_list
            elif len(authors_list) > 1:
                authors = pattern.sub(
                    r"\1\2\3",
                    ", ".join(author.replace(",", "").replace(".", "") for author in authors_list),
                )
            identifier.authors = authors
            identifier.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lit", "0011_auto_20190416_2035"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference", old_name="authors", new_name="authors_short",
        ),
        migrations.AlterField(
            model_name="reference",
            name="authors_short",
            field=models.TextField(
                blank=True, help_text='Short-text for to display (eg., "Smith et al.")'
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="authors",
            field=models.TextField(
                blank=True,
                help_text='The complete, comma separated authors list, (eg., "Smith JD, Tom JF, McFarlen PD")',
            ),
        ),
        migrations.RunPython(set_null_content, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_authors, reverse_code=migrations.RunPython.noop),
    ]
