# Generated by Django 2.2.11 on 2020-04-12 19:08

import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0013_literatureassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="literatureassessment",
            name="topic_tsne_data",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=str(settings.PRIVATE_DATA_ROOT)
                ),
                upload_to="lit/topic_model",
            ),
        ),
        migrations.AddField(
            model_name="literatureassessment",
            name="topic_tsne_last_refresh",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="literatureassessment",
            name="topic_tsne_refresh_requested",
            field=models.DateTimeField(null=True),
        ),
    ]
