# Generated by Django 4.1.5 on 2023-01-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit", "0016_doi_lowercase"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="identifiers",
            new_name="lit_identif_databas_394ab9_idx",
            old_fields=("database", "unique_id"),
        ),
        migrations.AlterField(
            model_name="referencetags",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="lit.referencefiltertag",
            ),
        ),
    ]
