# Generated by Django 4.2.3 on 2023-07-14 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0018_rename_identifiers_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literatureassessment",
            name="topic_tsne_data",
        ),
        migrations.RemoveField(
            model_name="literatureassessment",
            name="topic_tsne_last_refresh",
        ),
        migrations.RemoveField(
            model_name="literatureassessment",
            name="topic_tsne_refresh_requested",
        ),
    ]
