# Generated by Django 4.2.1 on 2023-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0018_rename_identifiers_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literatureassessment",
            name="keyword_list_1",
            field=models.TextField(
                blank=True,
                help_text='Keywords to highlight in titles and abstracts on the reference tagging page.\n         Keywords are pipe-separated ("|") to allow for highlighting chemicals which may include\n         commas. Keywords can be whole word matches or partial matches. To have a partial match,\n         add "*" to the end of the keyword. For example rat|phos*, it should match rat, but not\n         rats, as well as phos, phosphate, and phosphorous.',
            ),
        ),
        migrations.AlterField(
            model_name="literatureassessment",
            name="keyword_list_2",
            field=models.TextField(
                blank=True,
                help_text='Keywords to highlight in titles and abstracts on the reference tagging page.\n         Keywords are pipe-separated ("|") to allow for highlighting chemicals which may include\n         commas. Keywords can be whole word matches or partial matches. To have a partial match,\n         add "*" to the end of the keyword. For example rat|phos*, it should match rat, but not\n         rats, as well as phos, phosphate, and phosphorous.',
            ),
        ),
        migrations.AlterField(
            model_name="literatureassessment",
            name="keyword_list_3",
            field=models.TextField(
                blank=True,
                help_text='Keywords to highlight in titles and abstracts on the reference tagging page.\n         Keywords are pipe-separated ("|") to allow for highlighting chemicals which may include\n         commas. Keywords can be whole word matches or partial matches. To have a partial match,\n         add "*" to the end of the keyword. For example rat|phos*, it should match rat, but not\n         rats, as well as phos, phosphate, and phosphorous.',
            ),
        ),
    ]
