# Generated by Django 4.2.3 on 2023-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0019_remove_literatureassessment_topic_tsne_data_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userreferencetag",
            constraint=models.UniqueConstraint(
                fields=("user", "reference"), name="user_reference_tag"
            ),
        ),
    ]
