# Generated by Django 4.2.4 on 2023-08-14 16:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0019_remove_literatureassessment_topic_tsne_data_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "abstract",
                    "title",
                    "authors",
                    "authors_short",
                    "year",
                    "journal",
                    config="english",
                ),
                name="search_vector_idx",
            ),
        ),
    ]
