# Generated by Django 4.2.6 on 2023-10-30 02:58

import django.contrib.postgres.fields
from django.contrib.postgres.aggregates import ArrayAgg
from django.db import migrations, models


def add_deletions(apps, schema_editor):
    UserReferenceTag = apps.get_model("lit", "UserReferenceTag")
    user_tag_qs = UserReferenceTag.objects.filter(is_resolved=False).annotate(
        ref_tags=ArrayAgg("reference__tags__id"), user_tags=ArrayAgg("tags__id")
    )
    for user_tag in user_tag_qs:
        user_tag.deleted_tags = list(set(user_tag.ref_tags).difference(set(user_tag.user_tags)))
    UserReferenceTag.objects.bulk_update(user_tag_qs, ["deleted_tags"])


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0021_reference_search_vector_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreferencetag",
            name="deleted_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.RunPython(add_deletions, reverse_code=migrations.RunPython.noop),
    ]
