# Generated by Django 4.2.3 on 2023-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0021_reference_search_vector_idx"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="referencetags",
            constraint=models.UniqueConstraint(
                fields=("content_object", "tag"), name="reference_tag"
            ),
        ),
    ]
