# Generated by Django 4.2.6 on 2023-10-30 15:34

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    ReferenceTags = apps.get_model("lit", "ReferenceTags")
    unique_tags = ReferenceTags.objects.distinct("content_object", "tag")
    duplicate_tags = (
        ReferenceTags.objects.all().difference(unique_tags).values_list("id", flat=True)
    )
    ReferenceTags.objects.filter(id__in=duplicate_tags).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0022_userreferencetag_deleted_tags"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="referencetags",
            constraint=models.UniqueConstraint(
                fields=("content_object", "tag"), name="reference_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="userreferencetags",
            constraint=models.UniqueConstraint(
                fields=("tag", "content_object"), name="user_reference_tags"
            ),
        ),
    ]
