# Generated by Django 4.2.3 on 2023-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0022_referencetags_reference_tag"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userreferencetags",
            constraint=models.UniqueConstraint(
                fields=("tag", "content_object"), name="user_reference_tags"
            ),
        ),
    ]
