# Generated by Django 5.1.4 on 2025-02-11 03:27

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0024_workflows"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainedVectorizer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "vectorizer",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\chansen\\dev\\hawc\\private"
                        ),
                        upload_to="trained-vectorizers/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainedModelVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "model",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\chansen\\dev\\hawc\\private"
                        ),
                        upload_to="trained-models/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trained_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="lit.trainedmodel",
                    ),
                ),
                (
                    "vectorizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trained_models",
                        to="lit.trainedvectorizer",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("trained_model", "version")},
            },
        ),
        migrations.CreateModel(
            name="ModelPredictionRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prediction_class", models.CharField(max_length=100)),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trained_models",
                        to="lit.workflow",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_runs",
                        to="lit.trainedmodelversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True, help_text="Manually approve this prediction", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_predictions",
                        to="lit.reference",
                    ),
                ),
                (
                    "prediction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_predictions",
                        to="lit.modelpredictionrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("prediction_run", "reference")},
            },
        ),
    ]
