# Generated by Django 1.11.4 on 2018-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0002_auto_20150629_1327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="HERO_access",
            field=models.BooleanField(
                default=False,
                help_text="Open HERO links using HERO Net (requires authentication), instead of public HERO (no authentication required).",
                verbose_name="Has Authenticated HERO access",
            ),
        ),
    ]
