# Generated by Django 1.11.9 on 2018-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0003_py3_unicode"),
    ]

    operations = [
        migrations.AddField(
            model_name="hawcuser",
            name="license_v1_accepted",
            field=models.BooleanField(default=False, verbose_name="Accept license"),
        ),
        migrations.AddField(
            model_name="hawcuser",
            name="license_v2_accepted",
            field=models.BooleanField(default=False, verbose_name="Accept license"),
        ),
    ]
