# Generated by Django 3.2.5 on 2021-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myuser", "0005_lowercase"),
    ]

    operations = [
        migrations.AddField(
            model_name="hawcuser",
            name="external_id",
            field=models.CharField(default="", max_length=30),
        ),
    ]
