# Generated by Django 3.2.5 on 2021-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0005_lowercase"),
    ]

    operations = [
        migrations.AddField(
            model_name="hawcuser",
            name="external_id",
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
