# Generated by Django 3.2.16 on 2023-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myuser", "0006_hawcuser_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hawcuser",
            name="backend",
            field=models.CharField(
                default="django.contrib.auth.backends.ModelBackend", max_length=64
            ),
        ),
    ]
