# Generated by Django 3.2.11 on 2022-02-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myuser", "0006_hawcuser_external_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="HERO_access", new_name="authenticated_hero",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="authenticated_hero",
            field=models.BooleanField(
                default=False,
                help_text="Use the login-required version of HERO links, instead of the public version",
                verbose_name="Authenticated HERO access",
            ),
        ),
        migrations.AddField(
            model_name="hawcuser",
            name="otp_secret",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
