# Generated by Django 5.0.1 on 2024-02-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0006_hawcuser_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hawcuser",
            name="email_verified_on",
            field=models.DateTimeField(null=True, verbose_name="Email Verified"),
        ),
    ]
