# Generated by Django 1.9.4 on 2016-06-06 16:36


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riskofbias", "0010_auto_20160518_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskofbiasdomain",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="riskofbiasscore",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
