# Generated by Django 2.2.11 on 2020-07-14 18:44

from django.db import migrations, models
import hawc.apps.riskofbias.models


class Migration(migrations.Migration):
    def update_overall_confidence(apps, schema_editor):
        score_map = {24: 34, 25: 35, 26: 36, 27: 37}
        RiskOfBiasScore = apps.get_model("riskofbias", "RiskOfBiasScore")
        for score in RiskOfBiasScore.objects.filter(
            metric__domain__is_overall_confidence=True, score__in=score_map.keys()
        ):
            score.score = score_map[score.score]
            score.save()

    dependencies = [
        ("riskofbias", "0021_riskofbiasscore_bias_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskofbiasscore",
            name="score",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Not applicable"),
                    (12, "Not reported"),
                    (14, "Definitely high risk of bias"),
                    (15, "Probably high risk of bias"),
                    (16, "Probably low risk of bias"),
                    (17, "Definitely low risk of bias"),
                    (20, "Not applicable"),
                    (22, "Not reported"),
                    (24, "Critically deficient"),
                    (25, "Deficient"),
                    (26, "Adequate"),
                    (27, "Good"),
                    (34, "Uninformative"),
                    (35, "Low confidence"),
                    (36, "Medium confidence"),
                    (37, "High confidence"),
                ],
                default=hawc.apps.riskofbias.models.build_default_rob_score,
            ),
        ),
        migrations.RunPython(update_overall_confidence),
    ]
