# Generated by Django 3.1.3 on 2021-05-14 05:10

from django.db import migrations, models


def set_default_responses(apps, schema_editor):
    RiskOfBiasMetric = apps.get_model("riskofbias", "RiskOfBiasMetric")

    RiskOfBiasMetric.objects.filter(domain__assessment__rob_settings__responses=0).update(
        responses=0
    )
    RiskOfBiasMetric.objects.filter(domain__assessment__rob_settings__responses=1).update(
        responses=1
    )

    # TODO set it for edge case assessment that needs no score choices?


class Migration(migrations.Migration):

    dependencies = [
        ("riskofbias", "0022_new_rob_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskofbiasmetric",
            name="responses",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Prime"), (1, "Epa"), (2, "None")], default=0
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_responses, reverse_code=migrations.RunPython.noop),
    ]
