# Generated by Django 3.1.3 on 2021-05-14 05:10

from django.db import migrations, models

from ..models import RiskOfBiasMetric


def set_default_responses(apps, schema_editor):
    RiskOfBiasMetric = apps.get_model("riskofbias", "RiskOfBiasMetric")

    RiskOfBiasMetric.objects.filter(domain__assessment__rob_settings__responses=0).update(
        responses=0
    )
    RiskOfBiasMetric.objects.filter(domain__assessment__rob_settings__responses=1).update(
        responses=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ("riskofbias", "0023_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskofbiasmetric",
            name="responses",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "OHAT"), (1, "EPA"), (2, "No scores")],
                default=RiskOfBiasMetric.get_default_responses,
            ),
        ),
        migrations.RunPython(set_default_responses, reverse_code=migrations.RunPython.noop),
    ]
