# Generated by Django 3.2.11 on 2022-02-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0011_auto_20190416_2035"),
        ("riskofbias", "0024_riskofbiasmetric_responses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskofbias",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="riskofbiases",
                to="study.study",
            ),
        ),
    ]
