# Generated by Django 5.2.5 on 2025-09-08 20:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("epi", "0018_django31"),
        ("study", "0012_study_eco"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peco_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PE", "PECO (supplemental)"),
                                ("NO", "No (off-PECO)"),
                                ("UN", "Uncertain of PECO relevance"),
                            ],
                            max_length=2,
                        ),
                        help_text="What is the correct PECO?",
                        size=None,
                    ),
                ),
                (
                    "peco_supplemental_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LE", "Letter to/from editor or commentary"),
                                ("CO", "Conference proceeding or abstract"),
                                ("RE", "Remediation/spill/improper disposal"),
                                ("SE", "Only secondary quantitative data"),
                                (
                                    "QU",
                                    "Only qualitative contextual information or concentrations in rocks",
                                ),
                                ("IS", "Isomer only (not applicable to asbestos)"),
                            ],
                            max_length=2,
                        ),
                        help_text="Select Type of PECO Supplemental",
                        size=None,
                    ),
                ),
                (
                    "study_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("MON", "Monitoring"),
                                ("MDI", "Modeling - dose/intake"),
                                ("MPC", "Modeling - predicted concentration"),
                                (
                                    "XWF",
                                    "Experimental  - weight fraction or concentration in consumer product",
                                ),
                                ("EXP", "Experimental"),
                                ("SUR", "Survey"),
                                ("DAT", "Database"),
                                ("COM", "Completed Assessment"),
                                ("EPI", "Epi"),
                            ],
                            max_length=3,
                        ),
                        help_text="What are the correct study types?",
                        size=None,
                    ),
                ),
                (
                    "consumer_prod_dermal_flux",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "CP",
                                    "Consumer products/articles (e.g. weight fractions or use instructions like dilution rate, application rate, application methods, amount of product per use, etc.)",
                                ),
                                (
                                    "DE",
                                    "Dermal parameters (e.g. dermal absorption fraction, neat and aqueous Kp, skin permeability coefficient, skin permeation coefficient, skin permeation, and skin absorption)",
                                ),
                                (
                                    "FL",
                                    "Fluxes (e.g. chemical fluxes in surface water with units mass per area per time)",
                                ),
                            ],
                            max_length=3,
                        ),
                        help_text="This can include either primary or secondary source information, and is likely information that is considered PECO Supplemental or contextual (i.e., would not be evaluated under any study type) unless it is primary source concentration data or survey data.",
                        size=None,
                        verbose_name="Is there data available for consumer products/articles, dermal parameters, or fluxes?",
                    ),
                ),
                (
                    "brief_description",
                    models.TextField(
                        blank=True,
                        verbose_name="Briefly describe the information present in the paper",
                    ),
                ),
                (
                    "help_requested",
                    models.BooleanField(
                        default=False,
                        verbose_name="Have you discussed this evaluation or extraction with a team lead?",
                    ),
                ),
                (
                    "help_requested_discussion_notes",
                    models.TextField(
                        blank=True,
                        verbose_name="Please list team member and brief summary of resolution.",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposure_monitoring_extractions",
                        to="study.study",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_item_type",
                    models.CharField(
                        choices=[
                            (
                                "CTE",
                                "Chemical to extract (TSCA, targeted metabolite, PAD)",
                            ),
                            (
                                "NTC",
                                "ONLY non-targeted chemical that will not be extracted (isomer, siloxane structure of D4, degradant of D4, precursor, or metabolite)",
                            ),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Reported chemical name"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=32, verbose_name="Reported chemical abbreviation"
                    ),
                ),
                (
                    "tsca_chemical_substance",
                    models.CharField(
                        choices=[
                            ("ODCB", "o-Dichlorobenzene (o-DCB or 1,2 DCB) (ODCB)"),
                            ("PDCB", "p-Dichlorobenzene (p-DCB or 1,4 DCB) (PDCB)"),
                            ("EDC", "1,2-Dichloroethane (EDC)"),
                            ("TDCE", "trans-1,2-Dichloroethylene (TDCE)"),
                            ("TCA", "1,1,2-Trichloroethane (TCA)"),
                            ("DCP", "1,2-Dichloropropane  (DCP)"),
                            ("DCE", "1,1-Dichloroethane (DCE)"),
                            (
                                "TPP",
                                "Triphenyl Phosphate (TPP) (Phosphoric acid, triphenyl ester)",
                            ),
                            ("TBBPA", "Tetrabromobisphenol A (TBBPA)"),
                            ("TCEP", "Tris(2-chloroethyl) phosphate (TCEP)"),
                            ("EDB", "Ethylene Dibromide (EDB)"),
                            ("BTD", "1,3-Butadiene (BTD)"),
                            ("PAD", "Phthalic Anhydride (PAD)"),
                            ("HHCB", "HHCB (Galaxolide)"),
                            ("FDH", "Formaldehyde (FDH)"),
                            ("DBP", "Dibutyl Phthalate (DBP)"),
                            ("BBP", "Butyl benzyl Phthalate (BBP)"),
                            ("DEHP", "Di-ethylhexyl Phthalate (DEHP)"),
                            ("DIBP", "Di-isobutyl Phthalate (DIBP)"),
                            ("DCHP", "Dicyclohexyl Phthalate (DCHP)"),
                            ("DIDP", "Di-isodecyl Phthlate (DIDP)"),
                            ("DINP", "Di-isononyl Phthlate (DINP)"),
                            ("D4", "D4"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "chemical_form",
                    models.CharField(
                        choices=[
                            ("PAR", "Parent/TSCA Chemical"),
                            ("MET", "Targeted Metabolite / Degradant (D4 or PAD)"),
                        ],
                        max_length=3,
                        verbose_name="Form of reported chemical",
                    ),
                ),
                (
                    "extraction_target",
                    models.CharField(
                        choices=[
                            (
                                "BCEP",
                                "BCEP (Bis(2-chloroethyl)phosphate) [TCEP - Human biomonitoring]",
                            ),
                            (
                                "DPHP",
                                "DPHP (Di(2-propylheptyl) phthalate) [TPP - Human biomonitoring]",
                            ),
                            (
                                "TPHP-M1",
                                "TPHP-M1 (Hydroxyphenyl phenyl phosphate) [TPP - Human biomonitoring]",
                            ),
                            (
                                "HEMA",
                                "HEMA (S-(hydroxyethyl)mercapturic acid) [EDB - Human biomonitoring]",
                            ),
                            (
                                "TDA",
                                "TDA (thiodiacetic acid) [EDB - Human biomonitoring]",
                            ),
                            (
                                "SODA",
                                "SODA (thiodiacetic acid sulfoxide) [EDB - Human biomonitoring]",
                            ),
                            ("PA", "PA (Phthalic acid) [PAD - urine]"),
                            (
                                "MEHHP",
                                "MEHHP (Mono-(2-ethyl-5-hydroxyhexyl) phthalate, (5OH-MEHP), OH-MEHP) [DEHP - urine]",
                            ),
                            (
                                "MEOHP",
                                "MEOHP (Mono-(2-ethyl-5-oxohexyl) phthalate, oxo-MEHP, (5oxo-MEHP)) [DEHP - urine]",
                            ),
                            (
                                "MEHP",
                                "MEHP (Mono-(2-ethyl)-hexyl phthalate) [DEHP - urine]",
                            ),
                            (
                                "MECPP",
                                "MECPP (Mono-(2-ethyl-5-carboxypentyl) phthalate, (5cx-MEPP), cx-MEPP) [DEHP - urine]",
                            ),
                            ("MBP", "MBP (Monobutyl phthalate) [DBP or DnBP - urine]"),
                            (
                                "MHBP",
                                "MHBP (Mono-3-hydroxy-n-butyl phthalate) [DBP or DnBP - urine]",
                            ),
                            (
                                "MnBP",
                                "MnBP (Mono-n-butyl phthalate) [DBP or DnBP - urine]",
                            ),
                            (
                                "MiNP",
                                "MiNP (Mono-isononyl phthalate, MNP) [DNP or DiNP - urine, breastmilk, maternal or infant blood]",
                            ),
                            (
                                "MCOP",
                                "MCOP (Mono-(carboxyisooctyl) phthalate, MCiOP) [DNP or DiNP - urine, breastmilk, maternal or infant blood]",
                            ),
                            (
                                "MONP",
                                "MONP (Mono-oxoisononyl phthalate, 7 oxo-MMeOp, MOiNP, 7-oxo-MiNP, oxo-MiNP) [DNP or DiNP - urine, breastmilk, maternal or infant blood]",
                            ),
                            (
                                "OH-MiNP",
                                "OH-MiNP (Mono(hydroxyisononyl) phthalate, MHiNP) [DNP or DiNP - urine, breastmilk, maternal or infant blood]",
                            ),
                            ("MiBP", "MiBP (Mono-isobutyl phthalate) [DiBP - urine]"),
                            (
                                "MHiBP",
                                "MHiBP (Mono-2-methyl-2-hydroxypropyl phthalate) [DiBP - urine]",
                            ),
                            (
                                "MCNP",
                                "MCNP (Mono-(carboxynonyl) phthalate) [DiDP - urine, breastmilk, maternal or infant blood]",
                            ),
                            (
                                "MBzP",
                                "MBzP (Mono-benzyl phthalate) [BBP or BzBP - urine]",
                            ),
                            (
                                "MCHP",
                                "MCHP (Monocyclohexyl phthalate) [DCH or DCHP - urine]",
                            ),
                        ],
                        max_length=7,
                        verbose_name="Targeted Metabolite/Degradant to Extract",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals",
                        to="expomon.extraction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=64, verbose_name="Location Label (KEY)"
                    ),
                ),
                (
                    "city_state_region",
                    models.CharField(
                        max_length=128, verbose_name='"City, State" or Region'
                    ),
                ),
                (
                    "coords_provided",
                    models.BooleanField(
                        default=False,
                        verbose_name="Are geographic coordinates (lat/longs) provided?",
                    ),
                ),
                (
                    "geographic_setting",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UR", "Urban"),
                                ("SU", "Suburban"),
                                ("RU", "Rural"),
                                ("IN", "Industrial"),
                                ("AG", "Agricultural"),
                                ("RE", "Remote"),
                                ("PO", "Port"),
                                ("MA", "Marine"),
                                ("OT", "Other"),
                                ("NR", "Not Reported/Unknown"),
                            ],
                            max_length=2,
                        ),
                        size=None,
                    ),
                ),
                (
                    "is_data_for_cohort",
                    models.BooleanField(
                        default=False, help_text="Is the data for a cohort?"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, verbose_name="Additional notes for location/cohort."
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="expomon_locations", to="epi.country"
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="expomon.extraction",
                    ),
                ),
            ],
        ),
    ]
