# Generated by Django 5.2.5 on 2025-09-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expomon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbientAirMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_label",
                    models.CharField(max_length=64, verbose_name="Media Label (KEY)"),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Additional notes"),
                ),
                (
                    "particle_size",
                    models.CharField(
                        help_text="Enter the phase (gas, particulate) if the particle size is not reported.",
                        max_length=256,
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expomon.extraction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SedimentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_label",
                    models.CharField(max_length=64, verbose_name="Media Label (KEY)"),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Additional notes"),
                ),
                (
                    "water_body_name",
                    models.CharField(
                        help_text='Examples: "Lake Erie" or "Multiple tributaries of the Mississippi River"',
                        max_length=256,
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expomon.extraction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
