# Generated by Django 5.2.5 on 2025-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expomon", "0002_ambientairmedia_sedimentmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambientairmedia",
            name="sub_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not Set"), (1, "Fake")], default=0
            ),
        ),
        migrations.AddField(
            model_name="sedimentmedia",
            name="sub_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not Set"), (1, "Fake")], default=0
            ),
        ),
    ]
