# Generated by Django 3.2.15 on 2022-10-20 20:24

from django.db import migrations, models


def updateAssessmentVersion(apps, schema_editor):
    Assessment = apps.get_model("assessment", "Assessment")
    AssessmentSettings = apps.get_model("bmd", "assessmentsettings")
    Session = apps.get_model("bmd", "session")
    ids = []
    for assessment in Assessment.objects.all():
        sessions = Session.objects.filter(endpoint__assessment=assessment).count()
        if sessions == 0:
            ids.append(assessment.id)

    AssessmentSettings.objects.filter(assessment_id__in=ids).update(version="BMDS330")


class Migration(migrations.Migration):

    dependencies = [
        ("bmd", "0007_selected_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentsettings",
            name="version",
            field=models.CharField(
                choices=[
                    ("BMDS231", "BMDS v2.3.1"),
                    ("BMDS240", "BMDS v2.4.0"),
                    ("BMDS260", "BMDS v2.6.0"),
                    ("BMDS2601", "BMDS v2.6.0.1"),
                    ("BMDS270", "BMDS v2.7.0"),
                    ("BMDS330", "BMDS v3.3.0"),
                ],
                default="BMDS330",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="version",
            field=models.CharField(
                choices=[
                    ("BMDS231", "BMDS v2.3.1"),
                    ("BMDS240", "BMDS v2.4.0"),
                    ("BMDS260", "BMDS v2.6.0"),
                    ("BMDS2601", "BMDS v2.6.0.1"),
                    ("BMDS270", "BMDS v2.7.0"),
                    ("BMDS330", "BMDS v3.3.0"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(updateAssessmentVersion, reverse_code=migrations.RunPython.noop),
    ]
