# Generated by Django 3.2.16 on 2022-11-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmd", "0009_delete_logicfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="bmrs",
            field=models.JSONField(default=dict),
        ),
        migrations.RenameField(
            model_name="session",
            old_name="bmrs",
            new_name="inputs",
        ),
        migrations.AddField(
            model_name="session",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="outputs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="errors",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="selected",
            field=models.JSONField(default=dict),
        ),
    ]
