# Generated by Django 3.2.16 on 2022-11-26 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bmd", "0009_bmd3_add_migrate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="selectedmodel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="selectedmodel",
            name="dose_units",
        ),
        migrations.RemoveField(
            model_name="selectedmodel",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="selectedmodel",
            name="model",
        ),
        migrations.DeleteModel(
            name="LogicField",
        ),
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.DeleteModel(
            name="SelectedModel",
        ),
    ]
