# Generated by Django 5.1 on 2024-11-06 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("bmd", "0010_bmd3_delete")]
    operations = [migrations.DeleteModel(name="AssessmentSettings")]
