# Generated by Django 5.1 on 2024-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bmd", "0011_delete_assessmentsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="version",
            field=models.CharField(max_length=10),
        ),
    ]
