# Generated by Django 5.1.6 on 2025-02-23 03:44

from django.db import migrations, models


def run_fwd(apps, schema_editor):
    Session = apps.get_model("bmd", "Session")
    updates = []
    for sess in Session.objects.filter(version="24.1"):
        sess.inputs = {"items": [sess.inputs]}
        sess.outputs = {"items": [sess.outputs]}
        sess.selected = {"items": [sess.selected]}
        sess.append(updates)
    if updates:
        Session.objects.bulk_update(updates, ["inputs", "outputs", "selected"])


def run_bkd(apps, schema_editor):
    Session = apps.get_model("bmd", "Session")
    updates = []
    for sess in Session.objects.filter(version="24.1"):
        sess.inputs = sess.inputs["items"][0]
        sess.outputs = sess.outputs["items"][0]
        sess.selected = sess.selected["items"][0]
        sess.append(updates)
    if updates:
        Session.objects.bulk_update(updates, ["inputs", "outputs", "selected"])


class Migration(migrations.Migration):
    dependencies = [
        ("bmd", "0012_alter_session_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="option_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(run_fwd, reverse_code=run_bkd),
    ]
