# Generated by Django 1.10.3 on 2017-05-11 15:57


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0009_assessment_enable_project_management"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporttemplate",
            name="assessment",
        ),
        migrations.DeleteModel(
            name="ReportTemplate",
        ),
    ]
