# Generated by Django 1.11.15 on 2019-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0013_py3_unicode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseendpoint",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Endpoint/Adverse outcome"),
        ),
    ]
