# Generated by Django 2.2.11 on 2020-04-02 14:57

from django.db import migrations, models


def set_public_training_data(apps, schema_editor):
    Assessment = apps.get_model("assessment", "Assessment")
    Assessment.objects.filter(public=True).update(is_public_training_data=True)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0015_flavor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_public_training_data",
            field=models.BooleanField(
                default=False,
                verbose_name="Public training data",
                help_text="Allows data to be anonymized and made available for machine learning projects. Both assessment ID and user ID will be made anonymous for these purposes.",
            ),
        ),
        migrations.RunPython(set_public_training_data),
    ]
