# -*- coding: utf-8 -*-
# Generated by Django 2.2.11 on 2020-04-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


def set_public_training_data(apps, schema_editor):
    Assessment = apps.get_model("assessment", "Assessment")
    Assessment.objects.filter(public=True).update(is_public_training_data=True)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0015_flavor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_public_training_data",
            field=models.BooleanField(
                default=False,
                help_text="Allows data to be anonymized by assessment id and user id for machine learning projects.",
            ),
        ),
        migrations.RunPython(set_public_training_data),
    ]
