# Generated by Django 2.2.15 on 2020-08-24 13:16

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("task_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "PENDING"), (2, "SUCCESS"), (3, "FAILURE"), (4, "RETRY")],
                        default=1,
                        editable=False,
                    ),
                ),
                (
                    "job",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "OTHER"), (2, "TEST")], default=2
                    ),
                ),
                ("kwargs", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("result", models.TextField(blank=True, editable=False)),
                ("exception", models.TextField(blank=True, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="assessment.Assessment",
                    ),
                ),
            ],
        ),
    ]
