# Generated by Django 2.2.11 on 2020-08-05 16:37

from django.db import migrations, models
from django.core.exceptions import ValidationError
import django.db.models.deletion
from pathlib import Path
import pandas as pd
from hawc.apps.assessment.models import DSSTox, ChemicalIdentifier


def migrate_all_casrn(apps, schema_editor):
    filepath = Path(__file__).absolute().parent.parent / "fixtures" / "Dsstox_CAS_number_name.xlsx"

    df = pd.read_excel(filepath)
    # save all assessment CASRNs as identifiers / add DSSTox details
    _migrate_assessment_casrn(apps, df)


def _migrate_assessment_casrn(apps, df):
    Assessment = apps.get_model("assessment", "assessment")

    assessments = Assessment.objects.exclude(cas="")

    imported_dtxsids = list(DSSTox.objects.all().values_list("dtxsid", flat=True))

    matching_df = df[df["casrn"].isin(assessments.values_list("cas", flat=True))]
    casrn_dtxsid_tuples = list(zip(matching_df["casrn"], matching_df["dsstox_substance_id"]))

    casrn_to_dtxsid = dict()
    dsstox_list = list()

    for casrn, dtxsid in casrn_dtxsid_tuples:
        try:
            if dtxsid in imported_dtxsids:
                casrn_to_dtxsid[casrn] = dtxsid
            else:
                dsstox = DSSTox.create_from_dtxsid(dtxsid)
                dsstox_list.append(dsstox)
                imported_dtxsids.append(dtxsid)
                casrn_to_dtxsid[casrn] = dtxsid
        except ValidationError:
            continue

    DSSTox.objects.bulk_create(dsstox_list)

    # create all identifiers and link with dsstox record
    identifier_list = [
        ChemicalIdentifier(
            identifier=assessment.cas, assessment_id=assessment.id, dsstox_id=casrn_to_dtxsid.get(assessment.cas, None)
        )
        for assessment in assessments
    ]
    ChemicalIdentifier.objects.bulk_create(identifier_list)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSSTox",
            fields=[
                ("dtxsid", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalIdentifier",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(blank=True, default=None, max_length=80, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.Assessment",
                    ),
                ),
                (
                    "dsstox",
                    models.ForeignKey(
                        blank=True,
                        db_column="dtxsid",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.DSSTox",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_all_casrn, reverse_code=migrations.RunPython.noop),
    ]
