# Generated by Django 2.2.15 on 2020-08-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0019_log_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(name="baseendpoint", options={"ordering": ("id",)},),
    ]
