# Generated by Django 3.1.3 on 2021-02-24 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessment", "0024_django31"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
