# Generated by Django 3.2.5 on 2021-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0027_content_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="log", name="content", field=models.JSONField(default=dict),
        ),
    ]
