# Generated by Django 3.2.8 on 2021-11-02 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_communication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='updated',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
