# Generated by Django 3.2.10 on 2022-01-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0028_assessment_models'),
        ('assessment', '0029_communication'),
    ]

    operations = [
    ]
