# Generated by Django 3.2.10 on 2022-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0029_communication"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="epi_version",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
