# Generated by Django 3.2.10 on 2022-01-03 20:11

from django.db import migrations, models


def set_epi_version(apps, schema_editor):
    # set epi_version to 1 on existing assessments
    Assessment = apps.get_model("assessment", "Assessment")
    db_alias = schema_editor.connection.alias
    Assessment.objects.using(db_alias).update(epi_version=1)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0029_communication"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="epi_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.RunPython(set_epi_version),
    ]
