# Generated by Django 3.2.11 on 2022-01-21 17:56

from django.db import migrations, models


# def set_released_on(apps, schema_editor):
#     Assessment = apps.get_model("assessment", "assessment")


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0030_assessment_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="released_on",
            field=models.DateTimeField(
                help_text="The date this assessment was released to be viewed by the general public.",
                null=True,
            ),
        ),
        # migrations.RunPython(set_released_on, migrations.RunPython.noop),
    ]
