# Generated by Django 3.2.11 on 2022-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0032_assessment_epi_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="public_on",
            field=models.DateTimeField(
                blank=True,
                help_text="The assessment can be viewed by the general public.",
                null=True,
                verbose_name="Public",
            ),
        ),
    ]
