# Generated by Django 3.2.16 on 2023-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0032_assessment_epi_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="This field is for capturing information about assessments (e.g., STICS numbers) that is only visible and accessible to HAWC Admins",
            ),
        ),
    ]
