# Generated by Django 3.2.12 on 2022-08-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_assessment_epi_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_system', models.CharField(help_text='Identify the organ system of concern (e.g., Hepatic, Nervous, Reproductive).', max_length=128)),
                ('evaluation_type', models.CharField(choices=[('CANCER', 'Cancer'), ('NONCANCER', 'Noncancer'), ('BOTH', 'Cancer and Noncancer')], default='CANCER', help_text='Select the type of chemical evaluation that was conducted.', max_length=32)),
                ('value_type', models.CharField(choices=[('SCREEN_RFD', 'Screening-Level RfD'), ('SCREEN_RFC', 'Screening-Level RfC'), ('ORGAN_RFD', 'Organ-Specific RfD'), ('ORGAN_RFC', 'Organ-Specific RfC'), ('OVERALL_RFD', 'Overall RfD'), ('OVERALL_RFC', 'Overall RfC'), ('IUR', 'IUR'), ('OSF', 'OSF'), ('NONE', 'No Value')], default='NONE', help_text='Select the type of toxicity value that was derived.', max_length=32)),
                ('value', models.FloatField(null=True)),
                ('value_unit', models.CharField(blank=True, max_length=64)),
                ('basis', models.TextField(blank=True, help_text='Describe the justification for deriving this value. Information should include the endpoint of concern from the principal study (e.g., decreased embryo/fetal survival) with the appropriate references included (Shams et al, 2022).')),
                ('pod_value', models.FloatField(null=True)),
                ('pod_unit', models.CharField(blank=True, max_length=64)),
                ('uncertainty', models.FloatField(null=True, verbose_name='Composite Uncertainty Factor')),
                ('confidence', models.TextField(blank=True, choices=[('HI', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], help_text='Select the overall study level confidence.')),
                ('species_studied', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, help_text='Describe the duration of the study selected to support the derivation of the toxicity value.', max_length=64)),
                ('tumor_type', models.CharField(blank=True, help_text='Describe the specific types of cancer found within the specific organ system (e.g., tumor site).', max_length=64, verbose_name='Tumor Type/Cancer')),
                ('extrapolation_method', models.CharField(blank=True, help_text='Describe the statistical method(s) used to derive the cancer toxicity values (e.g., Time-to-tumor dose-response model with linear extrapolation from the POD (BMDL10(HED)) associated with 10% extra cancer risk).', max_length=512)),
                ('evidence', models.CharField(blank=True, help_text='If applicable, describe the overall characterization of the evidence (e.g., cancer or noncancer descriptors) and the basis for this determination (e.g., based on strong and consistent evidence in animals and humans).', max_length=512, verbose_name='Evidence Characterization')),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assessment.assessment')),
            ],
            options={
                'verbose_name_plural': 'values',
            },
        ),
        migrations.CreateModel(
            name='AssessmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('IRIS', 'IRIS'), ('PPRTV', 'PPRTV'), ('TSCA', 'TSCA'), ('RE', 'RE'), ('OW HESD', 'OW HESD'), ('Other', 'Other')], default='Other', help_text='Name the product line relevant to this chemical evaluation.', max_length=64)),
                ('chemical_name', models.CharField(max_length=128)),
                ('cas', models.CharField(max_length=128, verbose_name='CAS No.')),
                ('milestone', models.CharField(blank=True, choices=[('Scoping', 'Scoping'), ('Problem Formulation', 'Problem Form'), ('Internal Review', 'Internal R'), ('Interagency Review', 'Interagency R'), ('Public Comment', 'Public Comment'), ('External Peer Review', 'External Pr'), ('Final', 'Final')], help_text='If relevant, insert high-level project management milestones for this assessment.', max_length=64, verbose_name='Milestone Fields/History Field')),
                ('pr_type', models.CharField(choices=[('CL', 'Contract-Led'), ('FACA', 'FACA Panel'), ('NASEM', 'NASEM'), ('JR', 'Journal Review'), ('NONE', 'No Review')], default='NONE', help_text='Define the method by which this assessment was externally reviewed.', max_length=64, verbose_name='Peer Review Type')),
                ('epa_report', models.IntegerField(null=True, verbose_name='EPA Report Number')),
                ('rapid_stics', models.IntegerField(null=True, verbose_name='RAPID/STICS Number')),
                ('file_link', models.URLField(blank=True, verbose_name='Link to File Assessments')),
                ('hero_link', models.URLField(blank=True, verbose_name='Link to HERO Project Page')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='assessment.assessment')),
            ],
        ),
    ]
