# Generated by Django 3.2.11 on 2022-01-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_rename_released_on_assessment_public_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='public',
        ),
    ]
