# Generated by Django 3.2.15 on 2022-08-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0011_auto_20190416_2035"),
        ("assessment", "0032_assessment_epi_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Values",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="Identify the organ system of concern (e.g., Hepatic, Nervous, Reproductive).",
                        max_length=128,
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("CANCER", "Cancer"),
                            ("NONCANCER", "Noncancer"),
                            ("BOTH", "Cancer and Noncancer"),
                        ],
                        default="CANCER",
                        help_text="Select the type of chemical evaluation that was conducted.",
                        max_length=32,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        help_text="Enter the type of toxicity value that was derived.",
                        max_length=64,
                    ),
                ),
                ("value", models.FloatField(null=True)),
                (
                    "basis",
                    models.TextField(
                        blank=True,
                        help_text="Describe the justification for deriving this value. Information should include the endpoint of concern from the principal study (e.g., decreased embryo/fetal survival) with the appropriate references included (Shams et al, 2022).",
                    ),
                ),
                ("pod_value", models.FloatField(null=True, verbose_name="POD Value")),
                (
                    "uncertainty",
                    models.FloatField(null=True, verbose_name="Composite Uncertainty Factor"),
                ),
                (
                    "confidence",
                    models.TextField(
                        blank=True,
                        choices=[("HI", "High"), ("MED", "Medium"), ("LOW", "Low")],
                        help_text="Select the overall study level confidence.",
                    ),
                ),
                ("species_studied", models.CharField(blank=True, max_length=64)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Describe the duration of the study selected to support the derivation of the toxicity value.",
                        max_length=64,
                    ),
                ),
                (
                    "tumor_type",
                    models.CharField(
                        blank=True,
                        help_text="Describe the specific types of cancer found within the specific organ system (e.g., tumor site).",
                        max_length=64,
                        verbose_name="Tumor Type/Cancer",
                    ),
                ),
                (
                    "extrapolation_method",
                    models.CharField(
                        blank=True,
                        help_text="Describe the statistical method(s) used to derive the cancer toxicity values (e.g., Time-to-tumor dose-response model with linear extrapolation from the POD (BMDL10(HED)) associated with 10% extra cancer risk).",
                        max_length=512,
                    ),
                ),
                (
                    "evidence",
                    models.CharField(
                        blank=True,
                        help_text="If applicable, describe the overall characterization of the evidence (e.g., cancer or noncancer descriptors) and the basis for this determination (e.g., based on strong and consistent evidence in animals and humans).",
                        max_length=512,
                        verbose_name="Evidence Characterization",
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("extra_metadata", models.JSONField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "pod_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="values_set_pod",
                        to="assessment.doseunits",
                        verbose_name="POD Unit",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="study.study",
                        verbose_name="HAWC Study",
                    ),
                ),
                (
                    "value_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessment.doseunits",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "values",
            },
        ),
        migrations.CreateModel(
            name="AssessmentDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        help_text="Name the product line relevant to this chemical evaluation.",
                        max_length=64,
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Scoping", "Scoping"),
                            ("Problem Formulation", "Problem Form"),
                            ("Internal Review", "Internal R"),
                            ("Interagency Review", "Interagency R"),
                            ("Public Comment", "Public Comment"),
                            ("External Peer Review", "External Pr"),
                            ("Final", "Final"),
                        ],
                        help_text="If relevant, insert high-level project management milestones for this assessment.",
                        max_length=64,
                    ),
                ),
                (
                    "pr_status",
                    models.CharField(
                        choices=[
                            ("CL", "Contract-Led"),
                            ("FACA", "FACA Panel"),
                            ("NASEM", "NASEM"),
                            ("JR", "Journal Review"),
                            ("NONE", "No Review"),
                        ],
                        default="NONE",
                        help_text="Define the method by which this assessment was externally reviewed.",
                        max_length=64,
                        verbose_name="Peer Review Status",
                    ),
                ),
                (
                    "report_number",
                    models.IntegerField(blank=True, help_text="eg., EPA report number", null=True),
                ),
                (
                    "qa_id",
                    models.IntegerField(blank=True, null=True, verbose_name="QA Tracking ID"),
                ),
                ("qa_link", models.URLField(blank=True, verbose_name="Link to QA Tracking Page")),
                (
                    "docs_link",
                    models.URLField(blank=True, verbose_name="Link to External Document Page"),
                ),
                (
                    "project_link",
                    models.URLField(
                        blank=True,
                        help_text="eg., HERO Project page",
                        verbose_name="Link to External Page",
                    ),
                ),
                ("extra_metadata", models.JSONField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="assessment.assessment",
                    ),
                ),
            ],
        ),
    ]
