# Generated by Django 3.2.15 on 2022-09-27 21:48

import django.db.models.deletion
from django.db import migrations, models

import hawc.apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0012_study_eco"),
        ("assessment", "0032_assessment_epi_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="Identify the health system of concern (e.g., Hepatic, Nervous, Reproductive).",
                        max_length=128,
                    ),
                ),
                (
                    "evaluation_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Cancer"), (1, "Noncancer"), (2, "Cancer and Noncancer")],
                        default=0,
                        help_text="Substance evaluation conducted.",
                    ),
                ),
                (
                    "value_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Screening-Level RfD"),
                            (5, "Screening-Level RfC"),
                            (10, "Organ-Specific RfD"),
                            (15, "Organ-Specific RfC"),
                            (20, "Overall RfD"),
                            (25, "Overall RfC"),
                            (30, "IUR"),
                            (35, "OSF"),
                            (40, "No Value"),
                            (45, "Other"),
                        ],
                        help_text="Type of derived value.",
                    ),
                ),
                ("value", models.FloatField(blank=True, help_text="The derived value")),
                (
                    "basis",
                    models.TextField(
                        blank=True,
                        help_text="Describe the justification for deriving this value. Information should include the endpoint of concern from the principal study (e.g., decreased embryo/fetal survival) with the appropriate references included (Shams et al, 2022).",
                    ),
                ),
                (
                    "pod_value",
                    models.FloatField(
                        blank=True,
                        help_text="Describe the Point of Departure (POD) for the final value",
                        null=True,
                        verbose_name="POD Value",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Describe the duration of the study selected to support the derivation of the value.",
                        max_length=128,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        choices=[(30, "High"), (20, "Medium"), (10, "Low"), (0, "Not Applicable")],
                        default=0,
                        help_text="Overall study level confidence for study or key studies.",
                    ),
                ),
                (
                    "uncertainty",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Composite Uncertainty Factor"
                    ),
                ),
                (
                    "tumor_type",
                    models.CharField(
                        blank=True,
                        help_text="Describe the specific types of cancer found within the specific organ system (e.g., tumor site).",
                        max_length=64,
                        verbose_name="Tumor/Cancer Type",
                    ),
                ),
                (
                    "extrapolation_method",
                    models.TextField(
                        blank=True,
                        help_text="Describe the statistical method(s) used to derive the cancer toxicity values (e.g., Time-to-tumor dose-response model with linear extrapolation from the POD (BMDL10(HED)) associated with 10% extra cancer risk).",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Describe the overall characterization of the evidence (e.g., cancer or noncancer descriptors) and the basis for this determination (e.g., based on strong and consistent evidence in animals and humans).",
                        verbose_name="Evidence Characterization",
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Any additional custom attributes; A <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON">JSON</a> object where keys are strings and values are strings or numbers. For example, <code>{"My Custom Field Name": "The Custom Value", "Extra ID": 12345}</code>.',
                        validators=[hawc.apps.common.validators.FlatJSON.validate],
                        verbose_name="Additional attributes",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "pod_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Units for the Point of Departure (POD)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_pods",
                        to="assessment.doseunits",
                        verbose_name="POD Unit",
                    ),
                ),
                (
                    "species_studied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessment.species",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="study.study",
                        verbose_name="Corresponding study as entered in HAWC, if available.",
                    ),
                ),
                (
                    "value_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_values",
                        to="assessment.doseunits",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "values",
            },
        ),
        migrations.CreateModel(
            name="AssessmentDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        help_text="If part of a product line, the name of the project type",
                        max_length=64,
                    ),
                ),
                (
                    "project_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Scoping"),
                            (5, "Problem Formulation"),
                            (10, "Internal Review"),
                            (15, "Interagency Review"),
                            (20, "Public Comment"),
                            (25, "External Peer Review"),
                            (30, "Final"),
                            (35, "Other"),
                        ],
                        help_text="High-level project management milestones for this assessment",
                    ),
                ),
                (
                    "project_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to an external project page, if one exists",
                        validators=[hawc.apps.common.validators.validate_hyperlink],
                        verbose_name="External Project URL",
                    ),
                ),
                (
                    "peer_review_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Contract-Led"),
                            (5, "FACA Panel"),
                            (10, "NASEM"),
                            (15, "Journal Review"),
                            (20, "No Review"),
                        ],
                        default=20,
                        help_text="Define the current status of peer review of this assessment, if any",
                        verbose_name="Peer Review Status",
                    ),
                ),
                (
                    "qa_id",
                    models.CharField(
                        blank=True,
                        help_text="Quality Assurance (QA) tracking identifier, if one exists.",
                        max_length=16,
                        verbose_name="Quality Assurance (QA) tracking identifier",
                    ),
                ),
                (
                    "qa_url",
                    models.URLField(
                        blank=True,
                        help_text="Quality Assurance Website, if any",
                        validators=[hawc.apps.common.validators.validate_hyperlink],
                        verbose_name="Quality Assurance (QA) URL",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        blank=True,
                        help_text="A external report number or identifier, if any",
                        max_length=16,
                        verbose_name="Report identifier",
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to the final document or publication, if one exists",
                        validators=[hawc.apps.common.validators.validate_hyperlink],
                        verbose_name="External Document URL",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Any additional custom attributes; A <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON">JSON</a> object where keys are strings and values are strings or numbers. For example, <code>{"My Custom Field Name": "The Custom Value", "Extra ID": 12345}</code>.',
                        validators=[hawc.apps.common.validators.FlatJSON.validate],
                        verbose_name="Additional attributes",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="assessment.assessment",
                    ),
                ),
            ],
        ),
    ]
