# Generated by Django 3.2.14 on 2022-08-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0033_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='published',
        ),
    ]
