# Generated by Django 3.2.15 on 2022-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0033_assessmentdetails_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentdetails",
            name="project_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Scoping", "Scoping"),
                    ("Problem Formulation", "Problem Formulation"),
                    ("Internal Review", "Internal Review"),
                    ("Interagency Review", "Interagency Review"),
                    ("Public Comment", "Public Comment"),
                    ("External Peer Review", "External Peer Review"),
                    ("Final", "Final"),
                ],
                help_text="If relevant, insert high-level project management milestones for this assessment.",
                max_length=64,
            ),
        ),
    ]
