# Generated by Django 3.2.14 on 2022-08-17 14:49

from django.db import migrations, models

import hawc.apps.assessment.constants


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0033_assessmentdetails_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentdetails",
            name="extra_metadata",
            field=models.JSONField(default=hawc.apps.assessment.constants.default_metadata),
        ),
        migrations.AlterField(
            model_name="values",
            name="extra_metadata",
            field=models.JSONField(
                blank=True, default=hawc.apps.assessment.constants.default_metadata
            ),
        ),
    ]
