# Generated by Django 3.2.15 on 2022-08-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20190416_2035'),
        ('assessment', '0033_assessmentdetails_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_values', to='study.study', verbose_name='HAWC Study'),
        ),
        migrations.AlterField(
            model_name='assessmentdetails',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='assessment.assessment'),
        ),
    ]
