# Generated by Django 3.2.14 on 2022-08-17 16:13

from django.db import migrations, models
import hawc.apps.assessment.constants


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0034_auto_20220817_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentdetails",
            name="extra_metadata",
            field=models.JSONField(
                blank=True, default=hawc.apps.assessment.constants.default_metadata
            ),
        ),
    ]
