# Generated by Django 3.2.15 on 2022-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_auto_20220812_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdetails',
            name='epa_report',
            field=models.IntegerField(blank=True, null=True, verbose_name='EPA Report Number'),
        ),
        migrations.AlterField(
            model_name='assessmentdetails',
            name='rapid_stics',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAPID/STICS Number'),
        ),
    ]
