# Generated by Django 3.2.15 on 2022-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0034_alter_assessmentdetails_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="values",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
