# Generated by Django 3.2.15 on 2022-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0035_alter_assessmentdetails_extra_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="values",
            name="pod_value",
            field=models.FloatField(blank=True, null=True, verbose_name="POD Value"),
        ),
        migrations.AlterField(
            model_name="values",
            name="uncertainty",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Composite Uncertainty Factor"
            ),
        ),
    ]
