# Generated by Django 3.2.15 on 2022-08-16 18:37

from django.db import migrations, models
import hawc.apps.assessment.constants


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_auto_20220815_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='extra_metadata',
            field=models.JSONField(blank=True, default=hawc.apps.assessment.constants.default_metadata, null=True),
        ),
    ]
