# Generated by Django 4.2.3 on 2023-07-14 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0036_assessment_enable_downloads_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
