# Generated by Django 3.2.15 on 2022-08-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_auto_20220822_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCharacterization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtrapolationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TumorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='values',
            name='species_studied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.species'),
        ),
        migrations.RemoveField(
            model_name='values',
            name='system',
        ),
        migrations.AlterField(
            model_name='assessmentdetails',
            name='project_type',
            field=models.ForeignKey(help_text='Name the product line relevant to this chemical evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.projecttype'),
        ),
        migrations.AlterField(
            model_name='values',
            name='duration',
            field=models.ForeignKey(blank=True, help_text='Describe the duration of the study selected to support the derivation of the toxicity value.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.duration'),
        ),
        migrations.AlterField(
            model_name='values',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text='If applicable, describe the overall characterization of the evidence (e.g., cancer or noncancer descriptors) and the basis for this determination (e.g., based on strong and consistent evidence in animals and humans).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.evidencecharacterization', verbose_name='Evidence Characterization'),
        ),
        migrations.AlterField(
            model_name='values',
            name='extrapolation_method',
            field=models.ForeignKey(blank=True, help_text='Describe the statistical method(s) used to derive the cancer toxicity values (e.g., Time-to-tumor dose-response model with linear extrapolation from the POD (BMDL10(HED)) associated with 10% extra cancer risk).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.extrapolationmethod'),
        ),
        migrations.AddField(
            model_name='values',
            name='system',
            field=models.ManyToManyField(help_text='Identify the organ system of concern (e.g., Hepatic, Nervous, Reproductive).', to='assessment.System'),
        ),
        migrations.AlterField(
            model_name='values',
            name='tumor_type',
            field=models.ForeignKey(blank=True, help_text='Describe the specific types of cancer found within the specific organ system (e.g., tumor site).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.tumortype', verbose_name='Tumor Type/Cancer'),
        ),
    ]
