# Generated by Django 3.2.15 on 2022-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_auto_20220822_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdetails',
            name='project_type',
            field=models.CharField(default='', help_text='Name the product line relevant to this chemical evaluation.', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='values',
            name='duration',
            field=models.CharField(blank=True, help_text='Describe the duration of the study selected to support the derivation of the toxicity value.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='evidence',
            field=models.TextField(blank=True, default='', help_text='If applicable, describe the overall characterization of the evidence (e.g., cancer or noncancer descriptors) and the basis for this determination (e.g., based on strong and consistent evidence in animals and humans).', verbose_name='Evidence Characterization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='values',
            name='extrapolation_method',
            field=models.TextField(blank=True, default='', help_text='Describe the statistical method(s) used to derive the cancer toxicity values (e.g., Time-to-tumor dose-response model with linear extrapolation from the POD (BMDL10(HED)) associated with 10% extra cancer risk).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='values',
            name='tumor_type',
            field=models.CharField(blank=True, default='', help_text='Describe the specific types of cancer found within the specific organ system (e.g., tumor site).', max_length=64, verbose_name='Tumor Type/Cancer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='EvidenceCharacterization',
        ),
        migrations.DeleteModel(
            name='ExtrapolationMethod',
        ),
        migrations.DeleteModel(
            name='TumorType',
        ),
    ]
