# Generated by Django 5.0.6 on 2024-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0037_delete_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentdetail",
            name="qa_id",
            field=models.CharField(
                blank=True,
                help_text="Quality Assurance (QA) tracking identifier, if one exists.",
                max_length=32,
                verbose_name="Quality Assurance (QA) tracking identifier",
            ),
        ),
    ]
