# Generated by Django 5.0.6 on 2024-06-17 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
        ("assessment", "0038_assessment_animal_version"),
    ]

    operations = []
