# Generated by Django 5.0.7 on 2024-08-20 03:08

import django.db.models.deletion
from django.db import migrations, models

import hawc.apps.common.models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", hawc.apps.common.models.ColorField(default="#0071bc")),
                ("published", models.BooleanField(default=False)),
                ("text_color", hawc.apps.common.models.ColorField(default="#000000")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="assessment.assessment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(hawc.apps.common.models.AssessmentRootMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LabeledItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assessment.label",
                    ),
                ),
            ],
        ),
    ]
