# Generated by Django 5.1 on 2024-08-21 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="enable_summary_text",
        ),
    ]
