# Generated by Django 5.0.6 on 2024-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="vocabulary",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "EPA Environmental health vocabulary"), (2, "ToxRef vocabulary")],
                default=1,
                help_text="Attempt to use a controlled vocabulary for entering bioassay data into HAWC.\n        You still have the option to enter terms which are not available in the vocabulary.",
                null=True,
                verbose_name="Controlled vocabulary",
            ),
        ),
    ]
