# Generated by Django 3.2.15 on 2022-08-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0038_auto_20220823_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
