# Generated by Django 5.1 on 2024-09-04 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0039_label_labeleditem_label_label_name"),
        ("assessment", "0039_remove_assessment_enable_summary_text"),
    ]

    operations = []
