# Generated by Django 3.2.15 on 2022-08-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_delete_projecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='system',
        ),
        migrations.AddField(
            model_name='values',
            name='system',
            field=models.CharField(default='', help_text='Identify the organ system of concern (e.g., Hepatic, Nervous, Reproductive).', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
