# Generated by Django 4.2.4 on 2023-10-20 21:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0039_remove_assessment_enable_summary_text"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dsstox",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("dtxsid", "content", config="english"),
                name="dsstox_search_idx",
            ),
        ),
    ]
