# Generated by Django 5.1 on 2024-09-04 02:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0039_remove_assessment_enable_summary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsstox",
            name="search",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "dtxsid", "content__preferredName", "content__casrn", config="english"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="dsstox",
            index=django.contrib.postgres.indexes.GinIndex(
                models.F("search"), name="dsstox_search_idx"
            ),
        ),
    ]
