# Generated by Django 3.2.15 on 2022-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0040_auto_20220825_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='value_type',
            field=models.CharField(choices=[('Screening-Level RfD', 'Screening-Level RfD'), ('Screening-Level RfC', 'Screening-Level RfC'), ('Organ-Specific RfD', 'Organ-Specific RfD'), ('Organ-Specific RfC', 'Organ-Specific RfC'), ('Overall RfD', 'Overall RfD'), ('Overall RfC', 'Overall RfC'), ('IUR', 'IUR'), ('OSF', 'OSF'), ('No Value', 'No Value'), ('Other', 'Other')], help_text='Enter the type of toxicity value that was derived.', max_length=64),
        ),
    ]
