# Generated by Django 5.1 on 2024-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0040_dsstox_search_dsstox_dsstox_search_idx"),
        ("study", "0012_study_eco"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentvalue",
            name="studies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to Key Study or Studies in HAWC. If it does not exist, leave blank and explain in comments",
                related_name="assessment_values",
                to="study.study",
                verbose_name="Key studies",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentvalue",
            name="pod_value",
            field=models.FloatField(
                blank=True,
                help_text="The Point of Departure (POD) (e.g., 2.1E-06)",
                null=True,
                verbose_name="POD Value",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentvalue",
            name="value",
            field=models.FloatField(help_text="The derived value (e.g., 2.1E-09)"),
        ),
    ]
