# Generated by Django 5.1 on 2024-09-04 18:41

from django.db import migrations


def study_to_studies(apps, schema_editor):
    """Copies existing data in AssessmentValue.study to new field with M2M relationship."""
    AssessmentValue = apps.get_model("hawc.apps.assessment", "AssessmentValue")
    for value in AssessmentValue.objects.all():
        value.studies.add(value.study)


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0041_assessmentvalue_studies_and_more"),
    ]

    operations = [migrations.RunPython(study_to_studies)]
