# Generated by Django 5.1 on 2024-09-04 18:41

from django.db import migrations


def study_to_studies(apps, schema_editor):
    """Copies existing data in AssessmentValue.study to new field with M2M relationship."""
    AssessmentValue = apps.get_model("assessment", "AssessmentValue")
    for value in AssessmentValue.objects.all():
        if value.study:
            value.studies.add(value.study)
            value.save()


def studies_to_study(apps, schema_editor):
    """Copies existing data in AssessmentValue.studies to study field when reversing."""
    AssessmentValue = apps.get_model("assessment", "AssessmentValue")
    for value in AssessmentValue.objects.all():
        study = value.studies.first()
        if study:
            value.study = value.studies.first()
            value.save()


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0042_assessmentvalue_studies_and_more"),
    ]

    operations = [migrations.RunPython(study_to_studies, studies_to_study)]
