# Generated by Django 5.1 on 2024-09-04 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0043_migrate_assessment_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentvalue",
            name="study",
        ),
    ]
