# Generated by Django 5.1.1 on 2024-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0044_remove_assessmentvalue_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentvalue",
            name="adaf",
            field=models.BooleanField(
                default=False,
                help_text="When checked, the ADAF note will appear as a footnote for the value. Add supporting information about ADAF in the comments.",
                verbose_name="ADAF has been applied?",
            ),
        ),
    ]
