# Generated by Django 5.1.1 on 2024-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0046_assessmentvalue_value_type_qualifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="enable_observations",
            field=models.BooleanField(
                default=True,
                help_text="Observations can be used to identify negative effects in animal bioassay studies. The project must use the Toxicity Reference Database Vocabulary to use Observations.",
            ),
        ),
    ]
