# Generated by Django 5.1 on 2024-11-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0046_assessmentvalue_value_type_qualifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="vocabulary",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "EHV"), (2, "ToxRefDB")],
                default=1,
                help_text="Attempt to use a controlled vocabulary for entering bioassay data into HAWC.\n        You still have the option to enter terms which are not available in the vocabulary.",
                null=True,
                verbose_name="Controlled vocabulary",
            ),
        ),
    ]
