# Generated by Django 5.1 on 2024-12-09 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0046_assessmentvalue_value_type_qualifier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labeleditem",
            options={"ordering": ("content_type", "object_id", "label__path")},
        ),
    ]
