# Generated by Django 5.2.9 on 2025-12-29 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0047_alter_labeleditem_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
