# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20170806_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawcuser',
            name='epa_sso_uid',
            field=models.CharField(blank=True, help_text="The user's User ID from the EPA's Single-Sign-On System", max_length=254, verbose_name='EPA single-sign-on User ID'),
        ),
    ]
