import re

import pandas as pd


def parse_request_logs(logs: str) -> pd.DataFrame:
    """Parse logs generated by `hawc.apps.common.middleware.RequestLogMiddleware`.

    Example input text string:
    INFO 2021-08-26 19:51:02,705 hawc.request GET /assessment/public/ 200 4887 ip-127.0.0.1 user-0 assess-0

    Args:
        logs (str): A string of logs

    Returns:
        pd.DataFrame: A pandas dataframe
    """
    regex = re.compile(
        r"(\w+) (.*) hawc\.request (\w+) (.*) (\d+) (\d+) ip-(.*) user-(\d+) assess-(\d+)"
    )
    data = [list(*regex.findall(line)) for line in logs.strip().splitlines()]
    cols = "message timestamp verb path status_code content_length ip user_id assessment_id".split()
    df = pd.DataFrame(data=data, columns=cols)
    # Convert numeric columns explicitly instead of using errors='ignore'
    for col in ["status_code", "content_length", "user_id", "assessment_id"]:
        try:
            df[col] = pd.to_numeric(df[col])
        except (ValueError, TypeError):
            pass
    df = df.assign(timestamp=pd.to_datetime(df.timestamp))
    return df
