# Generated by Django 3.1.6 on 2021-03-05 04:11

import json
from django.db import migrations



def add_filter(apps, schema_editor):
    changed = []
    for visual in apps.get_model("summary", "Visual").objects.filter(visual_type=6):
        try:
            settings = json.loads(visual.settings)
        except json.JSONDecodeError:
            continue

        settings["filters"] = []
        settings["filtersLogic"] = "and"

        visual.settings = json.dumps(settings)
        visual.save()
        changed.append(visual.id)
    print(f"Visuals changed: {changed}")


def remove_filter(apps, schema_editor):
    changed = []
    for visual in apps.get_model("summary", "Visual").objects.filter(visual_type=6):
        try:
            settings = json.loads(visual.settings)
        except json.JSONDecodeError:
            continue

        settings.pop("filters", None)
        visual.settings = json.dumps(settings)
        visual.save()
        changed.append(visual.id)
    print(f"Visuals changed: {changed}")


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0028_summarytable'),
    ]

    operations = [
        migrations.RunPython(add_filter, reverse_code=remove_filter),
    ]
