# Generated by Django 3.1.6 on 2021-03-23 21:18

from django.db import migrations


def change_ept_settings(apps, schema_editor):
    SummaryTable = apps.get_model("summary", "SummaryTable")
    updates = []

    for table in SummaryTable.objects.filter(table_type=1):
        table.content["exposed_human"]["hide_content"] = False
        table.content["exposed_human"]["no_content_text"] = "No data available"
        table.content["animal"]["hide_content"] = False
        table.content["animal"]["no_content_text"] = "No data available"
        table.content["mechanistic"]["hide_content"] = False
        table.content["mechanistic"]["no_content_text"] = "No data available"
        table.content["summary_judgement"]["hide_content"] = False
        updates.append(table)

    SummaryTable.objects.bulk_update(updates, ["content"])


def unchange_ept_settings(apps, schema_editor):
    SummaryTable = apps.get_model("summary", "SummaryTable")
    updates = []

    for table in SummaryTable.objects.filter(table_type=1):
        table.content["exposed_human"].pop("hide_content")
        table.content["exposed_human"].pop("no_content_text")
        table.content["animal"].pop("hide_content")
        table.content["animal"].pop("no_content_text")
        table.content["mechanistic"].pop("hide_content")
        table.content["mechanistic"].pop("no_content_text")
        table.content["summary_judgement"].pop("hide_content")
        updates.append(table)

    SummaryTable.objects.bulk_update(updates, ["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0029_tagtree_size"),
    ]

    operations = [
        migrations.RunPython(change_ept_settings, reverse_code=unchange_ept_settings),
    ]
