# Generated by Django 4.2.3 on 2023-08-21 03:49
import json

from django.db import migrations

from hawc.apps.assessment.constants import EpiVersion
from hawc.apps.summary import constants


def published_only_prefilters(apps, schema_editor):
    # add published_only field to prefilters
    DataPivotQuery = apps.get_model("summary", "DataPivotQuery")
    objs = DataPivotQuery.objects.all().select_related("assessment")
    for obj in objs:
        prefilters = json.loads(obj.prefilters)
        epi_version = obj.assessment.epi_version

        if obj.evidence_type == constants.StudyType.BIOASSAY:
            prefilters["animal_group__experiment__study__published"] = obj.published_only
        elif obj.evidence_type == constants.StudyType.EPI and epi_version == EpiVersion.V1:
            prefilters["study_population__study__published"] = obj.published_only
        elif obj.evidence_type == constants.StudyType.EPI and epi_version == EpiVersion.V2:
            prefilters["design__study__published"] = obj.published_only
        elif obj.evidence_type == constants.StudyType.EPI_META:
            prefilters["protocol__study__published"] = obj.published_only
        elif obj.evidence_type == constants.StudyType.IN_VITRO:
            prefilters["experiment__study__published"] = obj.published_only
        elif obj.evidence_type == constants.StudyType.ECO:
            prefilters["design__study__published"] = obj.published_only

        obj.prefilters = json.dumps(prefilters)
    DataPivotQuery.objects.bulk_update(objs, ["prefilters"])


def reverse_published_only_prefilters(apps, schema_editor):
    # TODO
    return


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0042_summarytable_interactive"),
    ]

    operations = [
        migrations.RunPython(
            published_only_prefilters, reverse_code=reverse_published_only_prefilters
        ),
        migrations.RemoveField(
            model_name="datapivotquery",
            name="published_only",
        ),
    ]
