# Generated by Django 4.2.3 on 2023-08-21 03:49
import json

from django.db import migrations, models



def prefilters_dict(apps, schema_editor):
    # load prefilters textfield into temp jsonfield
    DataPivotQuery = apps.get_model("summary", "DataPivotQuery")
    objs = DataPivotQuery.objects.all()
    for obj in objs:
        obj.temp = json.loads(obj.prefilters)
    DataPivotQuery.objects.bulk_update(objs,["temp"])


def reverse_prefilters_dict(apps, schema_editor):
    # dump temp jsonfield into prefilters textfield
    DataPivotQuery = apps.get_model("summary", "DataPivotQuery")
    objs = DataPivotQuery.objects.all()
    for obj in objs:
        obj.prefilters = json.dumps(obj.temp)
    DataPivotQuery.objects.bulk_update(objs,["prefilters"])

class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0043_new"),
    ]

    operations = [
        # change prefilters textfield into jsonfield
        migrations.AddField(
            model_name="datapivotquery",
            name="temp",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(prefilters_dict, reverse_code=reverse_prefilters_dict),
        migrations.RemoveField(
            model_name="datapivotquery",
            name="prefilters",
        ),
        migrations.RenameField(
            model_name="datapivotquery",
            old_name="temp",
            new_name="prefilters",
        ),
    ]
