# Generated by Django 4.2.3 on 2023-08-21 03:49


from django.db import migrations


def published_only_prefilters(apps, schema_editor):
    # add published_only field to prefilters
    DataPivotQuery = apps.get_model("summary", "DataPivotQuery")
    objs = DataPivotQuery.objects.all()
    for obj in objs:
        obj.prefilters["published_only"] = obj.published_only
    DataPivotQuery.objects.bulk_update(objs, ["prefilters"])


def reverse_published_only_prefilters(apps, schema_editor):
    # separate published_only field from prefilters
    DataPivotQuery = apps.get_model("summary", "DataPivotQuery")
    objs = DataPivotQuery.objects.all()
    for obj in objs:
        obj.published_only = obj.prefilters["published_only"]
    DataPivotQuery.objects.bulk_update(objs, ["published_only"])


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0044_visual_prefilters_json"),
    ]

    operations = [
        migrations.RunPython(
            published_only_prefilters, reverse_code=reverse_published_only_prefilters
        ),
        migrations.RemoveField(
            model_name="datapivotquery",
            name="published_only",
        ),
    ]
