# Generated by Django 4.2.3 on 2023-08-22 06:47

from django.db import migrations


def studies_prefilters(apps, schema_editor):
    # add studies field to prefilters
    Visual = apps.get_model("summary", "Visual")
    objs = Visual.objects.all().prefetch_related("studies")
    for obj in objs:
        obj.prefilters["studies"] = list(obj.studies.all().values_list("pk", flat=True))
    Visual.objects.bulk_update(objs, ["prefilters"])


def reverse_studies_prefilters(apps, schema_editor):
    # separate studies field from prefilters
    # TODO easiest way is probably to get the through table
    # and create records there using pks
    return


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0045_datapivotquery_published_only_to_prefilters"),
    ]

    operations = [
        migrations.RunPython(studies_prefilters, reverse_code=reverse_studies_prefilters),
        migrations.RemoveField(
            model_name="visual",
            name="studies",
        ),
    ]
