# Generated by Django 4.2.3 on 2023-09-21 20:38
import json

from django.db import migrations, models


def settings_json(apps, schema_editor):
    Visual = apps.get_model("summary", "Visual")
    changed = []
    for visual in Visual.objects.all():
        try:
            json.loads(visual.settings)
        except (TypeError, ValueError):
            visual.settings = {}
            changed.append(visual)
    if changed:
        Visual.objects.bulk_update(changed, ["settings"])


def reverse_settings_json(apps, schema_editor):
    Visual = apps.get_model("summary", "Visual")
    changed = []
    for visual in Visual.objects.all():
        settings = json.loads(visual.settings)
        if len(settings) == 0:
            visual.settings = "undefined"
    if changed:
        Visual.objects.bulk_update(changed, ["settings"])


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0048_visual_studies_to_prefilters"),
    ]

    operations = [
        migrations.RunPython(settings_json, reverse_code=reverse_settings_json),
        migrations.AlterField(
            model_name="visual",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
