# Generated by Django 4.2.3 on 2023-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0050_heatmap_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="visual",
            name="evidence_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Animal Bioassay"),
                    (1, "Epidemiology"),
                    (4, "Epidemiology meta-analysis/pooled analysis"),
                    (2, "In vitro"),
                    (5, "Ecology"),
                    (3, "Other"),
                ],
                default=0,
            ),
        ),
    ]
