# Generated by Django 5.1 on 2024-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0056_move_sort_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummaryText",
        ),
    ]
