# Generated by Django 5.1.4 on 2025-01-15 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("summary", "0059_move_data_pivot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datapivot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="datapivot",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="datapivotupload",
            name="datapivot_ptr",
        ),
        migrations.DeleteModel(
            name="DataPivotQuery",
        ),
        migrations.DeleteModel(
            name="DataPivot",
        ),
        migrations.DeleteModel(
            name="DataPivotUpload",
        ),
    ]
