# Generated by Django 4.2.4 on 2023-08-31 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdataextraction",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customdataextraction",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="editable_forms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customdataextraction",
            name="parent_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_forms",
                to="form_library.customdataextraction",
            ),
        ),
        migrations.AlterField(
            model_name="customdataextraction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customdataextraction",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
