# Generated by Django 4.2.4 on 2023-09-18 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form_library", "0002_customdataextraction_creator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDefinedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("schema", models.JSONField()),
                ("deprecated", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True, related_name="editable_forms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="form_library.userdefinedform",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated"],
                "unique_together": {("creator", "name")},
            },
        ),
        migrations.DeleteModel(
            name="CustomDataExtraction",
        ),
    ]
