const DC_BIO_SD = "bioassay-study-design",
    DC_BIO_EP = "bioassay-endpoint-summary",
    DC_EPI_SD = "epidemiology-study-design",
    DC_EPI_RE = "epidemiology-result-summary",
    DATA_CLASSES = [DC_BIO_SD, DC_BIO_EP, DC_EPI_SD, DC_EPI_RE],
    AXIS_OPTIONS = [
        {
            data_classes: [DC_BIO_SD],
            id: "dose-units",
            label: "Dose units",
            settings: [{column: "dose units", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_BIO_SD],
            id: "route-of-exposure",
            label: "Route of exposure",
            settings: [{column: "route of exposure", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_BIO_SD],
            id: "study-citation",
            label: "Study citation",
            settings: [{column: "study citation", delimiter: "", wrap_text: 0}],
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "test-subject",
            label: "Species & Sex",
            settings: [
                {column: "species", delimiter: "|", wrap_text: 0},
                {column: "sex", delimiter: "|", wrap_text: 0},
            ],
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "study-design",
            label: "Study design",
            settings: [{column: "experiment type", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "system",
            label: "System",
            settings: [{column: "system", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_EPI_SD, DC_EPI_RE],
            id: "exposure",
            label: "Exposure",
            settings: [{column: "exposure name", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_EPI_SD, DC_EPI_RE],
            id: "study-design",
            label: "Study design",
            settings: [{column: "study design", delimiter: "|", wrap_text: 0}],
        },
        {
            data_classes: [DC_EPI_SD, DC_EPI_RE],
            id: "system+effect",
            label: "System & Effect",
            settings: [
                {column: "system", delimiter: "|", wrap_text: 0},
                {column: "effect", delimiter: "|", wrap_text: 0},
            ],
        },
    ],
    FILTER_OPTIONS = [
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP, DC_EPI_SD, DC_EPI_RE],
            id: "study-citation",
            label: "study citation",
            settings: {column: "study citation", delimiter: "", on_click_event: "study"},
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "system",
            label: "system",
            settings: {column: "system", delimiter: "|", on_click_event: "endpoint_complete"},
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "organ",
            label: "organ",
            settings: {column: "organ", delimiter: "|", on_click_event: "endpoint_complete"},
        },
        {
            data_classes: [DC_BIO_SD, DC_BIO_EP],
            id: "effect",
            label: "effect",
            settings: {column: "effect", delimiter: "|", on_click_event: "endpoint_complete"},
        },
    ],
    TABLE_FIELDS = {
        [DC_BIO_SD]: [
            {column: "study citation", delimiter: "", on_click_event: "study"},
            {column: "system", delimiter: "|", on_click_event: "---"},
            {column: "dose units", delimiter: "|", on_click_event: "---"},
        ],
        [DC_BIO_EP]: [
            {column: "study citation", delimiter: "", on_click_event: "study"},
            {column: "experiment name", delimiter: "", on_click_event: "experiment"},
            {column: "species", delimiter: "", on_click_event: "animal_group"},
            {column: "strain", delimiter: "", on_click_event: "---"},
            {column: "system", delimiter: "", on_click_event: "---"},
            {column: "organ", delimiter: "", on_click_event: "---"},
            {column: "effect", delimiter: "", on_click_event: "---"},
            {column: "endpoint name", delimiter: "", on_click_event: "endpoint_complete"},
        ],
        [DC_EPI_SD]: [
            {column: "study citation", delimiter: "", on_click_event: "study"},
            {column: "exposure name", delimiter: "|", on_click_event: "---"},
            {column: "system", delimiter: "|", on_click_event: "---"},
            {column: "effect", delimiter: "|", on_click_event: "---"},
        ],
        [DC_EPI_RE]: [
            {column: "study citation", delimiter: "", on_click_event: "study"},
            {column: "exposure name", delimiter: "", on_click_event: "exposure"},
            {column: "result name", delimiter: "", on_click_event: "result"},
        ],
    },
    DASHBOARDS = [
        {
            data_class: DC_BIO_SD,
            id: "bio-sd-system-vs-study-design",
            label: "system vs. study design",
            x_axis: "study-design",
            y_axis: "system",
            filters: ["study-citation", "effect"],
        },
        {
            data_class: DC_BIO_SD,
            id: "bio-sd-system-vs-test-subject",
            label: "system vs. test subject",
            x_axis: "test-subject",
            y_axis: "system",
            filters: ["study-citation", "effect"],
        },
        {
            data_class: DC_BIO_SD,
            id: "bio-sd-dose-units-vs-route",
            label: "dose units vs. route of exposure",
            x_axis: "dose-units",
            y_axis: "route-of-exposure",
            filters: ["study-citation"],
        },
        {
            data_class: DC_BIO_EP,
            id: "bio-ep-system-vs-test-subject",
            label: "system vs. test subject",
            x_axis: "test-subject",
            y_axis: "system",
            filters: ["study-citation", "organ", "effect"],
        },
        {
            data_class: DC_EPI_SD,
            id: "epi-sd-study-design-vs-effect",
            label: "study design vs. effect",
            x_axis: "study-design",
            y_axis: "system+effect",
            filters: ["study-citation"],
        },
        {
            data_class: DC_EPI_SD,
            id: "epi-sd-exposure-vs-effect",
            label: "exposure vs. effect",
            x_axis: "exposure",
            y_axis: "system+effect",
            filters: ["study-citation"],
        },
        {
            data_class: DC_EPI_RE,
            id: "epi-res-study-design-vs-effect",
            label: "study design vs. effect",
            x_axis: "study-design",
            y_axis: "system+effect",
            filters: ["study-citation"],
        },
        {
            data_class: DC_EPI_RE,
            id: "epi-res-exposure-effect",
            label: "exposure vs. effect",
            x_axis: "exposure",
            y_axis: "system+effect",
            filters: ["study-citation"],
        },
    ];

export {DATA_CLASSES, AXIS_OPTIONS, FILTER_OPTIONS, TABLE_FIELDS, DASHBOARDS};
