# Generated by Django 5.2.12 on 2026-05-21 19:42

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0048_delete_job"),
        ("study", "0013_study_mechanistic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This field is commonly used in visualizations, so consider using a common acronym, e.g., BPA instead of Bisphenol A",
                        max_length=128,
                    ),
                ),
                (
                    "cas",
                    models.CharField(
                        blank=True,
                        help_text="CAS #",
                        max_length=255,
                        verbose_name="Chemical identifier (CAS)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Company and catalog number (if available)",
                        max_length=255,
                    ),
                ),
                (
                    "composition_purity",
                    models.CharField(
                        choices=[
                            ("AG", "Analytical Grade"),
                            ("TG", "Technical Grade"),
                            ("NS", "Purity Not Specified"),
                            ("NA", "Not Applicable (e.g. In Silico Study)"),
                            ("OT", "Other"),
                        ],
                        help_text="If detailed information on the purity of the composition is not known, a qualitative statement can be provided in this field, e.g. 'analytical grade' or 'technical grade'. A chemical can be created for a mixture/product. If the chemical refers to the composition of the mixture/product, in the field % purity, specify the chemical composition.",
                        max_length=2,
                        verbose_name="Composition / Purity",
                    ),
                ),
                (
                    "composition_purity_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about composition/purity.",
                        max_length=255,
                    ),
                ),
                (
                    "percent_purity",
                    models.FloatField(
                        blank=True,
                        help_text="Provide the % purity or chemical composition",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% Purity",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Enter other descriptive information on the chemical, e.g. technical, nature, relevant P-chem properties.",
                        verbose_name="Chemical description comment",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "dsstox",
                    models.ForeignKey(
                        blank=True,
                        help_text='<a rel="noopener noreferrer" target="_blank" href="https://www.epa.gov/chemical-research/distributed-structure-searchable-toxicity-dsstox-database">DssTox</a> substance identifier (recommended). When using an identifier, chemical name and CASRN are standardized using the <a href="https://comptox.epa.gov/dashboard/" rel="noopener noreferrer" target="_blank">DTXSID</a>.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_dsstox",
                        to="assessment.dsstox",
                        verbose_name="DSSTox substance identifier",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_chemicals",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name / identifier of the method (if available)",
                        max_length=255,
                        verbose_name="Method Name",
                    ),
                ),
                (
                    "has_high_throughput",
                    models.BooleanField(
                        default=False,
                        help_text="Indicate if the experiment is high throughput.",
                        verbose_name="High throughput?",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a short description of the method and how it is relevant to the endpoint being investigated.",
                        verbose_name="Method Description",
                    ),
                ),
                (
                    "protocol",
                    models.FileField(
                        blank=True,
                        help_text="In case the protocol is available (e.g. as supplement to a publication), please provide it as an attachment. The protocol includes the practical steps that were performed in the laboratory to generate the data.",
                        upload_to="mechanistic-experiment-protocols",
                    ),
                ),
                (
                    "test_facility",
                    models.TextField(
                        blank=True,
                        help_text="If available, enter:<br><ul><li>Test Facility Name</li><li>Location</li><li>Study director name</li><li>Other personnel name and responsibility</li><li>Study period: study start and end dates</li></ul>",
                    ),
                ),
                (
                    "guideline",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("NR", "Not reported")],
                        help_text="Select whether a guideline study was conducted. If yes, enter the TG# in the Guideline Name & Number field",
                        max_length=3,
                    ),
                ),
                (
                    "guideline_name_number",
                    models.CharField(
                        help_text="Enter in Guideline; e.g. OECD or OCSPP",
                        max_length=255,
                        verbose_name="Guideline Name & Number",
                    ),
                ),
                ("guideline_compliance", models.CharField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_experiments",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mechanistic Experiment",
                "verbose_name_plural": "Mechanistic Experiments",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TestSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provide a descriptive name for the experiment (e.g. Estrogen Receptor Biding Assay Using Rat Uterine Cytosol)",
                        max_length=255,
                    ),
                ),
                (
                    "test_system_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAC", "bacteria"),
                            ("CFR", "cellular fraction"),
                            ("BTS", "complex biological test system"),
                            ("CLN", "cell line"),
                            ("PCB", "physical / chemical based"),
                            ("PRI", "primary cells"),
                            ("TIS", "tissue"),
                            ("YEA", "yeast"),
                            ("CF", "cell free"),
                            ("OTH", "other, specify"),
                        ],
                        help_text="A test system is any biological, chemical or physical system or a combination thereof used in a study (OECD (2018), Guidance Document on Good In Vitro Method Practices (GIVIMP), OECD Series on Testing and Assessment, No. 286, OECD Publishing, Paris).<p>Examples of physical chemical based test systems: serum protein, peptide, enzyme.<p>Select complex biological test system for example in case of: 3D model, induced pluripotent stem cells, organ on a chip, co-cultures, etc.<p>Select 'other:' in case you don't find a suitable option, for example when your test system is a test kit or a lower in vivo organism.<p>If select “other” enter in free text field “Type of test system “other” remarks”",
                        max_length=3,
                    ),
                ),
                (
                    "test_system_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify the type of test system",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Describe the composition of the test system, e.g. the cells / tissues / proteins / 3D models / induced pluripotent stem cells / organ on chip / co-cultures etc. that were used in the study. When applicable, provide the following information on the genetic modification: - Gene inserted - Gene species (e.g. human, rat, mouse) - Additional information on modification",
                        max_length=255,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CO", "Commercial supplier, specify"),
                            ("NC", "Non-commercial supplier, specify"),
                            ("IH", "In house developed, specify"),
                            ("OT", "Other"),
                        ],
                        help_text="Select the appropriate test system used in the experiment.<p>In case the test system needs to be created in house (e.g. co-cultures, genetic modification), select 'in house developed'",
                        max_length=2,
                        verbose_name="Source/Supplier",
                    ),
                ),
                (
                    "supplier_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide information on the test system source and select if the test system was obtained from a commercial (e.g. cell bank) or non-commercial supplier (e.g. collaborating organisation), or if it was in-house developed or established.",
                        max_length=255,
                        verbose_name="Source/Supplier Remarks",
                    ),
                ),
                (
                    "catalogue_number",
                    models.CharField(
                        blank=True,
                        help_text="Provide the following details for the test system:<br><ul><li>Name</li><li>Source / supplier</li><li>Catalogue / batch number</li><ul>",
                        max_length=255,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Provide the batch/lot number that was used in the study. If unknown, enter “unknown”.",
                        max_length=255,
                        verbose_name="Lot/Batch Number",
                    ),
                ),
                (
                    "genetic_modification",
                    models.CharField(
                        choices=[
                            (
                                "POSTPURCHASE",
                                "genetically modified after purchase, prior to use",
                            ),
                            ("SUPPLIER", "genetically modified by supplier"),
                            ("NA", "not applicable"),
                            ("NOMOD", "not genetically modified"),
                            ("NS", "not specified"),
                        ],
                        help_text="Help text: Select option that best fits - if genetically modified after purchase, prior to use or genetically modified by supplier add additional information on modification in remarks field",
                        max_length=12,
                        verbose_name="Genetic modification of the test system",
                    ),
                ),
                (
                    "genetic_modification_remarks",
                    models.CharField(
                        blank=True,
                        help_text="When applicable, provide the following information on the genetic modification:<ul><li>Gene inserted</li><li>Gene species (e.g. human, rat, mouse)</li></ul>",
                        max_length=255,
                        verbose_name="Genetic modification of the test system remarks",
                    ),
                ),
                (
                    "metabolic_competence",
                    models.CharField(
                        choices=[
                            ("LIM", "limited metabolic activity, specify"),
                            ("MET", "metabolic activity, specify"),
                            ("UNK", "unknown metabolic activity"),
                            (
                                "OTH",
                                "other information on metabolic competence, describe:",
                            ),
                            ("NA", "not applicable"),
                        ],
                        help_text="Select the option that fits best and describe the knowledge about the metabolic competence (i.e. Phase I and/or II biotransformation capacity) of the test system under remarks.<p>For example, when the test system used is  cryopreserved human pooled liver tissue homogenate 9000 g fraction (S9) procured from a commercial supplier, select “metabolic activity, specify” and specify: contains phase I and II metabolic enzymes present in the microsomal (e.g. cytochrome P450s, Flavin-containing monooxygenase, uridine 5’-diphospho-glucuronosyltransferases, carboxylesterases) and cytosolic (e.g. sulfotransferases, glutathione S-transferases, methyltransferases, N-acetyl transferases, xanthine oxidase, aldehyde oxidase) fractions.",
                        max_length=3,
                        verbose_name="Metabolic competence of the test system",
                    ),
                ),
                (
                    "metabolic_competence_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Describe the method underlying metabolic competence of the test system",
                        max_length=255,
                        verbose_name="Metabolic competence of the test system remarks",
                    ),
                ),
                (
                    "medium_buffer",
                    models.CharField(
                        blank=True,
                        help_text="Description of stock medium or buffer including name, source, Lot/batch #, pH (if applicable)",
                        max_length=255,
                        verbose_name="Stock medium/buffer",
                    ),
                ),
                (
                    "serum_supplements",
                    models.CharField(
                        blank=True,
                        help_text="Describe Serum - name, source, lot/batch #, final conc<p>Supplements - name, source, lot/batch #, final conc",
                        max_length=255,
                        verbose_name="Stock medium serum/supplements",
                    ),
                ),
                (
                    "maintenance",
                    models.CharField(
                        blank=True,
                        help_text="Provide information on the routine maintenance of the test system: cell-based: Incubation conditions (humidity, temperature, CO2, etc.) Cell-free: buffer, PH, concentration",
                        max_length=255,
                    ),
                ),
                (
                    "qc_confirmation",
                    models.CharField(
                        choices=[
                            ("ABSMYC", "absence of mycoplasma"),
                            (
                                "STERILITY",
                                "sterility (absence of bacteria, fungi, yeast)",
                            ),
                            ("ABSPATH", "absence of pathological viruses"),
                            ("KARYO", "karyotype stability"),
                            ("RESPPOS", "test system response to positive control"),
                            ("RESPSOLV", "test system response to solvent control"),
                            ("RESPBASE", "test system baseline response"),
                            ("EXPBIO", "test system expression of biological markers"),
                            ("OTHER", "Other, specify"),
                        ],
                        help_text="Select which quality control that was performed on the test system, before or during the generation of results, to confirm the test system was healthy, stable and responsive. If “other” is selected, please specify in the “confirmation of quality control remarks” field",
                        max_length=9,
                        verbose_name="Confirmation of quality control",
                    ),
                ),
                (
                    "qc_confirmation_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Specify the quality control that was performed on the test system, before or during the generation of results, to confirm the test system was healthy, stable and / or responsive.",
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testsystems",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.species",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TestDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("DMSO", "DMSO"),
                            ("ACET", "acetone"),
                            ("ETHA", "ethanol"),
                            ("NREQ", "not required"),
                            ("NSPE", "not specified"),
                            ("SALI", "saline"),
                            ("TREX", "treatment/exposure medium"),
                            ("WATR", "water"),
                            ("OTHR", "other"),
                        ],
                        help_text="If a vehicle or solvent was used, select the relevant item or use 'other:' and specify.",
                        max_length=4,
                        verbose_name="Vehicle/Solvent",
                    ),
                ),
                (
                    "vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about vehicle/solvent.",
                        max_length=255,
                        verbose_name="Vehicle/Solvent: Additional Details",
                    ),
                ),
                (
                    "final_concentration_vehicle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PT1", "0.1%"),
                            ("PT2", "0.2%"),
                            ("PT5", "0.5%"),
                            ("ONE", "1.0%"),
                            ("NS", "Not specified"),
                            ("OTH", "Other, please specify"),
                        ],
                        help_text="Specify the % of vehicle / solvent in the final incubation mixture",
                        max_length=4,
                        verbose_name="Final concentration of the vehicle/solvent",
                    ),
                ),
                (
                    "final_concentration_vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about final concentration.",
                        max_length=255,
                        verbose_name="Final concentration: Additional Details",
                    ),
                ),
                (
                    "final_concentration_vehicle_units",
                    models.CharField(
                        blank=True,
                        choices=[("TODO", "todo/placeholder")],
                        help_text="Specify the vehicle / solvent unit",
                        max_length=4,
                        verbose_name="Final concentration of the vehicle/solvent unit",
                    ),
                ),
                (
                    "concentration_selection",
                    models.CharField(
                        choices=[
                            ("HUEX", "human exposure levels"),
                            (
                                "INDE",
                                "interference with the detection method (e.g. auto fluorescence)",
                            ),
                            (
                                "INTS",
                                "interference with the test system (e.g. cytotoxicity or pH)",
                            ),
                            (
                                "PRIN",
                                "prior information of response (e.g. dose-range finding experiment)",
                            ),
                            ("SOEM", "solubility in exposure medium"),
                            ("SOSO", "solubility in solvent"),
                            ("UNKW", "unknown"),
                            ("OTHR", "other"),
                        ],
                        help_text="For data interpretation it is important to know on what basis the highest concentration tested was selected.<p>Any free text explanation can be given in the adjacent text field to justify the dose level selected.",
                        max_length=4,
                        verbose_name="Concentration selection of the test material",
                    ),
                ),
                (
                    "concentration_selection_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Any free text explanation can be given in the adjacent text field to justify the dose level selected.",
                        verbose_name="Concentration selection of the test material: Additional Details",
                    ),
                ),
                (
                    "concentrations_tested",
                    models.JSONField(
                        help_text="Concentrations tested - test field/widget"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint_detection_method",
                    models.CharField(
                        choices=[
                            ("ANALYTICAL", "analytical method (e.g. LC/MS)"),
                            ("CHROMATO", "chromatography"),
                            ("COMPLEX", "complex detection methods (e.g. imaging)"),
                            ("FLUORO", "fluorescence"),
                            ("LUMIN", "luminescence"),
                            ("RADIOACTIV", "radioactivity"),
                            ("ABSORP", "UV/VIS absorption"),
                            ("OTHER", "other"),
                        ],
                        help_text="Indicate the readout used endpoint detection. Select a detection method type from the picklist and provide the type of instrument (e.g. HPLC, Spectrophotometer, Flow cytometer) or chose 'other: and specify the type or equipment used / analysis performed.",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        choices=[
                            ("SEMI", "Semi or non-quantitative detection methods"),
                            ("QUAN", "quantitative"),
                        ],
                        help_text="Select what type of qualitative method was used and describe the method in the remarks field below.",
                        max_length=4,
                        verbose_name="Details on detection method",
                    ),
                ),
                (
                    "parameters_measured",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("RFU", "RFU"),
                                ("RLU", "RLU"),
                                ("OD", "OD"),
                                (
                                    "CPD",
                                    "Detected compound (e.g. metabolite detection with LC-MS)",
                                ),
                                ("PKA", "Peak area"),
                                ("PKH", "Peak height"),
                                ("FSC", "Forward Scatter"),
                                ("SSC", "Side Scatter"),
                                ("DBI", "Detected biomarker (e.g. with imaging)"),
                                ("OTH", "Other"),
                            ],
                            max_length=3,
                        ),
                        help_text="Describe the unit or output that was provided by the instrument during the measurement. This is the instrument unit of measure of the raw data.",
                        size=None,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide any other relevant information on the detection method not described above",
                        verbose_name="Remarks on detection method",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
