# Generated by Django 5.2.12 on 2026-06-18 20:41

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import hawc.apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0048_delete_job"),
        ("study", "0013_study_mechanistic"),
        ("vocab", "0009_alter_entity_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This field is commonly used in visualizations, so consider using a common acronym, e.g., BPA instead of Bisphenol A",
                        max_length=128,
                    ),
                ),
                (
                    "cas",
                    models.CharField(
                        blank=True,
                        help_text="CAS #",
                        max_length=255,
                        verbose_name="Chemical identifier (CAS)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Company and catalog number (if available)",
                        max_length=255,
                    ),
                ),
                (
                    "composition_purity",
                    models.CharField(
                        choices=[
                            ("AG", "Analytical Grade"),
                            ("TG", "Technical Grade"),
                            ("NS", "Purity Not Specified"),
                            ("NA", "Not Applicable (e.g. In Silico Study)"),
                            ("OT", "Other"),
                        ],
                        help_text="If detailed information on the purity of the composition is not known, a qualitative statement can be provided in this field, e.g. 'analytical grade' or 'technical grade'. A chemical can be created for a mixture/product. If the chemical refers to the composition of the mixture/product, in the field % purity, specify the chemical composition.",
                        max_length=2,
                        verbose_name="Composition / Purity",
                    ),
                ),
                (
                    "composition_purity_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about composition/purity.",
                        max_length=255,
                    ),
                ),
                (
                    "percent_purity",
                    models.FloatField(
                        blank=True,
                        help_text="Provide the % purity or chemical composition",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% Purity",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Enter other descriptive information on the chemical, e.g. technical, nature, relevant P-chem properties.",
                        verbose_name="Chemical description comment",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "dsstox",
                    models.ForeignKey(
                        blank=True,
                        help_text='<a rel="noopener noreferrer" target="_blank" href="https://www.epa.gov/chemical-research/distributed-structure-searchable-toxicity-dsstox-database">DssTox</a> substance identifier (recommended). When using an identifier, chemical name and CASRN are standardized using the <a href="https://comptox.epa.gov/dashboard/" rel="noopener noreferrer" target="_blank">DTXSID</a>.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_dsstox",
                        to="assessment.dsstox",
                        verbose_name="DSSTox substance identifier",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_chemicals",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name / identifier of the method (if available)",
                        max_length=255,
                        verbose_name="Method Name",
                    ),
                ),
                (
                    "has_high_throughput",
                    models.BooleanField(
                        default=False,
                        help_text="Indicate if the experiment is high throughput.",
                        verbose_name="High throughput?",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a short description of the method and how it is relevant to the endpoint being investigated.",
                        verbose_name="Method Description",
                    ),
                ),
                (
                    "protocol",
                    models.FileField(
                        blank=True,
                        help_text="In case the protocol is available (e.g. as supplement to a publication), please provide it as an attachment. The protocol includes the practical steps that were performed in the laboratory to generate the data.",
                        upload_to="mechanistic-experiment-protocols",
                    ),
                ),
                (
                    "test_facility",
                    models.TextField(
                        blank=True,
                        help_text="If available, enter:<br><ul><li>Test Facility Name</li><li>Location</li><li>Study director name</li><li>Other personnel name and responsibility</li><li>Study period: study start and end dates</li></ul>",
                    ),
                ),
                (
                    "guideline",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("NR", "Not reported")],
                        help_text="Select whether a guideline study was conducted. If yes, enter the TG# in the Guideline Name & Number field",
                        max_length=3,
                    ),
                ),
                (
                    "guideline_name_number",
                    models.CharField(
                        help_text="Enter in Guideline; e.g. OECD or OCSPP",
                        max_length=255,
                        verbose_name="Guideline Name & Number",
                    ),
                ),
                ("guideline_compliance", models.CharField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_experiments",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mechanistic Experiment",
                "verbose_name_plural": "Mechanistic Experiments",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="DataAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Select whether criteria were used for the validity of the experiment and acceptance of the result. If so, please specify the criteria used to accept or reject an experiment or result.",
                        max_length=2,
                        verbose_name="Validity / acceptance criteria",
                    ),
                ),
                (
                    "validity_remarks",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Validity / acceptance criteria remarks",
                    ),
                ),
                (
                    "cytotoxicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Was the absence of cytotoxicity confirmed? Select the best answer and provide other relevant details in the remarks field. If yes, specify the type of cytotoxicity assay used.",
                        max_length=2,
                        verbose_name="Cytotoxicity assay",
                    ),
                ),
                (
                    "cytotoxicity_remarks",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Cytotoxicity assay remarks",
                    ),
                ),
                (
                    "interference_tests",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Was the absence of interference from test material confirmed? Select yes in case another type of analysis (other than cytotoxicity) was performed that is important for the interpretation of results (e.g. autofluorescence, quenching, etc.). If yes, specify the type of inference test used.",
                        max_length=2,
                    ),
                ),
                (
                    "interference_tests_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "detection_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Did the (object) measurement fall within the detection range for the method used?",
                        max_length=2,
                    ),
                ),
                (
                    "detection_range_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "data_calculation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Is it clear how results are calculated from the raw data?<br>Provide in the remarks field:<br><ul><li>Calculations performed</li><li>Statistical methods used</li><li>Where relevant, provide the method used to exclude outliers</li></ul>",
                        max_length=2,
                        verbose_name="Data calculation and statistics",
                    ),
                ),
                (
                    "data_calculation_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "evaluation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Is there criteria available to determine if the test material resulted as active (or not) in the study? If yes, describe the evaluation criteria used in the study to judge if the test material is positive, negative or equivocal. For example:<p>When there is more than 10% binding to the androgen receptor (as expressed in relative light units) for more than two concentrations, the result is ‘positive’.",
                        max_length=2,
                        verbose_name="Evaluation / data interpretation criteria",
                    ),
                ),
                ("evaluation_remarks", models.CharField(blank=True, max_length=2000)),
                (
                    "general_remarks",
                    models.CharField(
                        blank=True,
                        max_length=32768,
                        verbose_name="Remarks on data analysis",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataanalyses",
                        to="mechanistic.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ExperimentalDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_system_concentration",
                    models.CharField(
                        help_text="Indicate the number of cells or cell density in case of cell lines. Concentration of biological test systems is usually expressed as cell density (amount of cells/cm2 or cells/ml seeded) or confluence (%).",
                        max_length=255,
                        verbose_name="Test system concentration (e.g. cell density)",
                    ),
                ),
                (
                    "passage_number",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the passage number only in case that the test system is a cell line, report the passage number(s) used.",
                        max_length=255,
                    ),
                ),
                (
                    "exposure_medium_composition",
                    models.CharField(
                        blank=True,
                        help_text="Indicate what is the composition of the exposure medium where the test system and test material are incubated together to obtain the result. In case serum is present (not recommended) then please indicate the type and %.",
                        max_length=255,
                        verbose_name="Composition of exposure medium",
                    ),
                ),
                (
                    "incubation_conditions",
                    models.CharField(
                        blank=True,
                        help_text="Indicate cell culture incubation conditions (e.g., temperature, relative humidity, CO2 %, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "exposure_duration",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the time of incubation / exposure of the test system to the test material.",
                        max_length=255,
                    ),
                ),
                (
                    "administration_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the frequency of test material administration.",
                        max_length=255,
                        verbose_name="Frequency of Administration",
                    ),
                ),
                (
                    "technical_replicates",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the number of replicates included per concentration test item tested.",
                        max_length=255,
                        verbose_name="Number of technical replicates",
                    ),
                ),
                (
                    "biological_replicates",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the number of biologically independent experiments that were performed. Experiments should be separated in space and time to be considered independent.",
                        max_length=255,
                        verbose_name="Number of biological replicates",
                    ),
                ),
                (
                    "vessel_type",
                    models.CharField(
                        blank=True,
                        help_text="Indicate the vessel type including size and material (e.g. glass test tube, glass bottom 96 well plate, 384 well polystyrene cell culture plate, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, verbose_name="Remarks on experimental conditions"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experimentaldesigns",
                        to="mechanistic.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MechanisticEndpoint",
            fields=[
                (
                    "baseendpoint_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.baseendpoint",
                    ),
                ),
                (
                    "poa_process",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APOP", "apoptotic process - [GO:0008219]"),
                            ("BIOP", "biosynthetic process - [GO:0009058]"),
                            ("CATA", "catalytic activity - [GO:0003824]"),
                            ("CACT", "cell activation - [GO:0001775]"),
                            ("CDEA", "cell death - [GO:0008219]"),
                            ("CDIF", "cell differentiation - [GO:0030154]"),
                            ("CMIG", "cell migration - [GO:0016477]"),
                            ("CPRO", "cell proliferation - [GO:0008283]"),
                            ("GEXP", "gene expression - [GO:0010467]"),
                            ("KACT", "keratinocyte activation - [GO:0032980]"),
                            ("METP", "metabolic process - [GO:0008152]"),
                            ("NURA", "nuclear receptor activity - [GO:0004879]"),
                            ("NURB", "nuclear receptor binding - [GO:0016922]"),
                            ("OXST", "oxidative stress - [NCIT:C17741]"),
                            ("PERA", "peroxidase activity - [GO:0004601]"),
                            ("PNCD", "programmed necrotic cell death - [GO:0097300]"),
                            ("PROB", "protein binding - [GO:0005515]"),
                            ("PROI", "protein iodination - [GO:0018077]"),
                            ("RECA", "receptor activity - [GO:0004872]"),
                            ("RECB", "receptor binding - [GO:0005102]"),
                            ("SIGN", "signalling - [GO:0023052]"),
                            (
                                "SHBP",
                                "steroid hormone biosynthetic process - [GO:0120178]",
                            ),
                            ("TRAA", "transporter activity - [GO:0005215]"),
                            ("OTHR", "other"),
                        ],
                        help_text="Process represents the dynamics of the underlying biological system (e.g., receptor binding) (Ives et al, 2017). The Process is also used to annotate Key events in the Adverse Outcome Pathway Wiki (https://aopwiki.org/) as described in Ives et al, 2017, doi:10.1089/aivt.2017.0017).<p>Select the process that best describes the mechanistic information observed or select ‘other’ to specify the Process and provide a term. Please consult the Ontology Lookup Service (OLS) which is available at https://www.ebi.ac.uk/ols/index to choose a Process term. If possible please select as Process one term belonging to the following ontology Gene Ontology (GO).<p>For most terms there will be several options. It is therefore important to also copy the preferred ontology identifier into the remarks field.<p>Cytotoxicity data should only be reported as a process (e.g. cell death) when it is the scope of the study to determine cytotoxicity. In cases where cytotoxicity is measured for supporting information e.g. for dose selection/elimination, it should not be considered as a process. Such data are reported as ‘Other observations’.",
                        max_length=4,
                        verbose_name="Process",
                    ),
                ),
                (
                    "poa_process_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about Process",
                        max_length=255,
                    ),
                ),
                (
                    "poa_object",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NAME", "Object name, specify"),
                            ("IDEN", "Object identifier, specify"),
                        ],
                        help_text="Object represents the subject of the observed measurement (biological or chemical), for example, a specific biological receptor that is activated or inhibited, a specific molecule that is being formed and detected or a specific protein that is being bound. The Object is also used to annotate Key events in the Adverse Outcome Pathway Wiki (https://aopwiki.org/) as described in Ives et al, 2017, doi:10.1089/aivt.2017.0017).<p>It is optional to record both Process and Object. If both Process and Object are recorded, they have to be concordant with the chosen Action.<p>Please consult the Ontology Lookup Service (OLS) which is available at https://www.ebi.ac.uk/ols/index to choose a Process term. If possible, please select as Object one term belonging to the following ontologies protein Ontology (PR) or Chemical Entities of Biological Interest (ChEBI).<p> Enter the name and identifier of the object:<p>For most terms there will be several options. It is therefore important to also copy the preferred ontology identifier into the remarks field.<p>More than one object can be provided e.g. when changes of more than one biomarker is measured.<p>Examples of objects are:<br><ul><li>CD86 molecule - [PR:000001412]</li><li>cytochrome P450 - [CHEBI:38559]</li><li>interleukin 8 (IL8) - [PR:000001395]</li><li>thyroid peroxidase (TPO) - [PR:000016584]</li><li>UDP-glucuronosyltransferase (UDP GT) - [PR:000024849]</li></ul>",
                        max_length=4,
                        verbose_name="Object",
                    ),
                ),
                (
                    "poa_object_details",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about Object",
                        max_length=255,
                    ),
                ),
                (
                    "poa_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALTR", "alteration"),
                            ("BIND", "binder / non-binder"),
                            ("DECR", "decrease"),
                            ("DECA", "decrease, antagonism"),
                            ("DISR", "disruption"),
                            ("DREG", "down regulation"),
                            ("ENHA", "enhancement"),
                            ("INCR", "increase"),
                            ("INDE", "increase / decrease"),
                            ("INCA", "increase, agonism"),
                            ("INDU", "induction"),
                            ("INHI", "inhibition"),
                            ("OCCR", "occurrence"),
                            ("UREG", "up regulation"),
                            ("OTHR", "other"),
                        ],
                        help_text="Action represents the type of change observed e.g. ‘‘decrease’’ in the case where a receptor is inhibited to indicate a decrease in the signalling by that receptor. Action is also used to annotate Key events in the Adverse Outcome Pathway Wiki (https://aopwiki.org/) as described in Ives et al, 2017, doi:10.1089/aivt.2017.0017). Action is used together with the field Process and/or Object.<p>The Action field is always required to describe the type of change observed and it can form the following syntaxes “Process, Action” e.g. “gene expression, increase” or “Process, Object, Action” e.g. receptor activity, estrogen receptor, increase.<p>Select the Action that best describes the change observed or select ‘other’ to  specify the action and provide a term.",
                        max_length=4,
                        verbose_name="Action",
                    ),
                ),
                (
                    "poa_action_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about Action",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="Enter details about the endpoint that is measured in the (research) study.<br>Describe the (biological) change that is measured and what this means for human health, the environment or wildlife.",
                        verbose_name="Details on the effect measured",
                    ),
                ),
                (
                    "links_to_aops",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        help_text="Does the effect identification link to an AOP, MIE, KE, or KER? See https://aopwiki.org/.",
                        max_length=3,
                    ),
                ),
                (
                    "aop_details",
                    models.CharField(
                        blank=True,
                        help_text="Provide details of linked AOP content as available (note, more than one AOP link may be provided):<br><ul><li>AOP name and link</li><li>KE name and link</li><li>KER name and link</li><li>AO name and link</li></ul>",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="Select the specific system where the observed effect(s) play a role.",
                        max_length=128,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, help_text="Include any remarks as appropriate."
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "system_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mech_endpoint_system_terms",
                        to="vocab.term",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            bases=("assessment.baseendpoint",),
        ),
        migrations.CreateModel(
            name="TestSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provide a descriptive name for the experiment (e.g. Estrogen Receptor Biding Assay Using Rat Uterine Cytosol)",
                        max_length=255,
                    ),
                ),
                (
                    "test_system_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAC", "bacteria"),
                            ("CFR", "cellular fraction"),
                            ("BTS", "complex biological test system"),
                            ("CLN", "cell line"),
                            ("PCB", "physical / chemical based"),
                            ("PRI", "primary cells"),
                            ("TIS", "tissue"),
                            ("YEA", "yeast"),
                            ("CF", "cell free"),
                            ("OTH", "other, specify"),
                        ],
                        help_text="A test system is any biological, chemical or physical system or a combination thereof used in a study (OECD (2018), Guidance Document on Good In Vitro Method Practices (GIVIMP), OECD Series on Testing and Assessment, No. 286, OECD Publishing, Paris).<p>Examples of physical chemical based test systems: serum protein, peptide, enzyme.<p>Select complex biological test system for example in case of: 3D model, induced pluripotent stem cells, organ on a chip, co-cultures, etc.<p>Select 'other:' in case you don't find a suitable option, for example when your test system is a test kit or a lower in vivo organism.<p>If select “other” enter in free text field “Type of test system “other” remarks”",
                        max_length=3,
                    ),
                ),
                (
                    "test_system_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify the type of test system",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Describe the composition of the test system, e.g. the cells / tissues / proteins / 3D models / induced pluripotent stem cells / organ on chip / co-cultures etc. that were used in the study. When applicable, provide the following information on the genetic modification: - Gene inserted - Gene species (e.g. human, rat, mouse) - Additional information on modification",
                        max_length=255,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CO", "Commercial supplier, specify"),
                            ("NC", "Non-commercial supplier, specify"),
                            ("IH", "In house developed, specify"),
                            ("OT", "Other"),
                        ],
                        help_text="Select the appropriate test system used in the experiment.<p>In case the test system needs to be created in house (e.g. co-cultures, genetic modification), select 'in house developed'",
                        max_length=2,
                        verbose_name="Source/Supplier",
                    ),
                ),
                (
                    "supplier_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide information on the test system source and select if the test system was obtained from a commercial (e.g. cell bank) or non-commercial supplier (e.g. collaborating organisation), or if it was in-house developed or established.",
                        max_length=255,
                        verbose_name="Source/Supplier Remarks",
                    ),
                ),
                (
                    "catalogue_number",
                    models.CharField(
                        blank=True,
                        help_text="Provide the following details for the test system:<br><ul><li>Name</li><li>Source / supplier</li><li>Catalogue / batch number</li><ul>",
                        max_length=255,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Provide the batch/lot number that was used in the study. If unknown, enter “unknown”.",
                        max_length=255,
                        verbose_name="Lot/Batch Number",
                    ),
                ),
                (
                    "genetic_modification",
                    models.CharField(
                        choices=[
                            (
                                "POSTPURCHASE",
                                "genetically modified after purchase, prior to use",
                            ),
                            ("SUPPLIER", "genetically modified by supplier"),
                            ("NA", "not applicable"),
                            ("NOMOD", "not genetically modified"),
                            ("NS", "not specified"),
                        ],
                        help_text="Help text: Select option that best fits - if genetically modified after purchase, prior to use or genetically modified by supplier add additional information on modification in remarks field",
                        max_length=12,
                        verbose_name="Genetic modification of the test system",
                    ),
                ),
                (
                    "genetic_modification_remarks",
                    models.CharField(
                        blank=True,
                        help_text="When applicable, provide the following information on the genetic modification:<ul><li>Gene inserted</li><li>Gene species (e.g. human, rat, mouse)</li></ul>",
                        max_length=255,
                        verbose_name="Genetic modification of the test system remarks",
                    ),
                ),
                (
                    "metabolic_competence",
                    models.CharField(
                        choices=[
                            ("LIM", "limited metabolic activity, specify"),
                            ("MET", "metabolic activity, specify"),
                            ("UNK", "unknown metabolic activity"),
                            (
                                "OTH",
                                "other information on metabolic competence, describe:",
                            ),
                            ("NA", "not applicable"),
                        ],
                        help_text="Select the option that fits best and describe the knowledge about the metabolic competence (i.e. Phase I and/or II biotransformation capacity) of the test system under remarks.<p>For example, when the test system used is  cryopreserved human pooled liver tissue homogenate 9000 g fraction (S9) procured from a commercial supplier, select “metabolic activity, specify” and specify: contains phase I and II metabolic enzymes present in the microsomal (e.g. cytochrome P450s, Flavin-containing monooxygenase, uridine 5’-diphospho-glucuronosyltransferases, carboxylesterases) and cytosolic (e.g. sulfotransferases, glutathione S-transferases, methyltransferases, N-acetyl transferases, xanthine oxidase, aldehyde oxidase) fractions.",
                        max_length=3,
                        verbose_name="Metabolic competence of the test system",
                    ),
                ),
                (
                    "metabolic_competence_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Describe the method underlying metabolic competence of the test system",
                        max_length=255,
                        verbose_name="Metabolic competence of the test system remarks",
                    ),
                ),
                (
                    "medium_buffer",
                    models.CharField(
                        blank=True,
                        help_text="Description of stock medium or buffer including name, source, Lot/batch #, pH (if applicable)",
                        max_length=255,
                        verbose_name="Stock medium/buffer",
                    ),
                ),
                (
                    "serum_supplements",
                    models.CharField(
                        blank=True,
                        help_text="Describe Serum - name, source, lot/batch #, final conc<p>Supplements - name, source, lot/batch #, final conc",
                        max_length=255,
                        verbose_name="Stock medium serum/supplements",
                    ),
                ),
                (
                    "maintenance",
                    models.CharField(
                        blank=True,
                        help_text="Provide information on the routine maintenance of the test system: cell-based: Incubation conditions (humidity, temperature, CO2, etc.) Cell-free: buffer, PH, concentration",
                        max_length=255,
                    ),
                ),
                (
                    "qc_confirmation",
                    models.CharField(
                        choices=[
                            ("ABSMYC", "absence of mycoplasma"),
                            (
                                "STERILITY",
                                "sterility (absence of bacteria, fungi, yeast)",
                            ),
                            ("ABSPATH", "absence of pathological viruses"),
                            ("KARYO", "karyotype stability"),
                            ("RESPPOS", "test system response to positive control"),
                            ("RESPSOLV", "test system response to solvent control"),
                            ("RESPBASE", "test system baseline response"),
                            ("EXPBIO", "test system expression of biological markers"),
                            ("OTHER", "Other, specify"),
                        ],
                        help_text="Select which quality control that was performed on the test system, before or during the generation of results, to confirm the test system was healthy, stable and responsive. If “other” is selected, please specify in the “confirmation of quality control remarks” field",
                        max_length=9,
                        verbose_name="Confirmation of quality control",
                    ),
                ),
                (
                    "qc_confirmation_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Specify the quality control that was performed on the test system, before or during the generation of results, to confirm the test system was healthy, stable and / or responsive.",
                        max_length=255,
                    ),
                ),
                (
                    "controls_used",
                    models.CharField(
                        choices=[
                            ("YS", "yes"),
                            ("NO", "no"),
                            ("NS", "not specified"),
                            ("NR", "not required"),
                        ],
                        help_text='Indicate whether controls / reference substances were used. Enter controls data in the "Controls" block.',
                        max_length=2,
                        verbose_name="Controls / reference items used",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testsystems",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.species",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TestDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("DMSO", "DMSO"),
                            ("ACET", "acetone"),
                            ("ETHA", "ethanol"),
                            ("NREQ", "not required"),
                            ("NSPE", "not specified"),
                            ("SALI", "saline"),
                            ("TREX", "treatment/exposure medium"),
                            ("WATR", "water"),
                            ("OTHR", "other"),
                        ],
                        help_text="If a vehicle or solvent was used, select the relevant item or use 'other:' and specify.",
                        max_length=4,
                        verbose_name="Vehicle/Solvent",
                    ),
                ),
                (
                    "vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about vehicle/solvent.",
                        max_length=255,
                        verbose_name="Vehicle/Solvent: Additional Details",
                    ),
                ),
                (
                    "final_concentration_vehicle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PT1", "0.1%"),
                            ("PT2", "0.2%"),
                            ("PT5", "0.5%"),
                            ("ONE", "1.0%"),
                            ("NS", "Not specified"),
                            ("OTH", "Other, please specify"),
                        ],
                        help_text="Specify the % of vehicle / solvent in the final incubation mixture",
                        max_length=4,
                        verbose_name="Final concentration of the vehicle/solvent",
                    ),
                ),
                (
                    "final_concentration_vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about final concentration.",
                        max_length=255,
                        verbose_name="Final concentration: Additional Details",
                    ),
                ),
                (
                    "final_concentration_vehicle_units",
                    models.CharField(
                        blank=True,
                        choices=[("TODO", "todo/placeholder")],
                        help_text="Specify the vehicle / solvent unit",
                        max_length=4,
                        verbose_name="Final concentration of the vehicle/solvent unit",
                    ),
                ),
                (
                    "concentration_selection",
                    models.CharField(
                        choices=[
                            ("HUEX", "human exposure levels"),
                            (
                                "INDE",
                                "interference with the detection method (e.g. auto fluorescence)",
                            ),
                            (
                                "INTS",
                                "interference with the test system (e.g. cytotoxicity or pH)",
                            ),
                            (
                                "PRIN",
                                "prior information of response (e.g. dose-range finding experiment)",
                            ),
                            ("SOEM", "solubility in exposure medium"),
                            ("SOSO", "solubility in solvent"),
                            ("UNKW", "unknown"),
                            ("OTHR", "other"),
                        ],
                        help_text="For data interpretation it is important to know on what basis the highest concentration tested was selected.<p>Any free text explanation can be given in the adjacent text field to justify the dose level selected.",
                        max_length=4,
                        verbose_name="Concentration selection of the test material",
                    ),
                ),
                (
                    "concentration_selection_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Any free text explanation can be given in the adjacent text field to justify the dose level selected.",
                        verbose_name="Concentration selection of the test material: Additional Details",
                    ),
                ),
                (
                    "concentrations_tested",
                    hawc.apps.common.models.JSONListField(
                        blank=True, help_text="Concentrations tested"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint_detection_method",
                    models.CharField(
                        choices=[
                            ("ANALYTICAL", "analytical method (e.g. LC/MS)"),
                            ("CHROMATO", "chromatography"),
                            ("COMPLEX", "complex detection methods (e.g. imaging)"),
                            ("FLUORO", "fluorescence"),
                            ("LUMIN", "luminescence"),
                            ("RADIOACTIV", "radioactivity"),
                            ("ABSORP", "UV/VIS absorption"),
                            ("OTHER", "other"),
                        ],
                        help_text="Indicate the readout used endpoint detection. Select a detection method type from the picklist and provide the type of instrument (e.g. HPLC, Spectrophotometer, Flow cytometer) or chose 'other: and specify the type or equipment used / analysis performed.",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        choices=[
                            ("SEMI", "Semi or non-quantitative detection methods"),
                            ("QUAN", "quantitative"),
                        ],
                        help_text="Select what type of qualitative method was used and describe the method in the remarks field below.",
                        max_length=4,
                        verbose_name="Details on detection method",
                    ),
                ),
                (
                    "parameters_measured",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("RFU", "RFU"),
                                ("RLU", "RLU"),
                                ("OD", "OD"),
                                (
                                    "CPD",
                                    "Detected compound (e.g. metabolite detection with LC-MS)",
                                ),
                                ("PKA", "Peak area"),
                                ("PKH", "Peak height"),
                                ("FSC", "Forward Scatter"),
                                ("SSC", "Side Scatter"),
                                ("DBI", "Detected biomarker (e.g. with imaging)"),
                                ("OTH", "Other"),
                            ],
                            max_length=3,
                        ),
                        help_text="Describe the unit or output that was provided by the instrument during the measurement. This is the instrument unit of measure of the raw data.",
                        size=None,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide any other relevant information on the detection method not described above",
                        verbose_name="Remarks on detection method",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MechControl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("UNT", "untreated control"),
                            ("POS", "positive control item"),
                            ("REF", "reference item"),
                            ("SVC", "solvent / vehicle control"),
                            ("NEG", "negative control item"),
                            ("OTH", "other"),
                        ],
                        help_text="Select the type of control used to demonstrate the proper performance of the test system and therefore the validity of the experiments. More than one control/reference item can be provided.<p> Solvent / vehicle controls consist of solvent or vehicle alone, without test material, and otherwise treated in the same way as the treatment groups.<p>Untreated controls consist of culture medium without solvent / vehicle or test material, and otherwise treated in the same way as the treatment groups.<p>True negative controls include items (e.g. chemicals) with known lack of activity.<p>Positive controls include items with known activity.<p>Reference items are substances with known activity, used as basis for comparison with the test material.",
                        max_length=3,
                        verbose_name="Type of controls used",
                    ),
                ),
                (
                    "control_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter control type information",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Describe the reference or control item used or provide the name and identifier (e.g. CAS number), source, lot/batch #, purity, and concentration (range) used.",
                        verbose_name="Description of reference and control items used",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide any additional information about control and reference items used.",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechcontrols",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechcontrols",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
