# Generated by Django 5.2.12 on 2026-04-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study", "0013_study_mechanistic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("comments", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_experiments",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mechanistic Experiment",
                "verbose_name_plural": "Mechanistic Experiments",
                "ordering": ("id",),
            },
        ),
    ]
