# Generated by Django 5.2.12 on 2026-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdesign",
            name="final_concentration_vehicle_units",
            field=models.CharField(
                blank=True,
                choices=[("TODO", "todo/placeholder")],
                help_text="Specify the vehicle / solvent unit",
                max_length=4,
                verbose_name="Final concentration of the vehicle/solvent unit",
            ),
        ),
    ]
