# Generated by Django 5.2.12 on 2026-05-29 19:32

import django.db.models.deletion
import hawc.apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdesign",
            name="concentrations_tested",
            field=hawc.apps.common.models.JSONListField(
                blank=True, help_text="Concentrations tested"
            ),
        ),
        migrations.CreateModel(
            name="ExperimentalDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_system_concentration",
                    models.CharField(
                        help_text="Indicate the number of cells or cell density in case of cell lines. Concentration of biological test systems is usually expressed as cell density (amount of cells/cm2 or cells/ml seeded) or confluence (%).",
                        max_length=255,
                        verbose_name="Test system concentration (e.g. cell density)",
                    ),
                ),
                (
                    "passage_number",
                    models.CharField(
                        help_text="Indicate the passage number only in case that the test system is a cell line, report the passage number(s) used.",
                        max_length=255,
                    ),
                ),
                (
                    "exposure_medium_composition",
                    models.CharField(
                        help_text="Indicate what is the composition of the exposure medium where the test system and test material are incubated together to obtain the result. In case serum is present (not recommended) then please indicate the type and %.",
                        max_length=255,
                        verbose_name="Composition of exposure medium",
                    ),
                ),
                (
                    "incubation_conditions",
                    models.CharField(
                        help_text="Indicate cell culture incubation conditions (e.g., temperature, relative humidity, CO2 %, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "exposure_duration",
                    models.CharField(
                        help_text="Indicate the time of incubation / exposure of the test system to the test material.",
                        max_length=255,
                    ),
                ),
                (
                    "administration_frequency",
                    models.CharField(
                        help_text="Indicate the frequency of test material administration.",
                        max_length=255,
                        verbose_name="Frequency of Administration",
                    ),
                ),
                (
                    "technical_replicates",
                    models.CharField(
                        help_text="Indicate the number of replicates included per concentration test item tested.",
                        max_length=255,
                        verbose_name="Number of technical replicates",
                    ),
                ),
                (
                    "biological_replicates",
                    models.CharField(
                        help_text="Indicate the number of biologically independent experiments that were performed. Experiments should be separated in space and time to be considered independent.",
                        max_length=255,
                        verbose_name="Number of biological replicates",
                    ),
                ),
                (
                    "vessel_type",
                    models.CharField(
                        help_text="Indicate the vessel type including size and material (e.g. glass test tube, glass bottom 96 well plate, 384 well polystyrene cell culture plate, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(verbose_name="Remarks on experimental conditions"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experimentaldesigns",
                        to="mechanistic.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
