# Generated by Django 5.2.12 on 2026-06-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0001_initial"),
        ("vocab", "0009_alter_entity_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="effect",
            field=models.CharField(
                blank=True, help_text="Effect, using common-vocabulary", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="effect_subtype",
            field=models.CharField(
                blank=True,
                help_text="Effect subtype, using common-vocabulary",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="effect_subtype_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mech_endpoint_effect_subtype_terms",
                to="vocab.term",
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="effect_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mech_endpoint_effect_terms",
                to="vocab.term",
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="name_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mech_endpoint_name_terms",
                to="vocab.term",
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="organ",
            field=models.CharField(
                blank=True,
                help_text="Relevant organ or tissue",
                max_length=128,
                verbose_name="Organ (and tissue)",
            ),
        ),
        migrations.AddField(
            model_name="mechanisticendpoint",
            name="organ_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mech_endpoint_organ_terms",
                to="vocab.term",
            ),
        ),
    ]
