# Generated by Django 5.2.12 on 2026-04-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0048_delete_job"),
        ("mechanistic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This field is commonly used in visualizations, so consider using a common acronym, e.g., BPA instead of Bisphenol A",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "dsstox",
                    models.ForeignKey(
                        blank=True,
                        help_text='<a rel="noopener noreferrer" target="_blank" href="https://www.epa.gov/chemical-research/distributed-structure-searchable-toxicity-dsstox-database">DssTox</a> substance identifier (recommended). When using an identifier, chemical name and CASRN are standardized using the <a href="https://comptox.epa.gov/dashboard/" rel="noopener noreferrer" target="_blank">DTXSID</a>.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanistic_dsstox",
                        to="assessment.dsstox",
                        verbose_name="DSSTox substance identifier",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals",
                        to="mechanistic.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
