# Generated by Django 5.2.12 on 2026-05-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0048_delete_job"),
        ("mechanistic", "0002_alter_experiment_has_high_throughput_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsystem",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assessment.species"
            ),
        ),
        migrations.CreateModel(
            name="TestDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("DMSO", "DMSO"),
                            ("ACET", "acetone"),
                            ("ETHA", "ethanol"),
                            ("NREQ", "not required"),
                            ("NSPE", "not specified"),
                            ("SALI", "saline"),
                            ("TREX", "treatment/exposure medium"),
                            ("WATR", "water"),
                            ("OTHR", "other"),
                        ],
                        help_text="If a vehicle or solvent was used, select the relevant item or use 'other:' and specify.",
                        max_length=4,
                        verbose_name="Vehicle/Solvent",
                    ),
                ),
                (
                    "vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about vehicle/solvent.",
                        max_length=255,
                    ),
                ),
                (
                    "final_concentration_vehicle",
                    models.CharField(
                        choices=[
                            ("PT1", "0.1%"),
                            ("PT2", "0.2%"),
                            ("PT5", "0.5%"),
                            ("ONE", "1.0%"),
                            ("NS", "Not specified"),
                            ("OTH", "Other, please specify"),
                        ],
                        help_text="Specify the % of vehicle / solvent in the final incubation mixture",
                        max_length=4,
                        verbose_name="Final concentration of the vehicle/solvent",
                    ),
                ),
                (
                    "final_concentration_vehicle_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter additional details about final concentration.",
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testdesigns",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
