# Generated by Django 5.2.12 on 2026-05-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0002_alter_testdesign_concentrations_tested_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentaldesign",
            name="administration_frequency",
            field=models.CharField(
                blank=True,
                help_text="Indicate the frequency of test material administration.",
                max_length=255,
                verbose_name="Frequency of Administration",
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="biological_replicates",
            field=models.CharField(
                blank=True,
                help_text="Indicate the number of biologically independent experiments that were performed. Experiments should be separated in space and time to be considered independent.",
                max_length=255,
                verbose_name="Number of biological replicates",
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="exposure_duration",
            field=models.CharField(
                blank=True,
                help_text="Indicate the time of incubation / exposure of the test system to the test material.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="exposure_medium_composition",
            field=models.CharField(
                blank=True,
                help_text="Indicate what is the composition of the exposure medium where the test system and test material are incubated together to obtain the result. In case serum is present (not recommended) then please indicate the type and %.",
                max_length=255,
                verbose_name="Composition of exposure medium",
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="incubation_conditions",
            field=models.CharField(
                blank=True,
                help_text="Indicate cell culture incubation conditions (e.g., temperature, relative humidity, CO2 %, etc.)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="passage_number",
            field=models.CharField(
                blank=True,
                help_text="Indicate the passage number only in case that the test system is a cell line, report the passage number(s) used.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="remarks",
            field=models.CharField(
                blank=True, verbose_name="Remarks on experimental conditions"
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="technical_replicates",
            field=models.CharField(
                blank=True,
                help_text="Indicate the number of replicates included per concentration test item tested.",
                max_length=255,
                verbose_name="Number of technical replicates",
            ),
        ),
        migrations.AlterField(
            model_name="experimentaldesign",
            name="vessel_type",
            field=models.CharField(
                blank=True,
                help_text="Indicate the vessel type including size and material (e.g. glass test tube, glass bottom 96 well plate, 384 well polystyrene cell culture plate, etc.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DataAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Select whether criteria were used for the validity of the experiment and acceptance of the result. If so, please specify the criteria used to accept or reject an experiment or result.",
                        max_length=2,
                        verbose_name="Validity / acceptance criteria",
                    ),
                ),
                (
                    "validity_remarks",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Validity / acceptance criteria remarks",
                    ),
                ),
                (
                    "cytotoxicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Was the absence of cytotoxicity confirmed? Select the best answer and provide other relevant details in the remarks field. If yes, specify the type of cytotoxicity assay used.",
                        max_length=2,
                        verbose_name="Cytotoxicity assay",
                    ),
                ),
                (
                    "cytotoxicity_remarks",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Cytotoxicity assay remarks",
                    ),
                ),
                (
                    "interference_tests",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Was the absence of interference from test material confirmed? Select yes in case another type of analysis (other than cytotoxicity) was performed that is important for the interpretation of results (e.g. autofluorescence, quenching, etc.). If yes, specify the type of inference test used.",
                        max_length=2,
                    ),
                ),
                (
                    "interference_tests_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "detection_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Did the (object) measurement fall within the detection range for the method used?",
                        max_length=2,
                    ),
                ),
                (
                    "detection_range_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "data_calculation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Is it clear how results are calculated from the raw data?<br>Provide in the remarks field:<br><ul><li>Calculations performed</li><li>Statistical methods used</li><li>Where relevant, provide the method used to exclude outliers</li></ul>",
                        max_length=2,
                        verbose_name="Data calculation and statistics",
                    ),
                ),
                (
                    "data_calculation_remarks",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "evaluation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YS", "Yes, with remarks"),
                            ("NO", "no"),
                            ("NR", "not relevant"),
                            ("UN", "unknown"),
                        ],
                        help_text="Is there criteria available to determine if the test material resulted as active (or not) in the study? If yes, describe the evaluation criteria used in the study to judge if the test material is positive, negative or equivocal. For example:<p>When there is more than 10% binding to the androgen receptor (as expressed in relative light units) for more than two concentrations, the result is ‘positive’.",
                        max_length=2,
                        verbose_name="Evaluation / data interpretation criteria",
                    ),
                ),
                ("evaluation_remarks", models.CharField(blank=True, max_length=2000)),
                (
                    "general_remarks",
                    models.CharField(
                        blank=True,
                        max_length=32768,
                        verbose_name="Remarks on data analysis",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataanalyses",
                        to="mechanistic.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
