# Generated by Django 5.2.12 on 2026-04-14 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0002_chemical"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="cas",
            field=models.CharField(
                blank=True,
                help_text="CAS #",
                max_length=255,
                verbose_name="Chemical identifier (CAS)",
            ),
        ),
        migrations.AddField(
            model_name="chemical",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Enter other descriptive information on the chemical, e.g. technical, nature, relevant P-chem properties.",
                verbose_name="Chemical description comment",
            ),
        ),
        migrations.AddField(
            model_name="chemical",
            name="purity",
            field=models.FloatField(
                blank=True,
                help_text="Provide the % purity or chemical composition",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="% Purity",
            ),
        ),
        migrations.AddField(
            model_name="chemical",
            name="source",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Company and catalog number (if available)",
            ),
        ),
    ]
