# Generated by Django 5.2.12 on 2026-06-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanistic",
            "0003_alter_experimentaldesign_administration_frequency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testsystem",
            name="controls_used",
            field=models.CharField(
                choices=[
                    ("YS", "yes"),
                    ("NO", "no"),
                    ("NS", "not specified"),
                    ("NR", "not required"),
                ],
                default="NS",
                help_text='Indicate whether controls / reference substances were used. Enter controls data in the "Controls" block.',
                max_length=2,
                verbose_name="Controls / reference items used",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("UNT", "untreated control"),
                            ("POS", "positive control item"),
                            ("REF", "reference item"),
                            ("SVC", "solvent / vehicle control"),
                            ("NEG", "negative control item"),
                            ("OTH", "other"),
                        ],
                        help_text="Select the type of control used to demonstrate the proper performance of the test system and therefore the validity of the experiments. More than one control/reference item can be provided.<p> Solvent / vehicle controls consist of solvent or vehicle alone, without test material, and otherwise treated in the same way as the treatment groups.<p>Untreated controls consist of culture medium without solvent / vehicle or test material, and otherwise treated in the same way as the treatment groups.<p>True negative controls include items (e.g. chemicals) with known lack of activity.<p>Positive controls include items with known activity.<p>Reference items are substances with known activity, used as basis for comparison with the test material.",
                        max_length=3,
                        verbose_name="Type of controls used",
                    ),
                ),
                (
                    "control_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Enter control type information",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Describe the reference or control item used or provide the name and identifier (e.g. CAS number), source, lot/batch #, purity, and concentration (range) used.",
                        verbose_name="Description of reference and control items used",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Provide any additional information about control and reference items used.",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="mechanistic.experiment",
                    ),
                ),
                (
                    "test_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="mechanistic.testsystem",
                    ),
                ),
            ],
        ),
    ]
