# Generated by Django 5.2.12 on 2026-06-12 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0004_testsystem_controls_used_control"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="control",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="control",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="control",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
