# Generated by Django 5.2.12 on 2026-06-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0005_alter_control_options_control_created_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Control",
            new_name="MechControl",
        ),
    ]
