# Generated by Django 5.2.12 on 2026-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanistic", "0005_experiment_protocol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chemical",
            old_name="purity",
            new_name="percent_purity",
        ),
        migrations.AddField(
            model_name="chemical",
            name="composition_purity",
            field=models.CharField(
                choices=[
                    ("AG", "Analytical Grade"),
                    ("TG", "Technical Grade"),
                    ("NS", "Purity Not Specified"),
                    ("NA", "Not Applicable (e.g. In Silico Study)"),
                    ("OT", "Other"),
                ],
                default="NA",
                help_text="If detailed information on the purity of the composition is not known, a qualitative statement can be provided in this field, e.g. 'analytical grade' or 'technical grade'. A chemical can be created for a mixture/product. If the chemical refers to the composition of the mixture/product, in the field % purity, specify the chemical composition.",
                max_length=2,
                verbose_name="Composition / Purity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chemical",
            name="composition_purity_other",
            field=models.CharField(
                blank=True,
                help_text="Enter additional details about composition/purity.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="chemical",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Company and catalog number (if available)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="protocol",
            field=models.FileField(
                blank=True, upload_to="mechanistic-experiment-protocols"
            ),
        ),
    ]
