services:

    postgres:
        restart: always
        image: hawc_postgres
        env_file: .env
        volumes:
            - ./data/postgres/data:/var/lib/postgresql/data
            - ./data/postgres/backups:/app/data/backups
        healthcheck:
            test: pg_isready -U $$POSTGRES_USER
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 30s
            start_interval: 5s

    redis:
        restart: always
        image: hawc_redis
        command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
        env_file: .env
        healthcheck:
            test: redis-cli -a $$REDIS_PASSWORD ping
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 30s
            start_interval: 5s

    sync:
        restart: on-failure
        image: hawc_app
        command: /app/bin/sync.sh
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_healthy
                restart: true
        env_file: .env
        volumes:
        - ./data/private:/app/private
        - ./data/public:/app/public

    web:
        restart: always
        image: hawc_app
        command: /app/bin/web.sh
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_healthy
                restart: true
        env_file: .env
        volumes:
            - ./data/private:/app/private
            - ./data/public:/app/public
        healthcheck:
            test: nc -z 0.0.0.0 5000
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 30s
            start_interval: 5s

    workers:
        restart: always
        image: hawc_app
        command: /app/bin/workers.sh
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_healthy
                restart: true
        env_file: .env
        volumes:
            - ./data/private:/app/private
            - ./data/public:/app/public
        healthcheck:
            test: pgrep -f "manage.py db_worker"
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 30s
            start_interval: 5s

    cron:
        restart: always
        image: hawc_app
        command: /app/bin/cron.sh
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis:
                condition: service_healthy
                restart: true
        env_file: .env
        volumes:
            - ./data/private:/app/private
            - ./data/public:/app/public
        healthcheck:
            test: pgrep -f "manage.py crontask"
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 30s
            start_interval: 5s

    nginx:
        image: hawc_nginx
        depends_on:
            web:
                condition: service_healthy
                restart: true
        ports:
            - "0.0.0.0:8000:8000"
        volumes:
            - ./data/public:/app/public
            - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
