# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskofbias',
            options={'ordering': ('content_type', 'object_id', 'metric'), 'verbose_name_plural': 'Risk of Biases'},
        ),
        migrations.AddField(
            model_name='riskofbias',
            name='conflict_resolution',
            field=models.BooleanField(default=False),
        ),
    ]
