# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20160407_1010'),
        ('riskofbias', '0002_auto_20160411_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskofbias',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='study.Study'),
        ),
    ]
