# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0004_auto_20160413_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskofbias',
            options={'ordering': ('metric',), 'verbose_name_plural': 'Risk of Biases'},
        ),
        migrations.AlterUniqueTogether(
            name='riskofbias',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='riskofbias',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='riskofbias',
            name='object_id',
        ),
    ]
