# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('riskofbias', '0008_auto_20160415_1020'),
    ]

    # Provide assessments with a default reviewer number. Can be overridden in Study
    def assignReviewerNumber(apps, schema_editor):
        Assessment = apps.get_model('assessment', 'Assessment')
        RiskOfBiasReviewers = apps.get_model('riskofbias', 'RiskOfBiasReviewers')
        ContentTypes = apps.get_model('contenttypes', 'ContentType')
        ct = ContentTypes.objects.get(app_label='assessment', model='assessment')
        for assessment in Assessment.objects.all():
            rob_review = RiskOfBiasReviewers.objects.create(
                content_type=ct,
                object_id=assessment.pk,
            )

    operations = [
        migrations.CreateModel(
            name='RiskOfBiasReviewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Number of risk of bias reviewers to be required - not counting the conflict resolution reviewer. <br> If more than one reviewer is set, then a conflict resolution reviewer will be required.', verbose_name='Number of Reviewers')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RunPython(
            assignReviewerNumber,
            reverse_code=migrations.RunPython.noop
        )
    ]
