# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0013_auto_20170614_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasscore',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Not reported'), (1, 'Critically deficient'), (2, 'Poor'), (3, 'Adequate'), (4, 'Good'), (0, 'Not applicable')], default=10),
        ),
    ]
