# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0014_auto_20170806_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskofbiasmetric',
            name='hide_description',
            field=models.BooleanField(default=False, help_text='Hide the description on reports?', verbose_name='Hide description?'),
        ),
        migrations.AddField(
            model_name='riskofbiasmetric',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riskofbiasmetric',
            name='use_short_name',
            field=models.BooleanField(default=False, help_text='Use the short name in visualizations?', verbose_name='Use the short name?'),
        ),
    ]
