# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0015_auto_20170809_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBiasMetricAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_one', models.TextField(default='Not reported')),
                ('choice_two', models.TextField(default='Critically deficient')),
                ('choice_three', models.TextField(default='Poor')),
                ('choice_four', models.TextField(default='Adequate')),
                ('choice_five', models.TextField(default='Good')),
                ('choice_six', models.TextField(default='Not applicable')),
                ('symbol_one', models.TextField(default='NR')),
                ('symbol_two', models.TextField(default='--')),
                ('symbol_three', models.TextField(default='-')),
                ('symbol_four', models.TextField(default='+')),
                ('symbol_five', models.TextField(default='++')),
                ('symbol_six', models.TextField(default='-')),
                ('score_one', models.PositiveSmallIntegerField(default=10)),
                ('score_two', models.PositiveSmallIntegerField(default=1)),
                ('score_three', models.PositiveSmallIntegerField(default=2)),
                ('score_four', models.PositiveSmallIntegerField(default=3)),
                ('score_five', models.PositiveSmallIntegerField(default=4)),
                ('score_six', models.PositiveSmallIntegerField(default=0)),
                ('shade_one', models.CharField(default='#FFCC00', max_length=7)),
                ('shade_two', models.CharField(default='#CC3333', max_length=7)),
                ('shade_three', models.CharField(default='#FFCC00', max_length=7)),
                ('shade_four', models.CharField(default='#6FFF00', max_length=7)),
                ('shade_five', models.CharField(default='#00CC00', max_length=7)),
                ('shade_six', models.CharField(default='#FFCC00', max_length=7)),
            ],
        ),
    ]
