# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0018_riskofbiasanswersrecorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='riskofbias.RiskOfBiasMetric'),
        ),
    ]
