# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0019_auto_20171116_1332'),
        ('riskofbias', '0019_auto_20171107_1540'),
    ]

    operations = [
    ]
