# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskofbias', '0022_auto_20171201_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_choice',
            field=models.TextField(default='Not reported', unique=True),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_order',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_score',
            field=models.PositiveSmallIntegerField(default=10, unique=True),
        ),
        migrations.AlterField(
            model_name='riskofbiasmetricanswers',
            name='answer_symbol',
            field=models.TextField(default='NR', unique=True),
        ),
    ]
