# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0010_auto_20170806_1721'),
        ('riskofbias', '0025_heroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroid',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='heroid',
            name='study',
        ),
        migrations.AddField(
            model_name='riskofbias',
            name='identifiers_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heroids', to='lit.Reference'),
        ),
        migrations.DeleteModel(
            name='HeroId',
        ),
    ]
