# Generated by Django 4.2.7 on 2023-11-27 21:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def replace_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")
    Site = apps.get_model("wagtailcore", "Site")
    DocsPage = apps.get_model("docs", "DocsPage")

    # Delete the default homepage
    Page.objects.filter(slug="home").delete()

    # Get content type for docs page model
    content_type = ContentType.objects.get_for_model(DocsPage)

    # Create a new homepage
    homepage = DocsPage.objects.create(
        title="HAWC Documentation",
        draft_title="HAWC Documentation",
        slug="home",
        content_type=content_type,
        path="00010001",
        depth=2,
        numchild=0,
        url_path="/home/",
    )

    # Create a site with the new homepage set as the root
    Site.objects.create(hostname="localhost", root_page=homepage, is_default_site=True)


class Migration(migrations.Migration):
    initial = True

    run_before = [
        ("wagtailcore", "0053_locale_model"),
    ]

    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RunPython(replace_homepage, reverse_code=migrations.RunPython.noop),
    ]
