# Generated by Django 4.2.7 on 2023-11-17 18:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0002_docspage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docspage",
            name="date",
        ),
        migrations.AddField(
            model_name="docsindexpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="docsindexpage",
            name="intro",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="docspage",
            name="intro",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
