# Generated by Django 4.2.7 on 2023-11-22 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0003_remove_docspage_date_docsindexpage_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocsIndexPage",
        ),
    ]
