# Generated by Django 2.2.11 on 2020-08-06 13:29

import django.db.models.deletion
import requests
from django.db import migrations, models


def casrn_to_dtxsid(apps, schema_editor):

    IVChemical = apps.get_model("invitro", "ivchemical")
    DSSTox = apps.get_model("assessment", "dsstox")

    def _create_dsstox(identifier):
        # return an instance of dsstox or None if its not found
        url = f"https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve.json?identifier={identifier}"
        response = requests.get(url)
        response_dict = response.json()["DataRow"]
        if not response_dict["dtxsid"]:
            return None
        else:
            return DSSTox(dtxsid=response_dict["dtxsid"], content=response_dict)

    # we're only looking at ivchemicals with non-empty chemical identifiers
    ivchemicals = IVChemical.objects.exclude(cas="")

    # lists to keep track of changed data for bulk creates/updates
    existing_dtxsids = list(DSSTox.objects.all().values_list("dtxsid", flat=True))
    updated_ivchemicals = list()
    dsstox_entries = list()

    for ivchemical in ivchemicals:
        dsstox = _create_dsstox(ivchemical.cas)
        # if there is an associated DTXSID...
        if dsstox:
            # add it to ivchemical
            ivchemical.dtxsid = dsstox
            # mark the ivchemical as changed
            updated_ivchemicals.append(ivchemical)
            # and create the dsstox entry if it doesn't exist
            if dsstox.dtxsid not in existing_dtxsids:
                dsstox_entries.append(dsstox)
                existing_dtxsids.append(dsstox.dtxsid)

    # create new dsstox entries
    DSSTox.objects.bulk_create(dsstox_entries)
    # update ivchemicals with dtxsid
    IVChemical.objects.bulk_update(updated_ivchemicals, ["dtxsid"])


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_dsstox"),
        ("invitro", "0008_auto_20190416_2003"),
    ]

    operations = [
        migrations.AddField(
            model_name="ivchemical",
            name="dtxsid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ivchemicals",
                to="assessment.DSSTox",
            ),
        ),
        migrations.RunPython(casrn_to_dtxsid, migrations.RunPython.noop),
    ]
