# Generated by Django 3.2.10 on 2022-01-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("epi", "0018_django31"),
        ("study", "0011_auto_20190416_2035"),
        ("assessment", "0030_assessment_epi_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("health_outcome", models.CharField(max_length=128)),
                (
                    "health_outcome_system",
                    models.CharField(
                        blank=True,
                        choices=[("RE", "Reproductive"), ("IM", "Immune")],
                        default="",
                        help_text="If multiple cancer types are present, report all types under Cancer.",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="epiv2.studypopulation",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this health outcome that will help you identify it later.",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="epiv2.studypopulation",
                    ),
                ),
            ],
            options={"verbose_name": "Inclusion/exclusion criteria"},
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals",
                        to="epiv2.studypopulation",
                    ),
                ),
                (
                    "dsstox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.dsstox",
                        verbose_name="DSSTox substance identifier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdjustmentFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=128)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_factors",
                        to="epiv2.studypopulation",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this adjustment factor that will help you identify it later.",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("biomonitoring_matrix", models.CharField(max_length=128)),
                (
                    "measurement_timing",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='If timing is based on something other than age, specify the timing (e.g., start of employment at Factory A). If cross-sectional, enter "cross-sectional"',
                        max_length=128,
                        verbose_name="Timing of exposure measurement",
                    ),
                ),
                (
                    "exposure_route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IH", "Inhalation"),
                            ("OR", "Oral"),
                            ("DE", "Dermal"),
                            ("IU", "In utero"),
                            ("IV", "Intravenous"),
                            ("UK", "Unknown/Total"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("analytic_method", models.CharField(blank=True, default="", max_length=128)),
                ("comments", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="epiv2.studypopulation",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this exposure that will help you identify it later.",
                        max_length=64,
                    ),
                ),
                (
                    "measurement_type",
                    models.ManyToManyField(
                        blank=True,
                        to="epiv2.MeasurementType",
                        verbose_name="Exposure measurement type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExposureLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sub_population",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Sub-population (if relevant)",
                    ),
                ),
                ("central_tendency", models.CharField(max_length=128)),
                (
                    "central_tendency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MED", "Median"),
                            ("GME", "Geometric Mean"),
                            ("POI", "Point"),
                            ("MEA", "Mean"),
                            ("OTH", "Other"),
                        ],
                        default="MED",
                        max_length=128,
                        verbose_name="Central tendency type (median preferred)",
                    ),
                ),
                ("minimum", models.FloatField(blank=True, null=True)),
                ("maximum", models.FloatField(blank=True, null=True)),
                ("percentile25", models.FloatField(blank=True, null=True)),
                ("percentile75", models.FloatField(blank=True, null=True)),
                (
                    "neg_exposure",
                    models.FloatField(
                        blank=True,
                        help_text="e.g., %% below the LOD",
                        null=True,
                        verbose_name="Percent with negligible exposure",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, default="", verbose_name="Exposure level comments"
                    ),
                ),
                (
                    "data_location",
                    models.CharField(
                        blank=True, default="", help_text="e.g., table number", max_length=128
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="epiv2.chemical"
                    ),
                ),
                (
                    "exposure_measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epiv2.exposure",
                    ),
                ),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposure_levels",
                        to="epiv2.studypopulation",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this exposure level that will help you identify it later.",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("n", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "effect_estimate_type",
                    models.CharField(
                        blank=True,
                        choices=[("OR", "Odds Ratio"), ("PC", "Percent Change"), ("OT", "Other")],
                        default="",
                        max_length=128,
                    ),
                ),
                ("effect_estimate", models.FloatField(blank=True, null=True)),
                (
                    "effect_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of the effect estimate with units, including comparison group if applicable",
                        max_length=128,
                        verbose_name="Effect estimate description",
                    ),
                ),
                ("measurement_timing", models.CharField(blank=True, default="", max_length=128)),
                (
                    "exposure_rank",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Rank this comparison group by exposure (lowest exposure group = 1)",
                    ),
                ),
                (
                    "ci_lcl",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confidence Interval LCL"
                    ),
                ),
                (
                    "ci_ucl",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confidence Interval UCL"
                    ),
                ),
                (
                    "sd_or_se",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Standard Deviation or Standard Error"
                    ),
                ),
                (
                    "pvalue",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="p-value"
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Study confidence"
                    ),
                ),
                (
                    "data_location",
                    models.CharField(
                        blank=True, default="", help_text="e.g., table number", max_length=128
                    ),
                ),
                ("statistical_method", models.CharField(blank=True, default="", max_length=128)),
                ("comments", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "adjustment_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="epiv2.adjustmentfactor",
                    ),
                ),
                (
                    "exposure_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="epiv2.exposurelevel"
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        default=1, on_delete=django.db.models.deletion.CASCADE, to="epiv2.outcome"
                    ),
                ),
                (
                    "study_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_extractions",
                        to="epiv2.studypopulation",
                    ),
                ),
                ("sub_population", models.CharField(max_length=64)),
                (
                    "significant",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "No"), (1, "Yes"), (2, "N/A")],
                        default=2,
                        verbose_name="Statistically Significant",
                    ),
                ),
            ],
            options={"verbose_name": "Quantitative data extraction"},
        ),
        migrations.CreateModel(
            name="StudyPopulationV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "study_design",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CO", "Cohort"),
                            ("CC", "Case-control"),
                            ("NC", "Nested case-control"),
                            ("CR", "Case report"),
                            ("SE", "Case series"),
                            ("RT", "Randomized controlled trial"),
                            ("NT", "Non-randomized controlled trial"),
                            ("CS", "Cross-sectional"),
                            ("OT", "Other"),
                        ],
                        default="",
                        max_length=128,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GP", "General population"),
                            ("OC", "Occupational"),
                            ("OT", "Other"),
                        ],
                        default="",
                        max_length=128,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("U", "Not reported"),
                            ("M", "Male"),
                            ("F", "Female"),
                            ("B", "Male and Female"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Breifly describe the study population (e.g., Women undergoing fertility treatment).",
                        max_length=128,
                        verbose_name="Population Summary",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Other geographic information",
                    ),
                ),
                (
                    "participant_n",
                    models.PositiveIntegerField(
                        help_text="Enter the total number of participants enrolled in the study (after exclusions).\nNote: Sample size for specific result can be extracted in qualitative data extraction",
                        verbose_name="Overall study population N",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "age_profile",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Select all that apply. Note: do not select "Pregnant women" if pregnant women are only included as part of a general population sample',
                        to="epiv2.AgeProfile",
                        verbose_name="Population age category",
                    ),
                ),
                ("countries", models.ManyToManyField(blank=True, to="epi.Country")),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_populations_v2",
                        to="study.study",
                    ),
                ),
                (
                    "age_description",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Population age details"
                    ),
                ),
                (
                    "study_name",
                    models.CharField(
                        blank=True,
                        help_text="Typically available for cohorts. Abbreviations provided in the paper are fine",
                        max_length=64,
                        null=True,
                        verbose_name="Study name (if applicable",
                    ),
                ),
                (
                    "years",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Year(s) of data collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Population",
                "verbose_name_plural": "Study Populations",
            },
        ),
    ]
