# Generated by Django 3.2.13 on 2022-04-28 14:26

import django.db.models.deletion
from django.db import migrations, models

import hawc.apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="design",
            old_name="years",
            new_name="years_enrolled",
        ),
        migrations.RemoveField(
            model_name="dataextraction",
            name="adjustment_factor",
        ),
        migrations.RemoveField(
            model_name="exposure",
            name="analytic_method",
        ),
        migrations.AddField(
            model_name="adjustmentfactor",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dataextraction",
            name="exposure_transform",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="dataextraction",
            name="factors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epiv2.adjustmentfactor",
                verbose_name="Adjustment factors",
            ),
        ),
        migrations.AddField(
            model_name="dataextraction",
            name="outcome_transform",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="design",
            name="susceptibility",
            field=models.TextField(blank=True, verbose_name="Susceptibility"),
        ),
        migrations.AddField(
            model_name="design",
            name="years_followup",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Year(s) or length of follow-up"
            ),
        ),
        migrations.AddField(
            model_name="exposure",
            name="measurement_method",
            field=models.TextField(blank=True, verbose_name="Exposure measurement method"),
        ),
        migrations.AlterField(
            model_name="adjustmentfactor",
            name="description",
            field=models.CharField(help_text="Comma separated list", max_length=256),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="ci_lcl",
            field=models.FloatField(blank=True, null=True, verbose_name="Lower bound"),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                ],
                default="P95",
                max_length=3,
                verbose_name="Lower/upper bound type",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="ci_ucl",
            field=models.FloatField(blank=True, null=True, verbose_name="Upper bound"),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="variance_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "---"),
                    (1, "SD"),
                    (2, "SE"),
                    (3, "SEM"),
                    (4, "GSD"),
                    (5, "IQR (interquartile range)"),
                    (6, "other"),
                ],
                default=0,
                verbose_name="Type of variance estimate",
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_timing",
            field=models.CharField(
                blank=True,
                help_text='If timing is based on something other than age, specify the timing (e.g., start of employment at Factory A). If cross-sectional, enter "cross-sectional"',
                max_length=256,
                verbose_name="Timing of exposure measurement",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_lcl",
            field=hawc.apps.common.models.NumericTextField(
                blank=True, default="", max_length=16, verbose_name="Lower bound"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                ],
                default="Rng",
                max_length=3,
                verbose_name="Lower/upper bound type",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_ucl",
            field=hawc.apps.common.models.NumericTextField(
                blank=True, default="", max_length=16, verbose_name="Upper bound"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="neg_exposure",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., % below the LOD",
                max_length=64,
                verbose_name="Percent with negligible exposure",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="percentile_25",
            field=hawc.apps.common.models.NumericTextField(
                blank=True, default="", max_length=16, verbose_name="25th Percentile"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="percentile_75",
            field=hawc.apps.common.models.NumericTextField(
                blank=True, default="", max_length=16, verbose_name="75th Percentile"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="variance_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "---"),
                    (1, "SD"),
                    (2, "SE"),
                    (3, "SEM"),
                    (4, "GSD"),
                    (5, "IQR (interquartile range)"),
                    (6, "other"),
                ],
                default=0,
                verbose_name="Type of variance estimate",
            ),
        ),
    ]
