# Generated by Django 4.2.3 on 2023-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epiv2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="study_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Study name assigned by authors. Typically available for cohorts.",
                max_length=128,
                verbose_name="Study name (if applicable)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="units",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
    ]
