# Generated by Django 3.2.13 on 2022-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextraction',
            name='units',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='biomonitoring_matrix',
            field=models.CharField(blank=True, choices=[('BLP', 'Blood (portion: Plasma)'), ('BLW', 'Blood (portion: Whole blood)'), ('BLS', 'Blood (portion: Serum)'), ('UR', 'Urine'), ('TE', 'Teeth'), ('NL', 'Nails'), ('HR', 'Hair'), ('SA', 'Saliva'), ('BM', 'Breast milk'), ('SE', 'Semen'), ('FC', 'Feces'), ('CF', 'Cerebrospinal fluid'), ('EB', 'Exhaled breath'), ('OT', 'Other')], max_length=3),
        ),
    ]
