# Generated by Django 3.2.13 on 2022-07-08 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0002_auto_20220708_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextraction",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("NA", "---"),
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                    ("Oth", "Other"),
                ],
                default="P95",
                max_length=3,
                verbose_name="Lower/upper bound type",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="age_profile",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AD", "Adults"),
                        ("CH", "Children and adolescents <18 yrs"),
                        ("PW", "Pregnant women"),
                        ("OT", "Other"),
                    ],
                    max_length=2,
                ),
                help_text='Select all that apply. Note: do not select "Pregnant women" if pregnant women are only included as part of a general population sample',
                size=None,
                verbose_name="Population age category",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="source",
            field=models.CharField(
                choices=[("GP", "General population"), ("OC", "Occupational"), ("OT", "Other")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                help_text='Select the most appropriate type from the list. If a study includes multiples exposure measurement types but they are analyzed with outcomes separately, create a separate entry for each. If more than one type are combined for analysis with an outcome, you can select multiple options from the list. "Occupational" should be used when the exposure is based on job duties, etc. (i.e., not occupational exposure measured by biomarkers or air).',
                size=None,
                verbose_name="Exposure measurement types",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("NA", "---"),
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                    ("Oth", "Other"),
                ],
                default="NA",
                max_length=3,
                verbose_name="Lower/upper interval type",
            ),
        ),
    ]
