# Generated by Django 3.2.13 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0002_auto_20220426_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="susceptibility",
            field=models.TextField(blank=True, verbose_name="Susceptibility"),
        ),
    ]
