# Generated by Django 3.2.12 on 2022-02-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0002_design_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposure",
            name="measurement_type",
            field=models.ManyToManyField(
                to="epiv2.MeasurementType", verbose_name="Exposure measurement type"
            ),
        ),
    ]
