# Generated by Django 4.2.3 on 2023-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epiv2", "0002_no_null_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataextraction",
            name="adverse_direction",
            field=models.CharField(
                choices=[
                    ("unspecified", "Unspecified"),
                    ("unknown", "Unknown"),
                    ("up", "⬆"),
                    ("down", "⬇"),
                    ("both", "⬆⬇"),
                ],
                default="unspecified",
                help_text=" Select the direction of effect that would be adverse if observed. This does not mean that the actual results were adverse or were in that direction; this is a guide for interpretation of the results. For example, for a given neuropsychological score, is an increase interpreted as a better or worse score? For some outcomes (e.g., thyroid hormones), an association in either direction could conceivably be adverse.",
                max_length=12,
                verbose_name="Adverse direction",
            ),
        ),
    ]
