# Generated by Django 3.2.10 on 2022-01-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0002_rename_studypopulation_studypopulationv2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studypopulationv2',
            options={'verbose_name': 'Study Population', 'verbose_name_plural': 'Study Populations'},
        ),
    ]
