# Generated by Django 3.2.13 on 2022-05-03 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0002_auto_20220428_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextraction",
            name="effect_estimate_type",
            field=models.CharField(
                choices=[
                    ("OR", "Odds Ratio (OR)"),
                    ("RR", "Relative Risk Ratio (RR)"),
                    ("AR", "Absolute Risk %"),
                    ("B", "Regression coefficient (β)"),
                    ("SMR", "Standardized Mortality Ratio (SMR)"),
                    ("SIR", "Standardized Incidence Ratio (SIR)"),
                    ("IRR", "Incidence Risk Ratio (IRR)"),
                    ("ARR", "Absolute Risk Reduction/ Risk difference (ARR or RD)"),
                    ("HR", "Hazard Ratio (HR)"),
                    ("CM", "Comparison of Means"),
                    ("SCC", "Spearman's Correlation Coefficient"),
                    ("PC", "Percent change"),
                    ("MD", "Mean difference"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                help_text="Select all that apply.",
                size=None,
                verbose_name="Exposure measurement types",
            ),
        ),
    ]
