# Generated by Django 3.2.13 on 2022-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0003_auto_20220503_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataextraction",
            name="group",
            field=models.CharField(
                blank=True,
                help_text='If a set of results are linked (e.g., results for categories of exposure), each one is entered as a separate entry in the form. This field should be used to link the results. All linked results should have the same value for this field, and it should be unique to those results. The text can be descriptive (e.g., "Quartiles for PFNA and Asthma incidence") or a dummy variable ("Group 1").',
                max_length=128,
                verbose_name="Results group",
            ),
        ),
    ]
