# Generated by Django 3.2.10 on 2022-01-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0018_django31"),
        ("epiv2", "0003_alter_studypopulationv2_options"),
    ]

    operations = [
        migrations.DeleteModel(name="Country",),
        migrations.AlterField(
            model_name="studypopulationv2",
            name="countries",
            field=models.ManyToManyField(blank=True, to="epi.Country"),
        ),
    ]
