# Generated by Django 3.2.13 on 2022-05-04 23:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import hawc.apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0004_dataextraction_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustmentfactor",
            name="description",
            field=models.CharField(
                help_text='Enter the list of covariates in the model, separated by commas. These can be brief and ideally entered uniformly across studies when possible. Additional detail can be added in the comments or in study evaluation (e.g., enter "smoking" for consistency instead of "pack-years")',
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="adjustmentfactor",
            name="name",
            field=models.CharField(
                help_text='A unique name for this adjustment set that will help you identify it later. It may be descriptive or a dummy variable ("A").',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="confidence",
            field=models.CharField(
                blank=True,
                help_text="Enter the overall study confidence rating for the specific endpoint being extracted",
                max_length=128,
                verbose_name="Study confidence",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="effect_description",
            field=models.TextField(
                blank=True,
                help_text="Description of the effect estimate with units, including the comparison being made (e.g., beta for IQR increase, OR for Q2 vs Q1)",
                verbose_name="Effect estimate description",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="exposure_level",
            field=models.ForeignKey(
                help_text="Select from exposure levels entered above",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposure_levels",
                to="epiv2.exposurelevel",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="exposure_rank",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="If a set of results are linked, use this field to order them (helpful for sorting in visualizations). Rank the comparison groups in the order you would want them to appear (e.g., lowest exposure group=1).",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="factors",
            field=models.ForeignKey(
                blank=True,
                help_text="Select from adjustment sets entered above",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epiv2.adjustmentfactor",
                verbose_name="Adjustment factors",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="outcome",
            field=models.ForeignKey(
                help_text="Select from endpoints entered above",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="epiv2.outcome",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="outcome_measurement_timing",
            field=models.CharField(
                blank=True,
                help_text='Enter age or other timing (e.g., X years follow-up) for measurement of outcome. If cross-sectional, enter "cross-sectional".',
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="statistical_method",
            field=models.TextField(
                blank=True,
                help_text="Briefly describe the statistical analysis method (e.g., logistic regression).",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="sub_population",
            field=models.CharField(
                blank=True,
                help_text="Specify if the result is specific to a sub-group within the study population. Leave blank if the result applies to the full population.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="participant_n",
            field=models.PositiveIntegerField(
                help_text="Enter the total number of participants enrolled in the study (after exclusions). Note: Sample size for specific result can be extracted in qualitative data extraction",
                verbose_name="Overall study population N",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="study_design",
            field=models.CharField(
                choices=[
                    ("CO", "Cohort"),
                    ("CC", "Case-control"),
                    ("NC", "Nested case-control"),
                    ("CR", "Case report"),
                    ("SE", "Case series"),
                    ("RT", "Randomized controlled trial"),
                    ("NT", "Non-randomized controlled trial"),
                    ("CS", "Cross-sectional"),
                    ("EC", "Ecological"),
                    ("OT", "Other"),
                ],
                help_text='Select the most appropriate design from the list. If more than one study design applies (e.g., a cohort with cross-sectional analyses of baseline measures), can either a) select one design ("cohort") and clarify different timing in remaining extraction or b) select "other" and provide details in comments.',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="study_name",
            field=models.CharField(
                blank=True,
                help_text="Study name assigned by authors. Typically available for cohorts.",
                max_length=128,
                null=True,
                verbose_name="Study name (if applicable)",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="summary",
            field=models.CharField(
                help_text="Briefly describe the study population. Try to capture anything outside a typical general population samples (e.g.,people with a specific health condition, specific environments [e.g., assisted living facility, farmers, etc.], exposure scenario, etc. This field may be used in visualizations as a summary of the study, so it is important to be consistent within the assessment.",
                max_length=128,
                verbose_name="Population Summary",
            ),
        ),
        migrations.AlterField(
            model_name="design",
            name="susceptibility",
            field=models.TextField(
                blank=True,
                help_text="Note whether the study presents information for potentially susceptible or vulnerable populations or sub-populations, such as pregnant women or residents of environmental justice communities.",
                verbose_name="Susceptibility",
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="exposure_route",
            field=models.CharField(
                choices=[
                    ("IH", "Inhalation"),
                    ("OR", "Oral"),
                    ("DE", "Dermal"),
                    ("IU", "In utero"),
                    ("IV", "Intravenous"),
                    ("UK", "Unknown/Total"),
                ],
                default="UK",
                help_text='Select the most appropriate route. In most cases, biomarkers will be "Unknown/Total" unless a clear exposure source is known.',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_method",
            field=models.TextField(
                blank=True,
                help_text="Briefly state the method used to measure exposure (e.g., laboratory analytic method, job exposure matrix, etc.)",
                verbose_name="Exposure measurement method",
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_timing",
            field=models.CharField(
                blank=True,
                help_text='Enter age or other timing (e.g., start of employment, baseline). If cross-sectional, enter "cross-sectional".',
                max_length=256,
                verbose_name="Timing of exposure measurement",
            ),
        ),
        migrations.AlterField(
            model_name="exposure",
            name="measurement_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                help_text='Select the most appropriate type from the list. If a study includes multiples exposure measurement types but they are analyzed with outcomes separately, create a separate entry for each. If more than one type are combined for analysis with an outcome, you can select multiple options from the list. "Occupational" should be used when the exposure is based on job duties, etc. (i.e., not occupational exposure measured by biomarkers or air).',
                size=None,
                verbose_name="Exposure measurement types",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="chemical",
            field=models.ForeignKey(
                help_text="Select from chemicals entered above.",
                on_delete=django.db.models.deletion.CASCADE,
                to="epiv2.chemical",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_lcl",
            field=hawc.apps.common.models.NumericTextField(
                blank=True,
                help_text="Lower value of whichever range is selected in Lower/Upper interval type. Non-numeric values can be used if necessary, but should be limited to <, ≤, ≥, >, LOD, LOQ.",
                max_length=16,
                verbose_name="Lower interval",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                ],
                default="Rng",
                max_length=3,
                verbose_name="Lower/upper interval type",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_ucl",
            field=hawc.apps.common.models.NumericTextField(
                blank=True,
                help_text="Upper value of whichever range is selected in Lower/Upper interval type. Non-numeric values can be used if necessary, but should be limited to <, ≤, ≥, >, LOD, LOQ.",
                max_length=16,
                verbose_name="Upper interval",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="exposure_measurement",
            field=models.ForeignKey(
                help_text="Select from exposure measurement entered above.",
                on_delete=django.db.models.deletion.CASCADE,
                to="epiv2.exposure",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="neg_exposure",
            field=models.CharField(
                blank=True,
                help_text="Enter the percent of the population without measureable exposure. For biomarkers and other lab results, this will generally be the percent below the LOD or LOQ. Occupational studies may report the percent unexposed. The field is free text so elaboration on the meaning of the number can be provided.",
                max_length=64,
                verbose_name="Percent with negligible exposure",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="percentile_25",
            field=hawc.apps.common.models.NumericTextField(
                blank=True,
                help_text="Non-numeric values can be used if necessary, but should be limited to <, ≤, ≥, >, LOD, LOQ.",
                max_length=16,
                verbose_name="25th Percentile",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="percentile_75",
            field=hawc.apps.common.models.NumericTextField(
                blank=True,
                help_text="Non-numeric values can be used if necessary, but should be limited to <, ≤, ≥, >, LOD, LOQ.",
                max_length=16,
                verbose_name="75th Percentile",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="sub_population",
            field=models.CharField(
                blank=True,
                help_text="Specify if the exposure levels are reported for a sub-group within the study population (e.g., by case or exposure status, sex, etc.)",
                max_length=128,
                verbose_name="Sub-population",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="variance_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "---"),
                    (1, "SD"),
                    (2, "SE"),
                    (3, "SEM"),
                    (4, "GSD"),
                    (5, "IQR (interquartile range)"),
                    (6, "other"),
                ],
                default=0,
                verbose_name="Specify which measure of variation was reported from list",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="endpoint",
            field=models.CharField(
                help_text="A unique name for the health effect being measured. The endpoint is generally more specific than the outcome (e.g., cholesterol, asthma within the previous year). Use controlled vocabulary when available.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="health_outcome",
            field=models.CharField(
                help_text="The outcome is generally broader than the endpoint (e.g., serum lipids, asthma). However, if there is not a finer categorization, they may be the same. Use controlled vocabulary when available.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="health_outcome_system",
            field=models.CharField(
                choices=[
                    ("CA", "Cancer"),
                    ("CV", "Cardiovascular"),
                    ("DE", "Dermal"),
                    ("DV", "Developmental"),
                    ("EN", "Endocrine"),
                    ("GI", "Gastrointestinal"),
                    ("HM", "Hematologic"),
                    ("HP", "Hepatic"),
                    ("IM", "Immune"),
                    ("MT", "Metabolic"),
                    ("MS", "Multi-System"),
                    ("MU", "Musculoskeletal"),
                    ("NV", "Nervous"),
                    ("OC", "Ocular"),
                    ("RP", "Reproductive"),
                    ("RS", "Respiratory"),
                    ("UR", "Urinary"),
                    ("WB", "Whole Body"),
                    ("OT", "Other"),
                ],
                help_text="Select the system from the drop down. Use controlled vocabulary when available. If multiple cancer types are present, report all types under Cancer.",
                max_length=2,
            ),
        ),
    ]
