# Generated by Django 3.2.10 on 2022-01-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0004_auto_20220112_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studypopulationv2',
            name='race',
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epiv2.outcome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposurelevel',
            name='central_tendency_type',
            field=models.CharField(blank=True, choices=[('MED', 'Median'), ('GME', 'Geometric Mean'), ('POI', 'Point'), ('MEA', 'Mean'), ('OTH', 'Other')], default='MED', max_length=128, verbose_name='Central tendency type (median preferred)'),
        ),
        migrations.AlterField(
            model_name='studypopulationv2',
            name='age_description',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Population age details'),
            preserve_default=False,
        ),
    ]
