# Generated by Django 3.2.11 on 2022-02-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0002_auto_20220223_1200"),
        ("epiv2", "0004_alter_exposure_biomonitoring_matrix"),
    ]

    operations = []
