# Generated by Django 3.2.13 on 2022-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0004_alter_exposure_measurement_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='measurement_timing',
            field=models.CharField(help_text='If timing is based on something other than age, specify the timing (e.g., start of employment at Factory A). If cross-sectional, enter "cross-sectional"', max_length=256, verbose_name='Timing of exposure measurement'),
        ),
    ]
