# Generated by Django 3.2.10 on 2022-01-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0004_auto_20220110_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="studypopulation",
            name="race",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Population race/ethnicity"
            ),
        ),
    ]
