# Generated by Django 3.2.13 on 2022-04-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0005_alter_exposure_measurement_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposure',
            name='analytic_method',
        ),
        migrations.AddField(
            model_name='exposure',
            name='measurement_method',
            field=models.TextField(blank=True, verbose_name='Exposure measurement method'),
        ),
    ]
