# Generated by Django 3.2.14 on 2022-07-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0005_alter_dataextraction_effect_estimate_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outcome",
            old_name="health_outcome",
            new_name="effect",
        ),
        migrations.RenameField(
            model_name="outcome",
            old_name="health_outcome_system",
            new_name="system",
        ),
    ]
