# Generated by Django 3.2.10 on 2022-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0006_auto_20220113_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='analytic_method',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposure',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposure',
            name='exposure_route',
            field=models.CharField(blank=True, choices=[('IH', 'Inhalation'), ('OR', 'Oral'), ('DE', 'Dermal'), ('IU', 'In utero'), ('IV', 'Intravenous'), ('UK', 'Unknown/Total')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposure',
            name='measurement_timing',
            field=models.CharField(blank=True, default='', help_text='If timing is based on something other than age, specify the timing (e.g., start of employment at Factory A). If cross-sectional, enter "cross-sectional"', max_length=128, verbose_name='Timing of exposure measurement'),
            preserve_default=False,
        ),
    ]
