# Generated by Django 3.2.14 on 2022-07-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0006_auto_20220715_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcome",
            name="effect_detail",
            field=models.CharField(
                blank=True,
                help_text="Optional. If additional specification to the Effect is needed, it can be entered here (e.g., IQ).",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="effect",
            field=models.CharField(
                help_text="The health effect of interest. Effect is generally broader than the Endpoint/Outcome and may represent multiple endpoints (e.g., Serum lipids, Asthma, Cognition). However, if there is not a finer categorization, they may be the same. Use controlled vocabulary when available.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="endpoint",
            field=models.CharField(
                help_text="A unique name for the specific endpoint/outcome being measured. The endpoint is generally more specific than the effect (e.g., total cholesterol, incident asthma within the previous year, WISC-IV full scale). Use controlled vocabulary when available.",
                max_length=128,
                verbose_name="Endpoint/Outcome",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="system",
            field=models.CharField(
                choices=[
                    ("CA", "Cancer"),
                    ("CV", "Cardiovascular"),
                    ("DE", "Dermal"),
                    ("DV", "Developmental"),
                    ("EN", "Endocrine"),
                    ("GI", "Gastrointestinal"),
                    ("HM", "Hematologic"),
                    ("HP", "Hepatic"),
                    ("IM", "Immune"),
                    ("MT", "Metabolic"),
                    ("MS", "Multi-System"),
                    ("MU", "Musculoskeletal"),
                    ("NV", "Nervous"),
                    ("OC", "Ocular"),
                    ("RP", "Reproductive"),
                    ("RS", "Respiratory"),
                    ("UR", "Urinary"),
                    ("WB", "Whole Body"),
                    ("OT", "Other"),
                ],
                help_text="Select the most relevant system from the drop down menu. If more than one system is applicable refer to assessment team instructions. Use controlled vocabulary when available.",
                max_length=2,
            ),
        ),
    ]
