# Generated by Django 3.2.10 on 2022-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0006_auto_20220110_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextraction',
            name='sub_population',
            field=models.CharField(default='Full population', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='effect_description',
            field=models.CharField(blank=True, help_text='Description of the effect estimate with units, including comparison group if applicable', max_length=128, null=True, verbose_name='Effect estimate description'),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='effect_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='effect_estimate_type',
            field=models.CharField(blank=True, choices=[('OR', 'Odds Ratio'), ('OT', 'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='health_outcome_system',
            field=models.CharField(blank=True, choices=[('RE', 'Reproductive'), ('IM', 'Immune')], help_text='If multiple cancer types are present, report all types under Cancer.', max_length=128, null=True),
        ),
    ]
