# Generated by Django 3.2.14 on 2022-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0007_auto_20220715_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextraction",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("NA", "N/A"),
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                    ("Oth", "Other"),
                ],
                default="P95",
                max_length=3,
                verbose_name="Lower/upper bound type",
            ),
        ),
        migrations.AlterField(
            model_name="dataextraction",
            name="variance_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "N/A"),
                    (1, "SD"),
                    (2, "SE"),
                    (3, "SEM"),
                    (4, "GSD"),
                    (5, "IQR (interquartile range)"),
                    (6, "other"),
                ],
                default=0,
                help_text="Specify which measure of variation was reported from list",
                verbose_name="Type of variance estimate",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="ci_type",
            field=models.CharField(
                choices=[
                    ("NA", "N/A"),
                    ("Rng", "Range [min, max]"),
                    ("P90", "10th/90th percentile"),
                    ("P95", "5th/95th percentile"),
                    ("P99", "1st/99th percentile"),
                    ("Oth", "Other"),
                ],
                default="NA",
                max_length=3,
                verbose_name="Lower/upper interval type",
            ),
        ),
        migrations.AlterField(
            model_name="exposurelevel",
            name="variance_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "N/A"),
                    (1, "SD"),
                    (2, "SE"),
                    (3, "SEM"),
                    (4, "GSD"),
                    (5, "IQR (interquartile range)"),
                    (6, "other"),
                ],
                default=0,
                help_text="Specify which measure of variation was reported from list",
                verbose_name="Type of variance estimate",
            ),
        ),
    ]
