# Generated by Django 3.2.10 on 2022-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0007_auto_20220113_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentfactor',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposurelevel',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Exposure level comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposurelevel',
            name='data_location',
            field=models.CharField(blank=True, default='', help_text='e.g., table number', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposurelevel',
            name='sub_population',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Sub-population (if relevant)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outcome',
            name='health_outcome_system',
            field=models.CharField(blank=True, choices=[('RE', 'Reproductive'), ('IM', 'Immune')], default='', help_text='If multiple cancer types are present, report all types under Cancer.', max_length=128),
            preserve_default=False,
        ),
    ]
