# Generated by Django 3.2.13 on 2022-04-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0007_auto_20220426_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposurelevel",
            name="neg_exposure",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., % below the LOD",
                max_length=64,
                verbose_name="Percent with negligible exposure",
            ),
            preserve_default=False,
        ),
    ]
