# Generated by Django 3.2.13 on 2022-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0008_alter_exposurelevel_neg_exposure"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmentfactor",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
