# Generated by Django 3.2.10 on 2022-01-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0008_auto_20220113_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='exposure_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epiv2.exposurelevel'),
        ),
    ]
