# Generated by Django 3.2.10 on 2022-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0008_alter_exposurelevel_central_tendency_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextraction",
            name="effect_estimate_type",
            field=models.CharField(
                blank=True,
                choices=[("OR", "Odds Ratio"), ("PC", "Percent Change"), ("OT", "Other")],
                max_length=128,
                null=True,
            ),
        ),
    ]
