# Generated by Django 3.2.13 on 2022-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0009_adjustmentfactor_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustmentfactor",
            name="description",
            field=models.CharField(help_text="Comma separated list", max_length=256),
        ),
    ]
