# Generated by Django 3.2.10 on 2022-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0009_alter_dataextraction_exposure_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='effect_description',
            field=models.CharField(blank=True, default='', help_text='Description of the effect estimate with units, including comparison group if applicable', max_length=128, verbose_name='Effect estimate description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='effect_estimate_type',
            field=models.CharField(blank=True, choices=[('OR', 'Odds Ratio'), ('PC', 'Percent Change'), ('OT', 'Other')], default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='measurement_timing',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
