# Generated by Django 3.2.10 on 2022-01-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0010_auto_20220113_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='pvalue',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='p-value'),
            preserve_default=False,
        ),
    ]
