# Generated by Django 3.2.13 on 2022-04-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epiv2", "0011_auto_20220426_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextraction",
            name="factors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epiv2.adjustmentfactor",
                verbose_name="Adjustment factors",
            ),
        ),
    ]
