# Generated by Django 3.2.10 on 2022-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0011_alter_dataextraction_pvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Study confidence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='data_location',
            field=models.CharField(blank=True, default='', help_text='e.g., table number', max_length=128),
            preserve_default=False,
        ),
    ]
