# Generated by Django 3.2.10 on 2022-01-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0012_auto_20220113_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='statistical_method',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
