# Generated by Django 3.2.10 on 2022-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0013_auto_20220113_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
