# Generated by Django 3.2.10 on 2022-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0014_alter_dataextraction_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextraction',
            name='exposure_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rank this comparison group by exposure (lowest exposure group = 1)'),
        ),
    ]
