# Generated by Django 3.2.10 on 2022-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0015_alter_dataextraction_exposure_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataextraction',
            name='significant',
        ),
    ]
