# Generated by Django 3.2.10 on 2022-01-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epiv2', '0016_remove_dataextraction_significant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextraction',
            name='significant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'N/A')], default=2, verbose_name='Statistically Significant'),
        ),
    ]
