# Generated by Django 3.2.10 on 2022-01-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0030_assessment_epi_version'),
        ('epiv2', '0017_dataextraction_significant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='dsstox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.dsstox', verbose_name='DSSTox substance identifier'),
        ),
    ]
