# Generated by Django 4.2.4 on 2023-09-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0020_userreferencetag_user_reference_tag"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("assessment", "0037_delete_blog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("udf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="udf_tag_bindings",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="udf_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="udf.userdefinedform",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="udf_forms",
                        to="lit.referencefiltertag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["assessment", "tag"], name="udf_tagbind_assessm_b423ed_idx"
                    )
                ],
                "unique_together": {("assessment", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ModelBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="udf_bindings",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="udf_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="udf.userdefinedform",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["assessment", "content_type"], name="udf_modelbi_assessm_080685_idx"
                    )
                ],
                "unique_together": {("assessment", "content_type")},
            },
        ),
    ]
