# Generated by Django 5.0.1 on 2024-01-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0023_referencetags_reference_tag_and_more"),
        ("udf", "0003_modeludfcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagUDFContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_tag_contents",
                        to="lit.reference",
                    ),
                ),
                (
                    "tag_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="udf.tagbinding"
                    ),
                ),
            ],
            options={
                "unique_together": {("reference", "tag_binding")},
            },
        ),
    ]
