# Generated by Django 4.2.4 on 2023-10-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lit", "0020_userreferencetag_user_reference_tag"),
        ("udf", "0003_modeludfcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagUDFContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_tag_contents",
                        to="lit.reference",
                    ),
                ),
                (
                    "tag_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="udf.tagbinding"
                    ),
                ),
            ],
        ),
    ]
