# Generated by Django 5.0.1 on 2024-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0037_delete_blog"),
        ("udf", "0004_tagudfcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdefinedform",
            name="assessments",
            field=models.ManyToManyField(
                blank=True, related_name="udf_forms", to="assessment.assessment"
            ),
        ),
        migrations.AddField(
            model_name="userdefinedform",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
