# Generated by Django 5.0.1 on 2024-02-13 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0037_delete_blog"),
        ("udf", "0004_tagudfcontent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdefinedform",
            name="assessments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users in selected assessments will be able to apply this form to models in their assessment.",
                related_name="udf_forms",
                to="assessment.assessment",
            ),
        ),
        migrations.AddField(
            model_name="userdefinedform",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Published UDFs are visible for all users and usable for all assessments.",
            ),
        ),
        migrations.AlterField(
            model_name="userdefinedform",
            name="deprecated",
            field=models.BooleanField(
                default=False, help_text="Select if this UDF should no longer be used."
            ),
        ),
        migrations.AlterField(
            model_name="userdefinedform",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editors have the ability to update this form, and can use it for any of their assessments.",
                related_name="udf_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userdefinedform",
            name="schema",
            field=models.JSONField(
                help_text="The schema defines the structure and behavior of the UDF. It is composed of JSON that specifies fields and conditional logic. Contact us for help defining a schema for your UDF."
            ),
        ),
    ]
