# Generated by Django 5.0.6 on 2024-08-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animalv2", "0001_initial"),
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
        ("study", "0012_study_eco"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyLevelValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="Identify the health system of concern (e.g., Hepatic, Nervous, Reproductive)",
                        max_length=128,
                        verbose_name="System or health effect basis",
                    ),
                ),
                (
                    "value_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "LOEL"),
                            (1, "NOEL"),
                            (2, "LOAEL"),
                            (3, "NOAEL"),
                            (4, "BMDL"),
                            (5, "BMD"),
                        ],
                        help_text="Type of derived value",
                    ),
                ),
                ("value", models.FloatField(help_text="The value")),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="General comments related to the derivation of this value",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="study.study",
                    ),
                ),
                (
                    "units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.doseunits",
                    ),
                ),
            ],
        ),
    ]
