# Generated by Django 5.1.9 on 2025-06-02 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animalv2", "0002_studylevelvalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalgroup",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="chemical",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="dataextraction",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="dosegroup",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="doseresponseanimalleveldata",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="doseresponsegroupleveldata",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="endpoint",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="experiment",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="observationtime",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="studylevelvalue",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="treatment",
            options={"ordering": ("id",)},
        ),
    ]
