# Generated by Django 5.0 on 2024-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "animalv2",
            "0002_rename_exposure_outcome_durection_treatment_exposure_outcome_duration",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="name",
            field=models.CharField(
                blank=True, help_text="Endpoint/Adverse Outcome", max_length=128
            ),
        ),
    ]
