# Generated by Django 5.0 on 2024-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animalv2", "0003_endpoint_name"),
        ("assessment", "0037_delete_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="additional_tags",
            field=models.ManyToManyField(blank=True, to="assessment.effecttag"),
        ),
    ]
