# Generated by Django 5.0 on 2024-03-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animalv2", "0004_endpoint_additional_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataextraction",
            name="treatment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="v2_data_extractions",
                to="animalv2.treatment",
            ),
            preserve_default=False,
        ),
    ]
