# Generated by Django 1.9.4 on 2016-06-14 14:52


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epi", "0005_auto_20151120_1013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studypopulation",
            name="design",
            field=models.CharField(
                choices=[
                    (b"CO", b"Cohort"),
                    (b"CX", b"Cohort (Retrospective)"),
                    (b"CY", b"Cohort (Prospective)"),
                    (b"CC", b"Case-control"),
                    (b"NC", b"Nested case-control"),
                    (b"CR", b"Case report"),
                    (b"SE", b"Case series"),
                    (b"RT", b"Randomized controlled trial"),
                    (b"NT", b"Non-randomized controlled trial"),
                    (b"CS", b"Cross-sectional"),
                ],
                max_length=2,
            ),
        ),
    ]
