# Generated by Django 2.2.14 on 2020-08-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0015_multiple_countries"),
    ]

    operations = [
        migrations.AlterModelOptions(name="outcome", options={"ordering": ("id",)},),
        migrations.AlterModelOptions(name="result", options={"ordering": ("id",)},),
    ]
