# Generated by Django 2.2.15 on 2020-10-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0017_endpoint_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(name="result", options={"ordering": ("id",)},),
    ]
