# Generated by Django 5.2.15 on 2026-06-26 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epi", "0018_django31"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonset",
            name="outcome",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_sets",
                to="epi.outcome",
            ),
        ),
        migrations.AlterField(
            model_name="comparisonset",
            name="study_population",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_sets",
                to="epi.studypopulation",
            ),
        ),
    ]
