# Generated by Django 3.1.3 on 2021-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0018_django31"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="isControl",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No"), (None, "N/A")],
                default=None,
                help_text="Should this group be interpreted as a null/control group, if applicable",
                null=True,
                verbose_name="Control?",
            ),
        ),
    ]
