# Generated by Django 5.0.6 on 2024-08-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0038_alter_assessmentdetail_qa_id"),
        ("mgmt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="open",
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(default="", help_text="User notes on status"),
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("value", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(help_text="Status order in assessment")),
                ("color", models.CharField(help_text="Hexadecimal color code", max_length=7)),
                (
                    "terminal_status",
                    models.BooleanField(
                        default=False,
                        help_text='If a study has this status, should it be considered "finished" for this task type. For example, completed/abandoned would be terminal, while started/ongoing would not be.',
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assessment.assessment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="new_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mgmt.taskstatus",
            ),
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "order",
                    models.PositiveSmallIntegerField(help_text="Task order in an assessment"),
                ),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assessment.assessment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskTrigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Create Study"),
                            (20, "Data Extraction"),
                            (30, "Modify Study Evaluation"),
                            (40, "Complete Study Evaluation"),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "current_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_triggers",
                        to="mgmt.taskstatus",
                    ),
                ),
                (
                    "next_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_triggers",
                        to="mgmt.taskstatus",
                    ),
                ),
                (
                    "task_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mgmt.tasktype"
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assessment.assessment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="new_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mgmt.tasktype",
            ),
        ),
    ]
