# Generated by Django 5.0.6 on 2024-08-19 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgmt", "0004_populate_task_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="type",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="new_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="new_type",
            new_name="type",
        ),
    ]
