# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0008_auto_20170221_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupresult',
            name='lower_range',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Lower Range'),
        ),
        migrations.AddField(
            model_name='groupresult',
            name='upper_range',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Upper Range'),
        ),
    ]
