# Generated by Django 2.2.13 on 2020-07-16 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_dataset"),
        ("animal", "0025_experiment_has_multiple_generations"),
    ]

    operations = [
        migrations.CreateModel(
            name="BioassayAssessmentSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vocabulary",
                    models.PositiveSmallIntegerField(choices=[(1, "EHV")], null=True, blank=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bioassay_settings",
                        to="assessment.Assessment",
                    ),
                ),
            ],
        ),
    ]
