# Generated by Django 2.2.14 on 2020-08-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0025_experiment_has_multiple_generations"),
    ]

    operations = [
        migrations.AlterModelOptions(name="endpoint", options={"ordering": ("id",)},),
    ]
