# Generated by Django 2.2.15 on 2020-08-28 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animal", "0026_experiment_dtxsid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endpoint",
            options={"ordering": ("id",)},
        ),
    ]
