# Generated by Django 3.1.2 on 2020-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animal", "0029_strip_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dosingregime",
            name="positive_control",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No"), (None, "Unknown")],
                default=False,
                help_text="Was a positive control used?",
                null=True,
            ),
        ),
    ]
