# Generated by Django 3.1.3 on 2021-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0030_django31"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dosingregime",
            name="positive_control",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No"), (None, "Unknown")],
                default=False,
                help_text="Was a positive control used?",
                null=True,
            ),
        ),
    ]
