# Generated by Django 3.2.5 on 2021-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0030_django31"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpoint", old_name="diagnostic", new_name="as_reported",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="as_reported",
            field=models.TextField(
                help_text="List the endpoint/adverse outcome name as used in the study. This will help during QA/QC of the extraction to the original study in cases where the endpoint/adverse outcome name is adjusted for consistency across studies or assessments.",
                verbose_name="Endpoint Name in Study",
            ),
        ),
    ]
