# Generated by Django 3.2.14 on 2022-08-10 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal", "0030_django31"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpointgroup",
            name="treatment_effect",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "not reported"), (1, "yes ↑"), (2, "yes ↓"), (3, "yes"), (4, "no")],
                default=None,
                help_text="Expert judgement based report of treatment related effects (add direction if known). Use when statistical analysis not available. In results comments, indicate whether it was author judgment or assessment team judgement",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="endpointgroup",
            name="significance_level",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Enter statistical significance level for the effect. Typically this is as presented in the study. Indicate in the results comment field if it is based on statistical analysis conducted by the assessment team",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Statistical significance level",
            ),
        ),
    ]
