site_name: HAWC Documentation
theme:
  name: material
  favicon: static/img/favicon-128.png
  logo: static/img/favicon-128.png
  palette:
    primary: blue
    accent: cyan
  features:
    - navigation.tracking
nav:
  - index.md
  - development.md
  - client.md
  - database.md
  - deployment.md
  - statistical-methods.md
  - project-management.md
  - appendix-a-ci.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
        generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
