# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:46
from __future__ import unicode_literals

from django.db import migrations
import json


def add_barchart(apps, schema_editor):
    NULL_CASE = '---'
    DataPivot = apps.get_model("summary", "DataPivot")
    for obj in DataPivot.objects.all():
        try:
            settings = json.loads(obj.settings)
        except ValueError:
            settings = False

        if settings:
            settings['plot_settings']['as_barchart'] = False
            settings['barchart'] = {
                'dpe': NULL_CASE,
                'field_name': NULL_CASE,
                'error_low_field_name': NULL_CASE,
                'error_high_field_name': NULL_CASE,
                'header_name': '',
                'error_header_name': '',
                'bar_style': 'base',
                'error_marker_style': 'base',
                'conditional_formatting': [],
                'error_show_tails': True,
            }
            obj.settings = json.dumps(settings)

            # don't change last_updated timestamp
            DataPivot.objects\
                .filter(id=obj.id)\
                .update(settings=obj.settings)


def remove_barchart(apps, schema_editor):
    DataPivot = apps.get_model("summary", "DataPivot")
    for obj in DataPivot.objects.all():
        try:
            settings = json.loads(obj.settings)
        except ValueError:
            settings = False

            if settings:
                settings['plot_settings'].pop('as_barchart')
                settings.pop('barchart')
                obj.settings = json.dumps(settings)

            # don't change last_updated timestamp
            DataPivot.objects\
                .filter(id=obj.id)\
                .update(settings=obj.settings)


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_add_na_option'),
    ]

    operations = [
        migrations.RunPython(add_barchart, reverse_code=remove_barchart),
    ]
